"""
Django settings for coda_project project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY')


#DEBUG Configurations
# DEBUG = True
if os.environ.get('ENVIRONMENT') == 'production':
    DEBUG = False
else:
    DEBUG = True


SECURE_SSL_REDIRECT = False


ALLOWED_HOSTS = ["*"]


AUTH_USER_MODEL = "accounts.CustomerUser"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
# Application definition
INSTALLED_APPS = [
    "main.apps.MainConfig",
    #'users.apps.UsersConfig',
    "accounts.apps.AccountsConfig",
    "finance.apps.FinanceConfig",
    "crispy_forms",
    'crispy_bootstrap4',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',
    "storages",
    "django_countries",
    "mathfilters",
    "mptt",
    "django_filters",
    # "django_celery_beat",
    # "django_celery_results",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    # "django_crontab",
]

# if DEBUG:
#     try:
#         import debug_toolbar
#         INSTALLED_APPS += ['debug_toolbar']
#         MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
#     except ImportError:
#         pass # If it's not installed, just don't use it


DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Static files configuration
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main/static'),
]

CRONJOBS = [
    # ("*/1 * * * *", "coda_project.cron.my_backup"),
    ("* * * * *", "application.msg_send_cron.SendMsgApplicatUser"),
    ("*/5 * * * *", "management.cron.advertisement"),
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
    # 'Middleware.MiddlewareFile.MailMiddleware'
    #'debug_toolbar.middleware.DebugToolbarMiddleware',

]

CSRF_COOKIE_SECURE = False

ROOT_URLCONF = "coda_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR , 'templates')
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.images",
                "main.context_processors.googledriveurl",
                "main.context_processors.services",
                "main.context_processors.healthcare_images",
            ],
            # 'libraries': {
            #     'customfilters': 'application.templatetags.customfilters',
            # }
        },
    },
]

#  ==============DBFUNCTIONS=====================================
def dba_values():
    if os.environ.get('ENVIRONMENT') == 'production':
        host = os.environ.get('HEROKU_DYCPROD_HOST')
        dbname = os.environ.get('HEROKU_DYCPROD_NAME')
        user = os.environ.get('HEROKU_DYCPROD_USER')
        password = os.environ.get('HEROKU_DYCPROD_PASS')

    elif os.environ.get('ENVIRONMENT') == 'staging':
        # In Heroku/Postgres it is Heroku_UAT
        host = os.environ.get('DB_NAME')
        dbname = os.environ.get('DB_NAME')
        user = os.environ.get('DB_USER')
        password = os.environ.get('DB_PASSWORD')

    else:
        # Test in staging database before staging deployment
        # host = os.environ.get('STG_DB_HOST')
        # dbname = os.environ.get('STG_DB_NAME') 
        # user = os.environ.get('STG_DB_USER')
        # password = os.environ.get('STG_DB_PASSWORD')

        # Test locally 
        host = os.environ.get('LOCAL_DB_HOST')
        dbname = os.environ.get('LOCAL_DB_NAME') 
        user = os.environ.get('LOCAL_DB_USER')
        password = os.environ.get('LOCAL_DB_PASSWORD') 





        

    return host,dbname,user,password  

WSGI_APPLICATION = "coda_project.wsgi.application"
import dj_database_url

host,dbname,user,password=dba_values() #herokuprod() #herokudev() #dblocal()  #herokudev(),
# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": dbname,
        "USER":user,
        "PASSWORD":password,
        "HOST": host
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#     }
# }


db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES["default"].update(db_from_env)
# db_from_env = dj_database_url.config(conn_max_age=600)
# DATABASES["default"].update(db_from_env)
# DATABASES ={'default': dj_database_url.config(conn_max_age=600)}
# DATABASES['default'] = dj_database_url.config(conn_max_age=600)   # to update if default db already exists.


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    # Use secure, production-appropriate password hashers. MD5 is insecure and should not be used.
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage" if DEBUG 
                   else "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}



CRISPY_TEMPLATE_PACK = "bootstrap4"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

LOGIN_REDIRECT_URL = "main:layout"
LOGIN_URL = "accounts:account-login"


#DC48K email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_INFO_USE_SSL = False
EMAIL_INFO_USE_TLS = True
EMAIL_INFO_PORT = 587
EMAIL_INFO_HOST = "smtp.privateemail.com"
EMAIL_INFO_USER = os.environ.get("DC48K_EMAIL_INFO_USER")
EMAIL_INFO_PASS = os.environ.get("DC48K_EMAIL_INFO_PASS")


DEFAULT_FROM_EMAIL = EMAIL_INFO_USER



AWS_S3_REGION_NAME = "us-east-2"  # change to your region
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None


# from celery.schedules import crontab

# CELERY_BROKER_URL = "redis://default:xjaoROhpU8Lbiz8OZskVTgyYDFAdSmlo@redis-11854.c240.us-east-1-3.ec2.cloud.redislabs.com:11854"
# CELERY_RESULT_BACKEND = "redis://default:xjaoROhpU8Lbiz8OZskVTgyYDFAdSmlo@redis-11854.c240.us-east-1-3.ec2.cloud.redislabs.com:11854"
# CELERY_ACCEPT_CONTENT = ["application/json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"
# CELERY_IMPORTS = "coda_project.task"

# CELERYBEAT_SCHEDULE = {
#     "run_on_every_1st": {
#         "task": "task_history",
#         "schedule": crontab(0, 0, day_of_month="1"),
#         #'schedule': crontab(),
#     },

#     "run_on_every_1st": {
#         "task": "advertisement",
#         "schedule": crontab(0, 0, day_of_month="1"),
#         #'schedule': crontab(),
#     },
# }

#==================PAYMENT SETTINGS=================
# Testing Payment methods
def payment_details(request):
    # ================MPESA/CASHAPP/VENMO========================
    phone_number =os.environ.get('MPESA_PHONE_NUMBER')
    email_info =os.environ.get('EMAIL_INFO_USER')
    cashapp = os.environ.get('CASHAPP'),
    venmo= os.environ.get('VENMO'),
    account_no = os.environ.get('STANBIC_ACCOUNT_NO'),
    return (phone_number,email_info,cashapp,venmo,account_no)


if os.environ.get('ENVIRONMENT') == 'production':
    SITEURL = "https://www.codanalytics.net"
elif os.environ.get('ENVIRONMENT') == 'testing':
   SITEURL = "https://codamakutano.herokuapp.com"
else:
    SITEURL = "http://localhost:8000"

SITE_ID = 1    
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = 'accounts.views.CustomSocialAccountAdapter'
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email"
        ],
        "AUTH_PARAMS": {"access_type": "online"}
    },
    "facebook": {
        "SCOPE": [
            "public_profile",
            "email"
        ],
        "AUTH_PARAMS": {"access_type": "online"}
    },
}

ACCOUNT_EMAIL_VERIFICATION = 'optional'  # or 'mandatory', depending on your setup
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True

LOGIN_REDIRECT_URL = "main:layout"
LOGIN_URL = "accounts:account-login"


# Azure configuration --> To host images used especially for the governance structure

AZURE_ACCOUNT_NAME = os.getenv('AZURE_STORAGE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = os.getenv('AZURE_STORAGE_ACCOUNT_KEY')
AZURE_CONTAINER = 'web-dev-media'
AZURE_URL_EXPIRATION_SECS = None

if AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY:
    # Production: use Azure Blob Storage
    DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
    MEDIA_URL = f'https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/'
else:
    # Local dev: serve media files from local filesystem
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'

SECURE_SSL_REDIRECT = False




# Stripe checkout & webhook configuration keys.
if os.environ.get('ENVIRONMENT') == 'production':
    STRIPE_SECRET_KEY = os.environ.get('STRIPE_LIVE_SECRET_KEY')
    STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_LIVE_WEBHOOK_SECRET')
else:
    STRIPE_SECRET_KEY = os.environ.get('STRIPE_TEST_SECRET_KEY')
    STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_TEST_WEBHOOK_SECRET')
