# Generated by Django 4.2.27 on 2026-01-06 12:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerFundsProtection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "segregation_policy",
                    models.TextField(
                        default="Customer funds are held in segregated accounts separate from operational funds. These funds are held in trust for customers and are not used for operational purposes. In the event of bankruptcy, customer funds are protected and will be returned to customers."
                    ),
                ),
                ("last_audit_date", models.DateField(blank=True, null=True)),
                ("next_audit_date", models.DateField(blank=True, null=True)),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("review_needed", "Review Needed"),
                            ("non_compliant", "Non-Compliant"),
                        ],
                        default="compliant",
                        max_length=20,
                    ),
                ),
                ("audit_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Funds Protection",
                "verbose_name_plural": "Customer Funds Protection",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invoice_number", models.CharField(editable=False, max_length=50, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=30, help_text="Number of days the subscription is valid"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="List of features included in this plan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Highlight this plan as featured"),
                ),
                (
                    "billing_period",
                    models.CharField(
                        default="per month",
                        help_text="Display text for billing period",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending Payment"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wallet", "Wallet"),
                            ("stripe", "Stripe (Card)"),
                            ("mpesa", "M-Pesa"),
                            ("paypal", "PayPal"),
                        ],
                        default="wallet",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="payments.subscriptionplan"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transaction_id", models.CharField(editable=False, max_length=100, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("subscription_payment", "Subscription Payment"),
                            ("invoice_payment", "Invoice Payment"),
                            ("refund", "Refund"),
                            ("adjustment", "Manual Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "payment_gateway",
                    models.CharField(
                        choices=[
                            ("wallet", "Wallet"),
                            ("stripe", "Stripe"),
                            ("mpesa", "M-Pesa"),
                            ("paypal", "PayPal"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gateway_transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store gateway response, fees, and other details",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts for failed transactions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SegregatedFundsLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entry_id", models.CharField(editable=False, max_length=50, unique=True)),
                (
                    "fund_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer Funds"),
                            ("operational", "Operational Funds"),
                            ("reserve", "Reserve Funds"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Customer Deposit"),
                            ("withdrawal", "Customer Withdrawal"),
                            ("fee_collection", "Fee Collection"),
                            ("refund", "Refund to Customer"),
                            ("transfer_to_operational", "Transfer to Operational"),
                            ("transfer_from_operational", "Transfer from Operational"),
                            ("reconciliation_adjustment", "Reconciliation Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fund_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fund_ledger_entries",
                        to="payments.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this fund movement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segregated Funds Ledger Entry",
                "verbose_name_plural": "Segregated Funds Ledger Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gateway_name",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("mpesa", "M-Pesa"), ("paypal", "PayPal")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this payment gateway"
                    ),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(default=True, help_text="Use test/sandbox credentials"),
                ),
                (
                    "config_data_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted JSON containing API keys and configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gateway_configs_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Gateway Config",
                "verbose_name_plural": "Payment Gateway Configs",
            },
        ),
        migrations.CreateModel(
            name="PaymentDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dispute_id", models.CharField(editable=False, max_length=50, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unauthorized", "Unauthorized Transaction"),
                            ("not_received", "Product/Service Not Received"),
                            ("not_as_described", "Not As Described"),
                            ("duplicate", "Duplicate Charge"),
                            ("cancelled", "Cancelled Service Still Charged"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "evidence",
                    models.JSONField(
                        blank=True, default=dict, help_text="Store evidence files and documents"
                    ),
                ),
                (
                    "evidence_files",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of uploaded evidence file paths",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("resolved_favor_user", "Resolved - User Favor"),
                            ("resolved_favor_merchant", "Resolved - Merchant Favor"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("amount_disputed", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_refunded",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                        ],
                        default="medium",
                        help_text="Auto-calculated risk level based on amount and reason",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("high", "High"), ("critical", "Critical")],
                        default="normal",
                        help_text="Auto-calculated priority for resolution",
                        max_length=10,
                    ),
                ),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Service Level Agreement deadline for resolution",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="payments.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Dispute",
                "verbose_name_plural": "Payment Disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="payments.usersubscription",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FundsReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reconciliation_id", models.CharField(editable=False, max_length=50, unique=True)),
                ("reconciliation_date", models.DateField()),
                (
                    "total_customer_wallets",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of all customer wallet balances",
                        max_digits=14,
                    ),
                ),
                (
                    "total_customer_funds_ledger",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total in segregated customer funds ledger",
                        max_digits=14,
                    ),
                ),
                (
                    "discrepancy_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Difference between wallets and ledger",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reconciled", "Reconciled"),
                            ("discrepancy", "Discrepancy Found"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliations_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliations_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Funds Reconciliation",
                "verbose_name_plural": "Funds Reconciliations",
                "ordering": ["-reconciliation_date"],
            },
        ),
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("velocity", "Unusual Transaction Velocity"),
                            ("amount", "Unusual Transaction Amount"),
                            ("location", "Unusual Location"),
                            ("device", "New Device"),
                            ("pattern", "Unusual Pattern"),
                            ("failed_attempts", "Multiple Failed Attempts"),
                            ("limit_exceeded", "Limit Exceeded Attempt"),
                        ],
                        max_length=30,
                    ),
                ),
                ("severity", models.CharField(default="medium", max_length=20)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("investigating", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                            ("confirmed_fraud", "Confirmed Fraud"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_fraud_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraud Alert",
                "verbose_name_plural": "Fraud Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_deposits",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "total_spending",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("total_transactions", models.IntegerField(default=0)),
                (
                    "average_transaction",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Analytics",
                "verbose_name_plural": "Financial Analytics",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="WalletSpendingLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("per_transaction", "Per Transaction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spending_limits",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Spending Limit",
                "verbose_name_plural": "Wallet Spending Limits",
                "unique_together": {("wallet", "limit_type")},
            },
        ),
        migrations.CreateModel(
            name="WalletActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("payment", "Payment"),
                            ("transfer", "Transfer"),
                            ("settings_change", "Settings Change"),
                            ("limit_change", "Limit Change"),
                            ("failed_attempt", "Failed Attempt"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Activity Log",
                "verbose_name_plural": "Wallet Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="payments_wa_user_id_18b2fc_idx"
                    ),
                    models.Index(fields=["action_type"], name="payments_wa_action__ca741c_idx"),
                    models.Index(fields=["is_suspicious"], name="payments_wa_is_susp_bd72a8_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["transaction_id"], name="payments_tr_transac_e96a4f_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-created_at"], name="payments_tr_user_id_d7ba42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="payments_tr_status_96e6c0_idx"),
        ),
        migrations.AddIndex(
            model_name="segregatedfundsledger",
            index=models.Index(
                fields=["fund_type", "-created_at"], name="payments_se_fund_ty_a45442_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="segregatedfundsledger",
            index=models.Index(fields=["entry_type"], name="payments_se_entry_t_ced1fc_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentdispute",
            index=models.Index(
                fields=["status", "sla_deadline"], name="payments_pa_status_abfeab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdispute",
            index=models.Index(
                fields=["priority", "created_at"], name="payments_pa_priorit_429a14_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fundsreconciliation",
            unique_together={("reconciliation_date",)},
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(
                fields=["user", "-created_at"], name="payments_fr_user_id_7807d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(fields=["status"], name="payments_fr_status_ba653a_idx"),
        ),
        migrations.AddIndex(
            model_name="fraudalert",
            index=models.Index(fields=["alert_type"], name="payments_fr_alert_t_c79e66_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="financialanalytics",
            unique_together={("user", "period_type", "period_start")},
        ),
    ]
