# Generated by Django 5.2.7 on 2025-11-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(default='per month', help_text='Display text for billing period', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight this plan as featured'),
        ),
    ]
