# Generated by Django 3.2.6 on 2025-12-21 22:29

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("ad_title", models.CharField(blank=True, max_length=100, null=True)),
                ("bulletin", models.CharField(blank=True, max_length=100, null=True)),
                ("short_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company_site",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "meeting_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("video_link", models.CharField(blank=True, max_length=500, null=True)),
                ("signature", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Ads",
            },
        ),
        migrations.CreateModel(
            name="Whatsapp_Groups",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("group_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("group_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "participants",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Finance", "Finance"),
                            ("IT", "IT"),
                            ("Internal", "Internal"),
                            ("Political", "Political"),
                            ("Business", "Business"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=25,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("investments", "investments"),
                            ("data_analysis", "data_analysis"),
                            ("coda", "coda"),
                            ("Job_Support", "Job_Support"),
                            ("interview", "interview"),
                            ("mentorship", "mentorship"),
                            ("automation", "automation"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "WhatsApp Groups",
            },
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["created_at"], name="marketing_w_created_77c658_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["updated_at"], name="marketing_w_updated_167afa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["is_active"], name="marketing_w_is_acti_0ae1b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["is_featured"], name="marketing_w_is_feat_f18a47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["category"], name="marketing_w_categor_a5538c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(fields=["type"], name="marketing_w_type_b9b506_idx"),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["country"], name="marketing_w_country_5f5bdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(fields=["slug"], name="marketing_w_slug_7b1a65_idx"),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="marketing_w_is_acti_d6579f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["category", "is_active"], name="marketing_w_categor_8ac755_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["type", "is_active"], name="marketing_w_type_ce3d9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapp_groups",
            index=models.Index(
                fields=["country", "is_active"], name="marketing_w_country_1c40d8_idx"
            ),
        ),
        migrations.AddField(
            model_name="ads",
            name="image_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_image",
                to="main.assets",
            ),
        ),
        migrations.AddField(
            model_name="ads",
            name="my_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["created_at"], name="marketing_a_created_ed5fa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["updated_at"], name="marketing_a_updated_159a7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["is_active"], name="marketing_a_is_acti_2c08ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["is_featured"], name="marketing_a_is_feat_d71fd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["company"], name="marketing_a_company_b7baa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["my_user"], name="marketing_a_my_user_b9c967_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="marketing_a_is_acti_3855ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["company", "is_active"], name="marketing_a_company_48be1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ads",
            index=models.Index(
                fields=["created_at", "is_active"],
                name="marketing_a_created_07401f_idx",
            ),
        ),
    ]
