# Generated by Django 3.2.6 on 2026-01-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_userpreferences_userprofile_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymember',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RenameField(
            model_name='communitymember',
            old_name='joined_at',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='communitymember',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='is_public_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='profession',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_profiles/'),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='region',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
