# Generated by Django 3.2.6 on 2026-01-27 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_userpreferences_userprofile_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'Tech & IT'), ('healthcare', 'Healthcare'), ('business', 'Business & Finance'), ('education', 'Education'), ('legal', 'Legal Services'), ('engineering', 'Engineering'), ('creative', 'Creative & Design'), ('other', 'Other')], max_length=50)),
                ('membership_type', models.CharField(choices=[('verified', 'Verified'), ('premium', 'Premium')], default='verified', max_length=20)),
                ('expertise', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='directory_photos/')),
                ('initials', models.CharField(blank=True, max_length=5)),
                ('avatar_color', models.CharField(default='#059669', max_length=7)),
                ('title_color', models.CharField(default='#059669', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
