# Generated by Django 3.2.6 on 2026-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_userpreferences_userprofile_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Tech & IT', 'Tech & IT'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Legal', 'Legal'), ('Creative Arts', 'Creative Arts')], default='Tech & IT', max_length=50)),
                ('membership_type', models.CharField(choices=[('verified', 'Verified (Free)'), ('premium', 'Premium ($9/mo)')], default='verified', max_length=20)),
                ('expertise_summary', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
