# Generated by Django 3.2.6 on 2026-01-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20260127_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('region_city', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'Tech & IT'), ('legal', 'Legal'), ('finance', 'Finance & Accounting'), ('health', 'Healthcare'), ('education', 'Education'), ('business', 'Business & Consulting'), ('creative', 'Creative & Media'), ('engineering', 'Engineering'), ('other', 'Other')], max_length=50)),
                ('membership_type', models.CharField(choices=[('verified', 'Verified (Free)'), ('premium', 'Premium ($9/mo)')], default='verified', max_length=20)),
                ('expertise_summary', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='directory_profiles/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directory_profile', to='communities.communitymember')),
            ],
        ),
    ]
