# Generated by Django 3.2.6 on 2026-01-27 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0003_directorymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorymember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
