# Generated by Django 3.2.6 on 2026-01-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_directoryprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
