# Generated by Django 3.2.6 on 2026-02-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_verifiedmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('region_city', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'Tech & IT'), ('legal', 'Legal'), ('finance', 'Finance & Accounting'), ('health', 'Healthcare'), ('education', 'Education'), ('business', 'Business & Consulting'), ('creative', 'Creative & Media'), ('engineering', 'Engineering'), ('other', 'Other')], max_length=50)),
                ('membership_type', models.CharField(choices=[('verified', 'Verified (Free)'), ('premium', 'Premium ($9/mo)')], default='verified', max_length=20)),
                ('expertise_summary', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='directory_profiles/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VerifiedMember',
        ),
        migrations.AlterModelOptions(
            name='communitymember',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RenameField(
            model_name='communitymember',
            old_name='joined_at',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='communitymember',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='is_public_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='profession',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_profiles/'),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='region',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directoryprofile',
            name='community_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directory_profile', to='communities.communitymember'),
        ),
    ]
