# Generated by Django 3.2.6 on 2026-02-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_directorymember_user'),
        ('communities', '0005_alter_commentp_created_at'),
    ]

    operations = [
    ]
