# Generated by Django 3.2.6 on 2026-02-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_merge_20260218_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectoryMember',
        ),
    ]
