# Generated by Django 6.0.6 on 2026-07-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='secure_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='district',
            field=models.CharField(blank=True, choices=[('gasabo', 'Gasabo'), ('kicukiro', 'Kicukiro'), ('nyarugenge', 'Nyarugenge'), ('rubavu', 'Rubavu'), ('musanze', 'Musanze'), ('huye', 'Huye'), ('rusizi', 'Rusizi'), ('nyagatare', 'Nyagatare')], max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.CharField(blank=True, choices=[('lost', 'Lost / Misplaced'), ('damaged', 'Damaged'), ('name_change', 'Name Change'), ('expired', 'Expired'), ('first_time', 'First Time Application'), ('correction', 'Correction of Details'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='service',
            field=models.CharField(choices=[('national_id_replacement', 'National ID Replacement'), ('birth_certificate', 'Birth Certificate'), ('passport', 'Passport Application'), ('good_conduct', 'Certificate of Good Conduct'), ('marriage_certificate', 'Marriage Certificate'), ('business_permit', 'Business Permit')], default='national_id_replacement', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
