version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - fastapi-network
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESSPASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - fastapi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  fastapi-network:
    driver: bridge 