-- ===== Migration 0017: ServiceRequest =====
CREATE TABLE IF NOT EXISTS "main_servicerequest" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "service_type" varchar(30) NOT NULL,
    "full_name" varchar(200) NOT NULL,
    "email" varchar(254) NOT NULL,
    "phone" varchar(30) NOT NULL,
    "consultation_type" varchar(50) NOT NULL,
    "preferred_language" varchar(50) NOT NULL,
    "location" varchar(200) NOT NULL,
    "question" text NOT NULL,
    "urgency" varchar(30) NOT NULL,
    "additional_notes" text NOT NULL,
    "status" varchar(20) NOT NULL,
    "admin_notes" text NOT NULL,
    "reply_message" text NOT NULL,
    "replied_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "assigned_to_id" integer NULL
);
ALTER TABLE "main_servicerequest" ADD CONSTRAINT "main_servicerequest_assigned_to_id_d137d42b_fk_accounts_" FOREIGN KEY ("assigned_to_id") REFERENCES "accounts_customeruser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "main_servicerequest_assigned_to_id_d137d42b" ON "main_servicerequest" ("assigned_to_id");

-- ===== Migration 0019: communitymember.user + CommunityMessage =====
ALTER TABLE "main_communitymember" ADD COLUMN IF NOT EXISTS "user_id" integer NULL;
ALTER TABLE "main_communitymember" ADD CONSTRAINT "main_communitymember_user_id_4191695b_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_customeruser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE UNIQUE INDEX IF NOT EXISTS "unique_user_community_member" ON "main_communitymember" ("user_id") WHERE "user_id" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "main_communitymember_user_id_4191695b" ON "main_communitymember" ("user_id");

CREATE TABLE IF NOT EXISTS "main_communitymessage" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "subject" varchar(200) NOT NULL,
    "body" text NOT NULL,
    "is_read" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "sender_id" integer NOT NULL,
    "recipient_id" integer NOT NULL,
    "parent_message_id" bigint NULL
);
ALTER TABLE "main_communitymessage" ADD CONSTRAINT "main_communitymessage_sender_id_fk" FOREIGN KEY ("sender_id") REFERENCES "main_communitymember" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_communitymessage" ADD CONSTRAINT "main_communitymessage_recipient_id_fk" FOREIGN KEY ("recipient_id") REFERENCES "main_communitymember" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_communitymessage" ADD CONSTRAINT "main_communitymessage_parent_message_id_fk" FOREIGN KEY ("parent_message_id") REFERENCES "main_communitymessage" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "main_communitymessage_sender_id_6c3a13da" ON "main_communitymessage" ("sender_id");
CREATE INDEX IF NOT EXISTS "main_communitymessage_recipient_id_25d061b3" ON "main_communitymessage" ("recipient_id");
CREATE INDEX IF NOT EXISTS "main_communitymessage_parent_message_id_a99a0050" ON "main_communitymessage" ("parent_message_id");

-- ===== Migration 0020: communitypost.author + updated_at =====
ALTER TABLE "main_communitypost" ADD COLUMN IF NOT EXISTS "author_id" integer NULL;
ALTER TABLE "main_communitypost" ADD CONSTRAINT "main_communitypost_author_id_f6e43382_fk_accounts_" FOREIGN KEY ("author_id") REFERENCES "accounts_customeruser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "main_communitypost_author_id_f6e43382" ON "main_communitypost" ("author_id");
ALTER TABLE "main_communitypost" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "main_communitypost" ALTER COLUMN "updated_at" DROP DEFAULT;

-- ===== Migration 0021: DonationOrganization, Faq, Gallery, GetHelp, History =====
CREATE TABLE IF NOT EXISTS "main_donationorganization" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "contact_email" varchar(254) NOT NULL
);
CREATE TABLE IF NOT EXISTS "main_faq" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "question" varchar(255) NOT NULL,
    "answer" text NOT NULL,
    "category" varchar(255) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);
CREATE TABLE IF NOT EXISTS "main_gallery" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(100) NOT NULL,
    "description" text NULL,
    "image" varchar(100) NOT NULL,
    "uploaded_at" timestamp with time zone NOT NULL,
    "event_date" date NOT NULL
);
CREATE TABLE IF NOT EXISTS "main_gethelp" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "content" text NOT NULL,
    "link" varchar(100) NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);
CREATE TABLE IF NOT EXISTS "main_history" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "year" integer NOT NULL,
    "title" varchar(200) NOT NULL,
    "description" text NOT NULL,
    "image" varchar(100) NULL,
    "order" integer NOT NULL CHECK ("order" >= 0)
);
ALTER TABLE "main_donationorganization" ADD COLUMN IF NOT EXISTS "linked_profile_id" integer NULL;
ALTER TABLE "main_donationorganization" ADD CONSTRAINT "main_donationorganiz_linked_profile_id_8d75f9b0_fk_accounts_" FOREIGN KEY ("linked_profile_id") REFERENCES "accounts_customeruser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_donationorganization" ADD CONSTRAINT "main_donationorganization_linked_profile_id_key" UNIQUE ("linked_profile_id");
