from django.contrib import admin
from . models import *

# Register your models here.
admin.site.register(Projects)
admin.site.register(Access)
admin.site.register(Status)
admin.site.register(Roles)
admin.site.register(NormalizedTitles)
admin.site.register(Titles)
admin.site.register(Locations)
admin.site.register(Industry)
admin.site.register(Departments)
admin.site.register(Persons)
admin.site.register(PersonRole)
admin.site.register(Orgs)
admin.site.register(Positions)
admin.site.register(PositionRole)
admin.site.register(OrgHier)
admin.site.register(ExtPositions)
admin.site.register(ExtPersons)
admin.site.register(BenchmarkFact)
admin.site.register(AssociationOrgPosition)
admin.site.register(AssociationOrgPersonPosition)
admin.site.register(AssociationOrgPerson)
