# Generated by Django 5.2.11 on 2026-03-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI_generated summary for index page'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10),
        ),
    ]
