# Generated by Django 4.2.27 on 2026-01-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version number (e.g., '1.0', '1.1')", max_length=20, unique=True
                    ),
                ),
                ("title", models.CharField(help_text="Title of privacy policy", max_length=200)),
                ("content", models.TextField(help_text="Full text of privacy policy")),
                ("summary", models.TextField(blank=True, help_text="Summary of key changes")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Whether this is the current active version"
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(help_text="When this version becomes effective"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Policy Version",
                "verbose_name_plural": "Privacy Policy Versions",
                "db_table": "gdpr_privacy_policy_version",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(fields=["-effective_date"], name="gdpr_privac_effecti_caecfb_idx"),
                    models.Index(fields=["is_active"], name="gdpr_privac_is_acti_eb0cf4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV"), ("pdf", "PDF")],
                        default="json",
                        help_text="Format for exported data",
                        max_length=10,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, help_text="Path to exported file", max_length=500),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="Size of exported file in bytes", null=True
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, help_text="Number of times file was downloaded"),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When export file expires (30 days)", null=True
                    ),
                ),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if export failed"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting data export",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Export Request",
                "verbose_name_plural": "Data Export Requests",
                "db_table": "gdpr_data_export_request",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-requested_at"], name="gdpr_data_e_user_id_5a7ada_idx"
                    ),
                    models.Index(fields=["status"], name="gdpr_data_e_status_11977f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("grace_period", "Grace Period"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="User's reason for deletion (optional)"),
                ),
                (
                    "grace_period_end",
                    models.DateTimeField(
                        blank=True, help_text="End of 30-day grace period", null=True
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_deletion_at",
                    models.DateTimeField(
                        blank=True, help_text="When deletion is scheduled to occur", null=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="When deletion was completed", null=True
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When request was cancelled", null=True
                    ),
                ),
                (
                    "data_removed",
                    models.JSONField(
                        blank=True, default=dict, help_text="Record of what data was removed"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if deletion failed"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting deletion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Deletion Request",
                "verbose_name_plural": "Data Deletion Requests",
                "db_table": "gdpr_data_deletion_request",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-requested_at"], name="gdpr_data_d_user_id_001c2a_idx"
                    ),
                    models.Index(fields=["status"], name="gdpr_data_d_status_5b1dbd_idx"),
                    models.Index(
                        fields=["scheduled_deletion_at"], name="gdpr_data_d_schedul_325cc7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms_of_service", "Terms of Service"),
                            ("privacy_policy", "Privacy Policy"),
                            ("marketing", "Marketing Communications"),
                            ("analytics", "Analytics & Tracking"),
                            ("third_party_sharing", "Third-Party Data Sharing"),
                            ("cookies", "Cookie Usage"),
                            ("data_processing", "Data Processing"),
                        ],
                        db_index=True,
                        help_text="Type of consent given",
                        max_length=50,
                    ),
                ),
                (
                    "is_given",
                    models.BooleanField(
                        default=False, help_text="Whether consent is currently given"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version of policy/terms user consented to", max_length=20
                    ),
                ),
                (
                    "consent_text",
                    models.TextField(blank=True, help_text="Full text of what user consented to"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address when consent was given", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Browser user agent when consent was given",
                    ),
                ),
                (
                    "given_at",
                    models.DateTimeField(blank=True, help_text="When consent was given", null=True),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, help_text="When consent was withdrawn", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who gave consent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Record",
                "verbose_name_plural": "Consent Records",
                "db_table": "gdpr_consent_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"], name="gdpr_consen_user_id_243e75_idx"
                    ),
                    models.Index(fields=["-created_at"], name="gdpr_consen_created_00c7dc_idx"),
                ],
            },
        ),
    ]
