# Generated by Django 3.2.6 on 2025-10-27 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('gpt4_primary', 'GPT-4 Primary Model'), ('gpt35_fallback', 'GPT-3.5 Fallback Model'), ('claude3_backup', 'Claude-3 Backup Model'), ('local_offline', 'Local Offline Model')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_order', models.IntegerField(default=1)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('temperature', models.FloatField(default=0.3)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_model_configuration',
                'ordering': ['priority_order'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_analyses', models.IntegerField(default=0)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('presentation_mode', models.BooleanField(default=False)),
                ('stakeholder_type', models.CharField(blank=True, choices=[('investor', 'Investor'), ('government', 'Government Representative'), ('diaspora', 'Diaspora Member'), ('general', 'General Public')], max_length=50, null=True)),
                ('is_authenticated_session', models.BooleanField(default=False, help_text='Whether this is an authenticated user session')),
            ],
            options={
                'db_table': 'analysis_session',
            },
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'UseCase Categories',
                'db_table': 'getdata_case_category',
            },
        ),
        migrations.CreateModel(
            name='CashappMail',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('from_mail', models.CharField(max_length=255)),
                ('to_mail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=50)),
                ('full_path', models.CharField(max_length=255)),
                ('text_mail', models.TextField()),
                ('received_date', models.CharField(max_length=255)),
                ('parsed_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cashapp',
                'db_table': 'getdata_cashappmail',
            },
        ),
        migrations.CreateModel(
            name='DiasporaAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('analysis_type', models.CharField(choices=[('remittance_analysis', 'Remittance Analysis'), ('trade_facilitation', 'Trade Facilitation'), ('investment_opportunities', 'Investment Opportunities'), ('education_pathways', 'Education Pathways'), ('healthcare_access', 'Healthcare Access')], max_length=50)),
                ('user_input', models.JSONField()),
                ('ai_prediction', models.JSONField()),
                ('model_used', models.CharField(choices=[('gpt4_primary', 'GPT-4 Primary Model'), ('gpt35_fallback', 'GPT-3.5 Fallback Model'), ('claude3_backup', 'Claude-3 Backup Model'), ('local_offline', 'Local Offline Model')], max_length=100)),
                ('confidence_score', models.FloatField()),
                ('processing_time', models.FloatField()),
                ('fallback_used', models.BooleanField(default=False)),
                ('is_real_ai', models.BooleanField(default=False, help_text='Whether this used real AI or fallback data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'diaspora_analysis_data',
            },
        ),
        migrations.CreateModel(
            name='DynamicExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'getdata_dynamic_excel_data',
            },
        ),
        migrations.CreateModel(
            name='Editable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.JSONField(null=True)),
                ('threshhold', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'General',
                'db_table': 'getdata_editable',
            },
        ),
        migrations.CreateModel(
            name='GotoMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_topic', models.CharField(blank=True, max_length=250, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('recording', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_start_time', models.CharField(blank=True, max_length=250, null=True)),
                ('meeting_end_time', models.CharField(blank=True, max_length=250, null=True)),
                ('meeting_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_email', models.CharField(blank=True, max_length=150, null=True)),
                ('attendee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('attendee_email', models.CharField(blank=True, max_length=150, null=True)),
                ('download_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('attendee_duration', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'getdata_gotomeetings',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_in_code', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_code_crash', models.CharField(blank=True, max_length=255, null=True)),
                ('exception', models.CharField(blank=True, max_length=255, null=True)),
                ('api', models.URLField(blank=True, max_length=255, null=True)),
                ('crated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Logs',
                'db_table': 'getdata_logs',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(db_index=True, help_text='Unique GoToMeeting ID', max_length=100, unique=True)),
                ('topic', models.CharField(help_text='Meeting subject/topic', max_length=500)),
                ('meeting_type', models.CharField(blank=True, help_text='Type of meeting (e.g., General Meeting, 1-1 session)', max_length=100)),
                ('start_time', models.DateTimeField(db_index=True, help_text='Meeting start time (UTC)')),
                ('end_time', models.DateTimeField(help_text='Meeting end time (UTC)')),
                ('duration_minutes', models.IntegerField(default=0, help_text='Total meeting duration in minutes')),
                ('recording_url', models.URLField(blank=True, help_text='URL to meeting recording', max_length=1000, null=True)),
                ('download_url', models.URLField(blank=True, help_text='Direct download URL for recording', max_length=1000, null=True)),
                ('is_recorded', models.BooleanField(default=False, help_text='Whether meeting was recorded')),
                ('google_drive_url', models.URLField(blank=True, help_text='Google Drive URL if recording uploaded', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GoToMeeting',
                'verbose_name_plural': 'GoToMeetings',
                'db_table': 'gotomeeting_meeting',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingActivityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id_pattern', models.CharField(help_text='Meeting ID or pattern to match', max_length=100, unique=True)),
                ('activity_name', models.CharField(help_text='Activity name for task management', max_length=200)),
                ('task_points', models.IntegerField(default=0, help_text='Task points to award for attendance')),
                ('min_duration_minutes', models.IntegerField(default=3, help_text='Minimum attendance duration to qualify for points')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is currently active')),
                ('description', models.TextField(blank=True, help_text='Description of this meeting type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting Activity Mapping',
                'verbose_name_plural': 'Meeting Activity Mappings',
                'db_table': 'meeting_activity_mapping',
                'ordering': ['activity_name'],
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='gotomeeting', help_text='Service name (gotomeeting, google_drive, etc.)', max_length=50, unique=True)),
                ('access_token', models.TextField(help_text='Encrypted access token')),
                ('refresh_token', models.TextField(help_text='Encrypted refresh token')),
                ('token_type', models.CharField(default='Bearer', help_text='Token type', max_length=50)),
                ('expires_at', models.DateTimeField(help_text='When access token expires')),
                ('scope', models.TextField(blank=True, help_text='Token scope/permissions')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether token is currently valid')),
                ('last_refreshed_at', models.DateTimeField(blank=True, help_text='When token was last refreshed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OAuth Token',
                'verbose_name_plural': 'OAuth Tokens',
                'db_table': 'oauth_token',
            },
        ),
        migrations.CreateModel(
            name='OpenaiPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='What category', max_length=250, null=True)),
                ('subcategory', models.CharField(blank=True, choices=[('introduction', 'introduction'), ('Project Story', 'project story'), ('performance', 'performance'), ('methodology', 'methodology'), ('sdlc', 'sdlc'), ('testing', 'testing'), ('environment', 'environment'), ('resume', 'resume'), ('Other', 'Other')], default=1, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, help_text='What topic', max_length=250, null=True)),
                ('expert_question', models.CharField(blank=True, help_text='Describe your question', max_length=250, null=True)),
                ('context_description', models.TextField(blank=True, default='Domain such as IT Project Experice on roles such as Project Manager, Business Analysis', help_text='Provide context if possible', null=True)),
                ('role', models.CharField(blank=True, default='Expert in IT Field', help_text='Explain your role', max_length=250, null=True)),
                ('clarification_description', models.TextField(blank=True, default="Utilize professional diction,Maintain a formal,friendly and helpful tone and Keep the response concise to maintain the reader's engagement", help_text='Provide clarification or use default', null=True)),
                ('words', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'getdata_openaiprompt',
            },
        ),
        migrations.CreateModel(
            name='ReplyMail',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('from_mail', models.CharField(max_length=255)),
                ('to_mail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text_mail', models.TextField()),
                ('received_date', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ReplyMail',
                'db_table': 'getdata_replymail',
            },
        ),
        migrations.CreateModel(
            name='upwork_Transanctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=250, null=True)),
                ('ref_Id', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('agency', models.CharField(blank=True, max_length=250, null=True)),
                ('freelancer', models.CharField(blank=True, max_length=250, null=True)),
                ('team', models.CharField(blank=True, max_length=250, null=True)),
                ('account_name', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.CharField(blank=True, max_length=250, null=True)),
                ('balance', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'getdata_upwork_transactions',
            },
        ),
        migrations.CreateModel(
            name='UpworkConnects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=1000)),
                ('payment_range', models.CharField(choices=[('50-80', '50 to 80 dollars'), ('80+', 'More than 80 dollars')], max_length=200)),
                ('duration_range', models.CharField(choices=[('1-3 months', '1 month to 3 months'), ('3-6 months', '3 months to 6 months'), ('6-12 months', '6 months to 1 year'), ('1 year+', 'More than 1 year')], max_length=200)),
                ('project_type', models.CharField(choices=[('ongoing', 'Ongoing'), ('from scratch', 'From Scratch')], max_length=200)),
                ('project_category', models.CharField(choices=[('ERP SYSTEM', 'ERP SYSTEM'), ('SAAS', 'SAAS'), ('TRAINING', 'TRAINING'), ('WEB DEVELOPMENT', 'Web Development'), ('BLOCKCHAIN', 'Blockchain')], max_length=200)),
            ],
            options={
                'db_table': 'getdata_upwork_connects',
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('form_start', 'Form Started'), ('form_submit', 'Form Submitted'), ('analysis_complete', 'Analysis Completed'), ('result_view', 'Results Viewed'), ('download', 'File Downloaded'), ('share', 'Content Shared'), ('error', 'Error Encountered'), ('session_start', 'Session Started'), ('session_end', 'Session Ended')], max_length=50)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('analysis_type', models.CharField(blank=True, choices=[('remittance_analysis', 'Remittance Analysis'), ('trade_facilitation', 'Trade Facilitation'), ('investment_opportunities', 'Investment Opportunities'), ('education_pathways', 'Education Pathways'), ('healthcare_access', 'Healthcare Access')], max_length=50, null=True)),
                ('event_data', models.JSONField(default=dict, help_text='Additional event-specific data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_behavior_analytics',
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('app', models.CharField(choices=[('main', 'main'), ('accounts', 'accounts'), ('application', 'application'), ('professional_services', 'professional_services'), ('ai_services', 'ai_services'), ('investing', 'investing'), ('management', 'management'), ('finance', 'finance'), ('marketing', 'marketing'), ('unified_dashboard', 'unified_dashboard'), ('portfolio', 'portfolio')], default='Other', max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('installation', models.TextField(blank=True, default='To implement this requirement, we need to install/access the following : 1. CODA Website, 2. CODA Google Drive, 3. Chatgpt, 3. Openai Key 4. Install ,Python, Postgres,VS CODE, and GIT, and finally create an account with GitHub, and Heroku you will also need access to AWS.', help_text='Provide tools used', null=True)),
                ('usage_link', models.CharField(blank=True, max_length=255, null=True)),
                ('deployment', models.CharField(blank=True, max_length=255, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('credits', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_sections', models.TextField(blank=True, null=True)),
                ('links', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, default=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_services.casecategory')),
                ('requirements_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.requirement')),
            ],
            options={
                'verbose_name_plural': 'UseCase',
                'db_table': 'getdata_usecase',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(help_text="Attendee's display name", max_length=200)),
                ('attendee_email', models.EmailField(help_text="Attendee's email address", max_length=254)),
                ('duration_minutes', models.IntegerField(default=0, help_text='How long attendee stayed in meeting (minutes)')),
                ('is_organizer', models.BooleanField(default=False, help_text='Whether attendee was the meeting organizer')),
                ('task_points_awarded', models.BooleanField(default=False, help_text='Whether task points were awarded for this attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(help_text='Meeting this attendee participated in', on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='ai_services.meeting')),
                ('user', models.ForeignKey(blank=True, help_text='Linked CODA user (if matched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Attendee',
                'verbose_name_plural': 'Meeting Attendees',
                'db_table': 'gotomeeting_attendee',
                'ordering': ['-duration_minutes'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_id'], name='gotomeeting_meeting_394d42_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time'], name='gotomeeting_start_t_40b9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['-start_time'], name='gotomeeting_start_t_6d2624_idx'),
        ),
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diasporaanalysisdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaspora_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['session_id', 'event_type'], name='user_behavi_session_f07319_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['timestamp'], name='user_behavi_timesta_a6bd97_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['analysis_type'], name='user_behavi_analysi_b7d0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['user', 'timestamp'], name='user_behavi_user_id_5bcefc_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendee',
            index=models.Index(fields=['attendee_email'], name='gotomeeting_attende_09e631_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendee',
            index=models.Index(fields=['user'], name='gotomeeting_user_id_03b36b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendee',
            unique_together={('meeting', 'attendee_email')},
        ),
        migrations.AddIndex(
            model_name='diasporaanalysisdata',
            index=models.Index(fields=['session_id', 'analysis_type'], name='diaspora_an_session_bf5d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='diasporaanalysisdata',
            index=models.Index(fields=['created_at'], name='diaspora_an_created_f7ccd8_idx'),
        ),
        migrations.AddIndex(
            model_name='diasporaanalysisdata',
            index=models.Index(fields=['model_used'], name='diaspora_an_model_u_3a9804_idx'),
        ),
    ]
