# Generated by Django 3.2.6 on 2025-03-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('repayment_period', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Recovery', 'Recovery'), ('Fully-paid', 'Fully-paid'), ('Default', 'Default')], max_length=255)),
                ('approval_date', models.DateField(null=True)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=20)),
                ('next_loan_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('weekly_installments', models.DecimalField(decimal_places=20, max_digits=20, null=True)),
                ('income_source', models.CharField(max_length=255, null=True)),
                ('security_item', models.CharField(max_length=255, null=True)),
                ('security_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('due_date', models.DateField(null=True)),
                ('referee_income_source', models.CharField(max_length=255, null=True)),
                ('days_to_due', models.IntegerField(default=0, null=True)),
                ('days_past_due', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField()),
                ('loanee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('referee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
