# Generated by Django 3.2.6 on 2025-03-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='weekly_installments',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
