# Generated by Django 5.2.3 on 2025-08-19 02:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=254)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField()),
                ("discounted_price", models.FloatField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "contract_length",
                    models.IntegerField(
                        choices=[
                            (1, "One Month"),
                            (2, "Two Months"),
                            (3, "Three Months"),
                            (12, "Open"),
                        ],
                        default=3,
                    ),
                ),
                ("is_direct", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("redirect_url_path", models.CharField(max_length=1024, null=True)),
            ],
            options={
                "verbose_name_plural": "Pricing",
            },
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_type",
        ),
        migrations.AddField(
            model_name="payment",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_partial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="original_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_purpose",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
