# Generated by Django 3.2.6 on 2025-09-20 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20250920_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipconfig',
            name='installment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 1, 22, 44, 11, 747281), null=True),
        ),
    ]
