# Generated by Django 3.2.6 on 2026-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_newslettersubscriber_opportunity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='subscribed_At',
            new_name='subscribed_at',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='Created_At',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(max_length=150),
        ),
    ]
