# Generated by Django 3.2.6 on 2026-02-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20260223_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='location',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('REAL_ESTATE', 'Real Estate'), ('SACCO', 'Sacco'), ('BOND', 'Bond'), ('SOFTWARE_ENGINEERING', 'Software Engineering')], max_length=50),
        ),
    ]
