# Generated by Django 5.2.3 on 2025-12-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_pricing_rename_user_payment_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Pricing",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
