# Generated by Django 3.2.6 on 2025-09-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payslipconfig_installment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Interest rate percentage', max_digits=5),
        ),
    ]
