# Generated by Django 3.2.6 on 2026-03-04 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20260304_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
