# Generated by Django 3.2.6 on 2026-02-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20260225_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
