# Generated by Django 3.2.6 on 2025-11-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        ('contenttypes', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = []
