# Generated by Django 3.2.6 on 2025-09-15 22:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('phone', models.CharField(default='90001', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Applicant'), (2, 'Student'), (3, 'Consultant'), (4, 'Investor'), (5, 'Explorer')], default=999)),
                ('sub_category', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is employee')),
                # ('is_client', models.BooleanField(default=False, verbose_name='Is Client')),
                # ('is_applicant', models.BooleanField(default=False, verbose_name='Is applicant')),
                # ('is_employee_contract_signed', models.BooleanField(default=False)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/doc/')),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='credential Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='credential safe URL')),
                ('description', models.TextField(default=None, max_length=1000)),
                ('link_name', models.CharField(default='General', max_length=255)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='No Password Needed', max_length=255, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='entered on')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('user_types', models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('Employee', 'Employee'), ('Other', 'Other')], default='Other', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'credentials',
            },
        ),
        migrations.CreateModel(
            name='CredentialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Required', max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='category safe URL')),
                ('description', models.TextField(default=None, max_length=1000)),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='entered on')),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HR Department', 'HR Department'), ('IT Department', 'IT Department'), ('Marketing Department', 'Marketing Department'), ('Finance Department', 'Finance Department'), ('Security Department', 'Security Department'), ('Management Department', 'Management Department'), ('Health Department', 'Health Department'), ('Other', 'Other')], default='Other', max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Department safe URL')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Is featured')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Group A', max_length=55, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('board', 'Board Members'), ('analytics_team', 'Analytics Team'), ('future_talent', 'Future Talent'), ('support_team', 'Support Team'), ('clients', 'Clients'), ('other', 'other')], default='Other', max_length=25)),
                ('title', models.CharField(default='Project Manager', max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Team Classification',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='Job title or position', max_length=255, null=True)),
                ('company', models.CharField(blank=True, help_text='Current employer or company', max_length=254, null=True)),
                ('description', models.TextField(blank=True, help_text='Professional summary or bio', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True)),
                ('education', models.IntegerField(choices=[(1, 'High School'), (2, 'Some College'), (3, "Bachelor's Degree"), (4, "Master's Degree"), (5, 'Doctorate')], default=3, help_text='Highest education level')),
                # ('skills', models.JSONField(blank=True, default=list, help_text='List of skills and competencies')),
                ('image', models.ImageField(blank=True, default='default.jpg', help_text='Profile picture', upload_to='Application_Profile_pics')),
                ('upload_a', models.FileField(blank=True, help_text='Document A', null=True, upload_to='Application_Profile/uploads')),
                ('upload_b', models.FileField(blank=True, help_text='Document B', null=True, upload_to='Application_Profile/uploads')),
                ('upload_c', models.FileField(blank=True, help_text='Document C', null=True, upload_to='Application_Profile/uploads')),
                ('national_id_no', models.CharField(blank=True, help_text='National ID number', max_length=254, null=True)),
                ('id_file', models.ImageField(blank=True, help_text='ID document', null=True, upload_to='id_files/')),
                ('emergency_name', models.CharField(blank=True, help_text='Emergency contact name', max_length=254, null=True)),
                ('emergency_address', models.CharField(blank=True, help_text='Emergency contact address', max_length=254, null=True)),
                ('emergency_citizenship', models.CharField(blank=True, help_text='Emergency contact citizenship', max_length=254, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Account number', max_length=254, null=True)),
                ('emergency_national_id_no', models.CharField(blank=True, help_text='Emergency contact ID', max_length=254, null=True)),
                ('emergency_phone', models.CharField(blank=True, help_text='Emergency contact phone', max_length=254, null=True)),
                ('emergency_email', models.EmailField(blank=True, help_text='Emergency contact email', max_length=254, null=True)),
                # ('emergency_contact_relationship', models.CharField(blank=True, choices=[('family', 'Family Member'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('employer', 'Employer'), ('other', 'Other')], help_text='Relationship to emergency contact', max_length=100, null=True)),
                # ('is_karen_country_club_member', models.BooleanField(default=False, help_text='Whether user is a Karen Country Club member')),
                # ('kcc_membership_number', models.CharField(blank=True, help_text='Karen Country Club membership number', max_length=100, null=True)),
                # ('kcc_membership_date', models.DateField(blank=True, help_text='Date when user became a KCC member', null=True)),
                # ('kcc_membership_expiry', models.DateField(blank=True, help_text='Karen Country Club membership expiry date', null=True)),
                # ('performance_tier', models.CharField(choices=[('new', 'New'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='new', help_text='Performance tier (affects loan terms for all users)', max_length=20)),
                # ('staff_level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('senior', 'Senior'), ('manager', 'Manager'), ('executive', 'Executive')], help_text='Staff level (affects loan terms)', max_length=20, null=True)),
                # ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income for loan eligibility', max_digits=10, null=True)),
                # ('employment_start_date', models.DateField(blank=True, help_text='Employment start date for loan eligibility', null=True)),
                # ('credit_score', models.IntegerField(blank=True, help_text='Credit score (300-850)', null=True)),
                # ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', help_text='Preferred method of contact', max_length=20)),
                # ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='Notification preferences (email, SMS, etc.)')),
                ('section', models.CharField(blank=True, default='A', help_text='User section', max_length=2)),
                ('laptop_status', models.BooleanField(default=True, help_text='Whether user has a laptop', verbose_name='Has laptop')),
                ('is_active', models.BooleanField(default=True, help_text='Whether profile is active', verbose_name='Is active')),
                # ('created_at', models.DateTimeField(auto_now_add=True)),
                # ('updated_at', models.DateTimeField(auto_now=True)),
                ('image2', models.ForeignKey(default=1, help_text='Secondary profile image', on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='main.assets')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'accounts_userprofile',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Job_Support', 'Job_Support'), ('Interview', 'Interview'), ('Training', 'Training'), ('Mentorship', 'Mentorship'), ('Other', 'Other')], max_length=25)),
                ('sub_category', models.CharField(choices=[('Requirements', 'Requirements'), ('Troubleshooting', 'Troubleshooting'), ('Development', 'Development'), ('Testing', 'Testing'), ('Other', 'Other')], default='Other', max_length=25)),
                ('task', models.CharField(choices=[('reporting', 'reporting'), ('database', 'database'), ('Business Analysis', 'Business Analysis'), ('Data Cleaning', 'Data Cleaning'), ('Other', 'Other')], max_length=25)),
                ('plan', models.CharField(default='B', help_text='Required', max_length=255, verbose_name='group')),
                ('employee', models.CharField(default='CODA', help_text='Required', max_length=255, verbose_name='Company/End Client')),
                ('login_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('duration', models.IntegerField(choices=[(1, 'One Hour'), (2, 'Two Hours'), (3, 'Three Hours'), (4, 'Four Hours'), (5, 'Five Hours'), (8, 'Eight Hours'), (10, 'Ten Hours')], default=2)),
                ('time', models.PositiveIntegerField(default=120, error_messages={'name': {' max_length': 'The maximum hours must be between 0 and 199'}}, help_text='Maximum 200')),
                ('author', models.ForeignKey(blank=True, limit_choices_to={'category__in': [1, 3, 4, 5, 6, 7], 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('empname', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'ordering': ['login_date'],
            },
        ),
        # migrations.AddIndex(
        #     model_name='team_members',
        #     index=models.Index(fields=['category'], name='accounts_te_categor_bd07e8_idx'),
        # ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credentialcategory',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='credential',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credential',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='credentialcategory', to='accounts.CredentialCategory'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        # migrations.AddIndex(
        #     model_name='userprofile',
        #     index=models.Index(fields=['performance_tier'], name='accounts_us_perform_a429b1_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='userprofile',
        #     index=models.Index(fields=['is_karen_country_club_member'], name='accounts_us_is_kare_eb47f6_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='userprofile',
        #     index=models.Index(fields=['staff_level'], name='accounts_us_staff_l_7f9e94_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='userprofile',
        #     index=models.Index(fields=['monthly_income'], name='accounts_us_monthly_9cb68e_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='userprofile',
        #     index=models.Index(fields=['created_at'], name='accounts_us_created_70c995_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='userprofile',
        #     index=models.Index(fields=['performance_tier', 'is_karen_country_club_member'], name='accounts_us_perform_63cb38_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='userprofile',
        #     index=models.Index(fields=['staff_level', 'performance_tier'], name='accounts_us_staff_l_e9de69_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='tracker',
        #     index=models.Index(fields=['login_date'], name='accounts_tr_login_d_8e69d2_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='tracker',
        #     index=models.Index(fields=['category', 'sub_category'], name='accounts_tr_categor_926abd_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='tracker',
        #     index=models.Index(fields=['empname'], name='accounts_tr_empname_395c4e_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='tracker',
        #     index=models.Index(fields=['author'], name='accounts_tr_author__e2068e_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='tracker',
        #     index=models.Index(fields=['login_date', 'category'], name='accounts_tr_login_d_f6acdd_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='tracker',
        #     index=models.Index(fields=['empname', 'login_date'], name='accounts_tr_empname_62ac24_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='tracker',
        #     index=models.Index(fields=['author', 'login_date'], name='accounts_tr_author__8fed88_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='tracker',
        #     index=models.Index(fields=['category', 'empname'], name='accounts_tr_categor_9b53d2_idx'),
        # ),
    ]
