# Generated by Django 3.2.6 on 2025-09-25 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image2',
            field=models.ForeignKey(default=1, help_text='Secondary profile image', on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='main.assets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergroups',
            name='users',
            field=models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tracker',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__in': [1, 3, 4, 5, 6, 7], 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='empname',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddIndex(
            model_name='team_members',
            index=models.Index(fields=['category'], name='accounts_te_categor_bd07e8_idx'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credentialcategory',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='credential',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credential',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='credentialcategory', to='accounts.CredentialCategory'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['performance_tier'], name='accounts_us_perform_a429b1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_karen_country_club_member'], name='accounts_us_is_kare_eb47f6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['staff_level'], name='accounts_us_staff_l_7f9e94_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['monthly_income'], name='accounts_us_monthly_9cb68e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='accounts_us_created_70c995_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['performance_tier', 'is_karen_country_club_member'], name='accounts_us_perform_63cb38_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['staff_level', 'performance_tier'], name='accounts_us_staff_l_e9de69_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['login_date'], name='accounts_tr_login_d_8e69d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['category', 'sub_category'], name='accounts_tr_categor_926abd_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['empname'], name='accounts_tr_empname_395c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['author'], name='accounts_tr_author__e2068e_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['login_date', 'category'], name='accounts_tr_login_d_f6acdd_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['empname', 'login_date'], name='accounts_tr_empname_62ac24_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['author', 'login_date'], name='accounts_tr_author__8fed88_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['category', 'empname'], name='accounts_tr_categor_9b53d2_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['date_joined'], name='accounts_cu_date_jo_3581ed_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['is_active'], name='accounts_cu_is_acti_f9316b_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['category', 'sub_category'], name='accounts_cu_categor_dd8de1_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['email'], name='accounts_cu_email_c1c908_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_06448a_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['is_active', 'category'], name='accounts_cu_is_acti_03d144_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['is_active', 'is_staff'], name='accounts_cu_is_acti_d2ed60_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['date_joined', 'is_active'], name='accounts_cu_date_jo_cdda9a_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['email', 'is_active'], name='accounts_cu_email_1b4c47_idx'),
        ),
    ]
