# Generated by Django 3.2.6 on 2025-09-18 20:36

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unified_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dashboardwidget',
            name='unique_user_position',
        ),
        migrations.AlterField(
            model_name='dashboardanalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidget',
            unique_together={('user', 'position')},
        ),
    ]
