# Generated by Django 3.2.6 on 2025-09-25 18:09

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import professional_services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('end_client', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('recruiting_agency', models.CharField(max_length=255)),
                ('job_offer_letter', models.CharField(max_length=255)),
                ('academic_documents', models.CharField(max_length=255)),
                ('hiring_company', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('past_employers', models.CharField(max_length=255)),
                ('reference_contacts', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_backgroundcheck',
            },
        ),
        migrations.CreateModel(
            name='ClientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Interview', 'Interview'), ('BI Training', 'BI Training'), ('Job Support', 'Job Support'), ('Other', 'Other')], default='Other', max_length=25)),
                ('type', models.CharField(choices=[('client', 'client'), ('Staff', 'Staff'), ('Other', 'Other')], default='Other', max_length=25)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(choices=[('Degree', 'Degree'), ('Some College', 'Some College'), ('High School', 'High School'), ('Other', 'Other')], default='Other', max_length=25)),
                ('rating_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('skills', models.TextField(default='word,excel,powerpoints and data tools etc')),
                ('experience', models.TextField(default='Tell us more on your experience(internships,projects,current work etc)')),
                ('non_it_exp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('it_exp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('projectmanagement', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('requirementsAnalysis', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('reporting', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('etl', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('database', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('testing', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('deployment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('frontend', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('backend', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('totalpoints', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'data_clientassessment',
            },
        ),
        migrations.CreateModel(
            name='Correct_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('performance', 'performance'), ('testing', 'testing'), ('Project Story', 'Project Story'), ('methodology', 'methodology'), ('sdlc', 'sdlc')], default='performance', max_length=50)),
                ('categories', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'db_table': 'data_correct_answers',
            },
        ),
        migrations.CreateModel(
            name='FeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Course Overview', 'Course Overview'), ('Initiation & Planning', 'Initiation & Planning'), ('Development', 'Development'), ('Testing', 'Testing'), ('Deployment', 'Deployment'), ('Other', 'Other')], default='Other', max_length=25, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'data_featuredcategory',
            },
        ),
        migrations.CreateModel(
            name='FeaturedSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(default='General')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('featuredcategory', models.ForeignKey(default=professional_services.models.FeaturedCategory.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='professional_services.featuredcategory')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'db_table': 'data_featuredsubcategory',
            },
        ),
        migrations.CreateModel(
            name='JobRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('category', models.CharField(choices=[('Project Management', 'Project Management'), ('Business Analysis', 'Business Analysis'), ('Quality Assurance', 'Quality Assurance'), ('User Experience', 'User Experience'), ('Reporting', 'Reporting'), ('ETL', 'ETL'), ('Database', 'Database'), ('Python', 'Python'), ('Other', 'Other')], default='Other', max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_tech', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'IT Roles',
                'db_table': 'data_jobroles',
            },
        ),
        migrations.CreateModel(
            name='Prep_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('Project Management', 'Project Management'), ('Business Analysis', 'Business Analysis'), ('Quality Assurance', 'Quality Assurance'), ('User Experience', 'User Experience'), ('Reporting', 'Reporting'), ('ETL', 'ETL'), ('Database', 'Database'), ('Python', 'Python'), ('Other', 'Other')], max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('introduction', 'introduction'), ('Project Story', 'project story'), ('performance', 'performance'), ('methodology', 'methodology'), ('sdlc', 'sdlc'), ('testing', 'testing'), ('environment', 'environment'), ('resume', 'resume'), ('Other', 'Other')], max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_answered', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('is_tech', models.BooleanField(blank=True, default=False, null=True)),
                ('questioner', models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', [1, 3, 4, 5, 6, 7]), ('is_staff', True), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questioner', to=settings.AUTH_USER_MODEL, verbose_name='questioner')),
            ],
            options={
                'verbose_name_plural': 'prep_questions',
                'db_table': 'data_prep_questions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='Data Analyst', max_length=500, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_answered', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional_services.prep_questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_useranswerstatus',
            },
        ),
        migrations.CreateModel(
            name='TrainingResponsesTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_overview', models.CharField(blank=True, max_length=254, null=True)),
                ('featuredsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional_services.featuredsubcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_training_responses_tracking',
            },
        ),
        migrations.CreateModel(
            name='Training_Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('response', models.CharField(blank=True, max_length=1000, null=True)),
                ('question', models.CharField(blank=True, max_length=1055, null=True)),
                ('question1', models.TextField(default='Write Your Reponse')),
                ('is_active', models.BooleanField(default=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField()),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('first_displayed_at', models.DateTimeField(blank=True, null=True)),
                ('seen_notifications', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Training Responses',
                'db_table': 'data_training_responses',
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('category', models.CharField(choices=[('Project Management', 'Project Management'), ('Business Analyst', 'Business Analysis'), ('Quality Assurance', 'Quality Assurance'), ('User Interface', 'User Experience'), ('Reporting', 'Reporting'), ('ETL', 'ETL'), ('Database', 'Database'), ('Python', 'Python'), ('Other', 'Other')], default='Other', max_length=100)),
                ('question_type', models.CharField(choices=[('introduction', 'introduction'), ('Project Story', 'project story'), ('performance', 'performance'), ('methodology', 'methodology'), ('sdlc', 'sdlc'), ('testing', 'testing'), ('environment', 'environment'), ('resume', 'resume'), ('Other', 'Other')], default='Other', max_length=100)),
                ('doc', models.FileField(default='None', upload_to='Uploads/doc/')),
                ('videolink', models.CharField(blank=True, max_length=255, null=True)),
                ('doclink', models.CharField(blank=True, max_length=255, null=True)),
                ('desc1', models.TextField(blank=True, max_length=1000, null=True)),
                ('desc2', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'category__in': [1, 3, 4, 5, 6, 7], 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client_Name', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'data_jobrole',
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_offer_letter', models.FileField(upload_to='job_offers/')),
                ('verified', models.BooleanField(default=False)),
                ('background_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='professional_services.backgroundcheck')),
            ],
            options={
                'db_table': 'data_jobdetails',
            },
        ),
        migrations.CreateModel(
            name='Job_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('recruiter', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('offer', models.DecimalField(decimal_places=2, error_messages={'name': {' max_length': 'The earning must be between 0 and 4999.99'}}, max_digits=10)),
                ('status', models.CharField(choices=[('screening call', 'screening call'), ('1st interview', '1st interview'), ('2nd interview', '2nd interview'), ('3rd interview', '3rd interview'), ('Other', 'Other')], default='other', max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_resume', models.FileField(default='None', upload_to='training/docs/')),
                ('resume_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'jobs',
                'db_table': 'data_job_tracker',
            },
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('category', models.CharField(choices=[('Project Management', 'Project Management'), ('Business Analyst', 'Business Analysis'), ('Quality Assurance', 'Quality Assurance'), ('User Interface', 'User Experience'), ('Reporting', 'Reporting'), ('ETL', 'ETL'), ('Database', 'Database'), ('Python', 'Python'), ('Other', 'Other')], default='Other', max_length=100)),
                ('question_type', models.CharField(choices=[('introduction', 'introduction'), ('Project Story', 'project story'), ('performance', 'performance'), ('methodology', 'methodology'), ('sdlc', 'sdlc'), ('testing', 'testing'), ('environment', 'environment'), ('resume', 'resume'), ('Other', 'Other')], default='Other', max_length=100)),
                ('comment', models.TextField()),
                ('doc', models.FileField(blank=True, default='None', upload_to='Uploads/doc/')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamic_fields', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='client_assiged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview_Responses',
                'db_table': 'data_interviews',
            },
        ),
        migrations.CreateModel(
            name='FeaturedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('guiding_question', models.TextField(blank=True, null=True)),
                ('interview_question', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('featuredsubcategory', models.ManyToManyField(blank=True, related_name='subcategories_fetured', to='professional_services.FeaturedSubCategory')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'db_table': 'data_featuredactivity',
            },
        ),
        migrations.CreateModel(
            name='DSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Interview', 'Interview'), ('BI Training', 'BI Training'), ('Job Support', 'Job Support'), ('Other', 'Other')], default='Other', max_length=25)),
                ('type', models.CharField(choices=[('client', 'client'), ('Staff', 'Staff'), ('Other', 'Other')], default='Other', max_length=25)),
                ('subcategory', models.CharField(default='data', max_length=255)),
                ('client_name', models.CharField(default='admin', max_length=255)),
                ('task', models.TextField()),
                ('plan', models.TextField()),
                ('challenge', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('cohort', models.PositiveIntegerField(default=1)),
                ('trained_by', models.ForeignKey(limit_choices_to=models.Q(('is_staff', True), ('category__in', [1, 3, 4, 5, 6, 7]), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DSU',
                'db_table': 'data_dsu',
            },
        ),
        migrations.CreateModel(
            name='ActivityLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(default='General', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.FileField(default='None', upload_to='training/docs/')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('Activity', models.ManyToManyField(blank=True, related_name='activity_featured', to='professional_services.FeaturedActivity')),
                ('Featuredsubcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorie_fetured', to='professional_services.featuredsubcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'links',
                'db_table': 'data_activitylinks',
            },
        ),
    ]
