# Generated by Django 3.2.6 on 2026-02-04 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this deal is currently active'),
        ),
        migrations.CreateModel(
            name='ValuationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('IN_KIND', 'In-Kind Asset'), ('TIME', 'Time Logged'), ('WORK', 'Work Deliverable')], help_text='Contribution tier this rate applies to', max_length=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, help_text='USD value per internal unit (e.g., 50.00 USD/hour)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_label', models.CharField(help_text="Unit label (e.g., 'hour', 'point', 'unit')", max_length=50)),
                ('description', models.CharField(blank=True, help_text="Description of this rate (e.g., 'Senior Developer hourly rate')", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('effective_date', models.DateField(auto_now_add=True, help_text='Date this rate became effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(help_text='Associated deal', on_delete=django.db.models.deletion.CASCADE, related_name='valuation_rates', to='shareholders.deal')),
            ],
            options={
                'verbose_name': 'Valuation Rate',
                'verbose_name_plural': 'Valuation Rates',
                'db_table': 'shareholders_valuation_rate',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='LedgerDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', help_text='Current dispute status', max_length=15)),
                ('reason', models.TextField(help_text='Reason for the dispute')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the dispute was resolved', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the dispute was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(help_text='The ledger entry being disputed', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='shareholders.ledgerentry')),
                ('raised_by', models.ForeignKey(help_text='User who raised this dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved this dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Dispute',
                'verbose_name_plural': 'Ledger Disputes',
                'db_table': 'shareholders_ledger_dispute',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Entry Created'), ('UPDATED', 'Entry Updated'), ('STATUS_CHANGED', 'Status Changed'), ('APPROVED', 'Entry Approved'), ('REJECTED', 'Entry Rejected'), ('DISPUTE_RAISED', 'Dispute Raised'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('EVIDENCE_ADDED', 'Evidence Added'), ('EVIDENCE_REMOVED', 'Evidence Removed')], help_text='Action performed', max_length=20)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (for updates)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (for updates)', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional context in JSON format', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.ForeignKey(help_text='The ledger entry this log pertains to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='shareholders.ledgerentry')),
                ('performed_by', models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Audit Log',
                'verbose_name_plural': 'Ledger Audit Logs',
                'db_table': 'shareholders_ledger_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='Approval action taken', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Approval notes or comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(help_text='User who approved this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_approvals', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(help_text='The ledger entry being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='shareholders.ledgerentry')),
            ],
            options={
                'verbose_name': 'Ledger Approval',
                'verbose_name_plural': 'Ledger Approvals',
                'db_table': 'shareholders_ledger_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='valuationrate',
            index=models.Index(fields=['deal', 'tier', 'is_active'], name='shareholder_deal_id_6d1d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerauditlog',
            index=models.Index(fields=['ledger_entry', 'action'], name='shareholder_ledger__11bd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerauditlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='shareholder_perform_74378e_idx'),
        ),
    ]
