# Generated by Django 3.2.6 on 2026-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholders', '0002_phase2_ledger_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='identity_document',
            field=models.FileField(blank=True, help_text='Uploaded identity document (ID, passport, or business certificate)', null=True, upload_to='shareholders/identity_documents/%Y/%m/'),
        ),
    ]
