# Generated by Django 3.2.6 on 2025-12-28 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_fees', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('down_payment', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)])),
                ('student_bonus', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_balance', models.IntegerField(blank=True, null=True)),
                ('plan', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('subplan', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(max_length=100)),
                ('contract_submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_signature', models.CharField(max_length=1000)),
                ('company_rep', models.CharField(max_length=1000)),
                ('client_date', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_date', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-contract_submitted_date'],
            },
        ),
    ]
