# Generated by Django 3.2.6 on 2026-02-01 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_fees', models.IntegerField()),
                ('down_payment', models.IntegerField()),
                ('student_bonus', models.IntegerField()),
                ('fee_balance', models.IntegerField()),
                ('plan', models.IntegerField()),
                ('subplan', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('contract_submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_signature', models.CharField(max_length=1000)),
                ('company_rep', models.CharField(max_length=1000)),
                ('client_date', models.CharField(max_length=100)),
                ('rep_date', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_history',
                'ordering': ['-contract_submitted_date'],
            },
        ),
    ]
