# Generated by Django 3.2.6 on 2024-12-03 10:19

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def delete_member_registration_if_exists(apps, schema_editor):
    """Safely delete MemberRegistration table if it exists"""
    db_table = 'accounts_memberregistration'
    with connection.cursor() as cursor:
        # Check if table exists before trying to delete
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [db_table])
        exists = cursor.fetchone()[0]
        if exists:
            cursor.execute(f'DROP TABLE IF EXISTS {db_table} CASCADE;')


def reverse_delete_member_registration(apps, schema_editor):
    """Recreate MemberRegistration table if needed (for rollback)"""
    # This is a no-op since we're deleting the model anyway
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid')], default='NOT_PAID', max_length=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    delete_member_registration_if_exists,
                    reverse_delete_member_registration,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='MemberRegistration',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Is Member'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='verification_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Ordinary Member (Free)'), (2, 'Active Member'), (3, 'Executive Member'), (4, 'FBO & Ordinary (Free)'), (5, 'Active Organization'), (6, 'Royal Organization')], default=999),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
