# Generated by Django 3.2.6 on 2025-09-21 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credit_score',
            field=models.IntegerField(blank=True, help_text='Credit score (300-850)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_start_date',
            field=models.DateField(blank=True, help_text='Employment start date for loan eligibility', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_karen_country_club_member',
            field=models.BooleanField(default=False, help_text='Whether user is a Karen Country Club member'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kcc_membership_date',
            field=models.DateField(blank=True, help_text='Date when user became a KCC member', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kcc_membership_expiry',
            field=models.DateField(blank=True, help_text='Karen Country Club membership expiry date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kcc_membership_number',
            field=models.CharField(blank=True, help_text='Karen Country Club membership number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income for loan eligibility', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Notification preferences (email, SMS, etc.)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='performance_tier',
            field=models.CharField(choices=[('new', 'New'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='new', help_text='Performance tier (affects loan terms for all users)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', help_text='Preferred method of contact', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills and competencies'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('senior', 'Senior'), ('manager', 'Manager'), ('executive', 'Executive')], help_text='Staff level (affects loan terms)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['date_joined'], name='accounts_cu_date_jo_3581ed_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['is_active'], name='accounts_cu_is_acti_f9316b_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['category', 'sub_category'], name='accounts_cu_categor_dd8de1_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['email'], name='accounts_cu_email_c1c908_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_06448a_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['is_active', 'category'], name='accounts_cu_is_acti_03d144_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['is_active', 'is_staff'], name='accounts_cu_is_acti_d2ed60_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['date_joined', 'is_active'], name='accounts_cu_date_jo_cdda9a_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['email', 'is_active'], name='accounts_cu_email_1b4c47_idx'),
        ),
        migrations.AddIndex(
            model_name='team_members',
            index=models.Index(fields=['category'], name='accounts_te_categor_bd07e8_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['login_date'], name='accounts_tr_login_d_8e69d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['category', 'sub_category'], name='accounts_tr_categor_926abd_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['empname'], name='accounts_tr_empname_395c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['author'], name='accounts_tr_author__e2068e_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['login_date', 'category'], name='accounts_tr_login_d_f6acdd_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['empname', 'login_date'], name='accounts_tr_empname_62ac24_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['author', 'login_date'], name='accounts_tr_author__8fed88_idx'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['category', 'empname'], name='accounts_tr_categor_9b53d2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['performance_tier'], name='accounts_us_perform_a429b1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_karen_country_club_member'], name='accounts_us_is_kare_eb47f6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['staff_level'], name='accounts_us_staff_l_7f9e94_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['monthly_income'], name='accounts_us_monthly_9cb68e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='accounts_us_created_70c995_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['performance_tier', 'is_karen_country_club_member'], name='accounts_us_perform_63cb38_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['staff_level', 'performance_tier'], name='accounts_us_staff_l_e9de69_idx'),
        ),
    ]
