# Generated by Django 3.2.6 on 2024-12-03 16:19

from django.db import migrations, models, connection


def add_currency_field_if_membership_exists(apps, schema_editor):
    """Add currency field to Membership only if the table exists"""
    membership_table = 'accounts_membership'
    with connection.cursor() as cursor:
        # Check if Membership table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [membership_table])
        exists = cursor.fetchone()[0]
        
        if exists:
            # Check if currency column already exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = 'currency';
            """, [membership_table])
            if not cursor.fetchone():
                cursor.execute(f'ALTER TABLE {membership_table} ADD COLUMN currency VARCHAR(10) DEFAULT \'KES\' NOT NULL;')


def reverse_add_currency_field(apps, schema_editor):
    """Remove currency field if needed"""
    membership_table = 'accounts_membership'
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = 'currency';
        """, [membership_table])
        if cursor.fetchone():
            cursor.execute(f'ALTER TABLE {membership_table} DROP COLUMN IF EXISTS currency CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241203_1019'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_currency_field_if_membership_exists,
                    reverse_add_currency_field,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='membership',
                    name='currency',
                    field=models.CharField(default='KES', max_length=10),
                ),
            ],
        ),
    ]
