# Generated by Django 5.2.7 on 2025-11-04 03:12

from django.db import migrations, models  # type: ignore[import]


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_role_alter_userprofile_category_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full address (optional)', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, help_text='Alternative email address', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or Organization name', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile or page URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry or sector', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Your current job title or position', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profile_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Your skills or areas of expertise (comma separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter username (without @)', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Your website or company website'),
        ),
    ]
