# Generated by Django 3.2.6 on 2025-09-29 03:29

from django.db import migrations, models, connection


def add_customeruser_fields_if_exists(apps, schema_editor):
    """Add fields to CustomerUser only if the table exists"""
    db_table = 'accounts_customeruser'
    with connection.cursor() as cursor:
        # Check if CustomerUser table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [db_table])
        exists = cursor.fetchone()[0]
        
        if exists:
            # Add accepted_terms field if it doesn't exist
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = 'accepted_terms';
            """, [db_table])
            if not cursor.fetchone():
                cursor.execute(f'ALTER TABLE {db_table} ADD COLUMN accepted_terms BOOLEAN DEFAULT FALSE NOT NULL;')
            
            # Add city field if it doesn't exist
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = 'city';
            """, [db_table])
            if not cursor.fetchone():
                cursor.execute(f'ALTER TABLE {db_table} ADD COLUMN city VARCHAR(100);')
            
            # Add country field if it doesn't exist
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = 'country';
            """, [db_table])
            if not cursor.fetchone():
                cursor.execute(f'ALTER TABLE {db_table} ADD COLUMN country VARCHAR(100);')
            
            # Add gender field if it doesn't exist
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = 'gender';
            """, [db_table])
            if not cursor.fetchone():
                cursor.execute(f'ALTER TABLE {db_table} ADD COLUMN gender VARCHAR(10);')
            
            # Add phone field if it doesn't exist
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = 'phone';
            """, [db_table])
            if not cursor.fetchone():
                cursor.execute(f'ALTER TABLE {db_table} ADD COLUMN phone VARCHAR(20);')
            
            # Add plan field if it doesn't exist
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = %s AND column_name = 'plan';
            """, [db_table])
            if not cursor.fetchone():
                cursor.execute(f'ALTER TABLE {db_table} ADD COLUMN plan VARCHAR(20);')


def reverse_add_customeruser_fields(apps, schema_editor):
    """Remove fields if needed (for rollback)"""
    # This is a no-op since we can't easily reverse these changes
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_currency'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_customeruser_fields_if_exists,
                    reverse_add_customeruser_fields,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='customeruser',
                    name='accepted_terms',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='customeruser',
                    name='city',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='customeruser',
                    name='country',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='customeruser',
                    name='gender',
                    field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
                ),
                migrations.AddField(
                    model_name='customeruser',
                    name='phone',
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='customeruser',
                    name='plan',
                    field=models.CharField(blank=True, choices=[('ordinary', 'Ordinary Member Free'), ('active', 'Active Member 1000'), ('executive', 'Executive Members 10000'), ('active_org', 'Active ORGANIZATION 10000'), ('royal_org', 'ROYAL ORGANIZATION 20000')], max_length=20, null=True),
                ),
            ],
        ),
    ]
