# Generated by Django 3.2.6 on 2025-10-02 13:54

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def create_account_models_if_customeruser_exists(apps, schema_editor):
    """Create Account and AccountTeamMember only if CustomerUser exists"""
    customeruser_table = 'accounts_customeruser'
    account_table = 'accounts_account'
    accountteammember_table = 'accounts_accountteammember'
    
    with connection.cursor() as cursor:
        # Check if CustomerUser table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [customeruser_table])
        customeruser_exists = cursor.fetchone()[0]
        
        if not customeruser_exists:
            # Skip creating these models if CustomerUser doesn't exist
            # They'll be created when CustomerUser is created
            return
        
        # Create Account table if it doesn't exist
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [account_table])
        if not cursor.fetchone()[0]:
            cursor.execute(f"""
                CREATE TABLE {account_table} (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP NOT NULL
                );
            """)
        
        # Create AccountTeamMember table if it doesn't exist
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [accountteammember_table])
        if not cursor.fetchone()[0]:
            cursor.execute(f"""
                CREATE TABLE {accountteammember_table} (
                    id SERIAL PRIMARY KEY,
                    role VARCHAR(10) NOT NULL,
                    status BOOLEAN NOT NULL DEFAULT TRUE,
                    joined_date TIMESTAMP NOT NULL,
                    notes TEXT,
                    account_id INTEGER NOT NULL REFERENCES {account_table}(id) ON DELETE CASCADE,
                    added_by_id INTEGER REFERENCES {customeruser_table}(id) ON DELETE SET NULL,
                    user_id INTEGER NOT NULL REFERENCES {customeruser_table}(id) ON DELETE CASCADE,
                    UNIQUE(account_id, user_id)
                );
            """)


def reverse_create_account_models(apps, schema_editor):
    """Remove Account models if needed"""
    account_table = 'accounts_account'
    accountteammember_table = 'accounts_accountteammember'
    with connection.cursor() as cursor:
        cursor.execute(f'DROP TABLE IF EXISTS {accountteammember_table} CASCADE;')
        cursor.execute(f'DROP TABLE IF EXISTS {account_table} CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_currency'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_account_models_if_customeruser_exists,
                    reverse_create_account_models,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Account',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                ),
                migrations.CreateModel(
                    name='AccountTeamMember',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], max_length=10)),
                        ('status', models.BooleanField(default=True)),
                        ('joined_date', models.DateTimeField(auto_now_add=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.account')),
                        ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_team_members', to=settings.AUTH_USER_MODEL)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Account Team Member',
                        'verbose_name_plural': 'Account Team Members',
                        'unique_together': {('account', 'user')},
                    },
                ),
            ],
        ),
    ]
