# Generated by Django 3.2.6 on 2025-09-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='plan',
            field=models.CharField(blank=True, choices=[('ordinary', 'Ordinary Member Free'), ('active', 'Active Member 1000'), ('executive', 'Executive Members 10000'), ('active_org', 'Active ORGANIZATION 10000'), ('royal_org', 'ROYAL ORGANIZATION 20000')], max_length=20, null=True),
        ),
    ]
