# Generated by Django 3.2.6 on 2025-09-29 03:56

from django.db import migrations, connection


def remove_customeruser_fields_if_exists(apps, schema_editor):
    """Remove fields from CustomerUser only if the table exists"""
    db_table = 'accounts_customeruser'
    with connection.cursor() as cursor:
        # Check if CustomerUser table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [db_table])
        exists = cursor.fetchone()[0]
        
        if exists:
            # Remove fields if they exist
            for field in ['city', 'country', 'gender', 'phone', 'plan']:
                cursor.execute("""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name = %s AND column_name = %s;
                """, [db_table, field])
                if cursor.fetchone():
                    cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN IF EXISTS {field} CASCADE;')


def reverse_remove_customeruser_fields(apps, schema_editor):
    """Reverse the field removals if needed"""
    # This is a no-op since we can't easily reverse these changes
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250929_0529'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_customeruser_fields_if_exists,
                    reverse_remove_customeruser_fields,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='customeruser',
                    name='city',
                ),
                migrations.RemoveField(
                    model_name='customeruser',
                    name='country',
                ),
                migrations.RemoveField(
                    model_name='customeruser',
                    name='gender',
                ),
                migrations.RemoveField(
                    model_name='customeruser',
                    name='phone',
                ),
                migrations.RemoveField(
                    model_name='customeruser',
                    name='plan',
                ),
            ],
        ),
    ]
