# Generated by Django 3.2.6 on 2025-09-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250929_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='plan',
        ),
    ]
