# Generated by Django 3.2.6 on 2025-10-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_accountteammember'),
        ('accounts', '0005_auto_20250929_0556'),
    ]

    operations = [
    ]
