# Generated by Django 5.2.15 on 2026-08-02 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('skills_expertise', models.TextField()),
                ('number_of_connects', models.IntegerField()),
                ('min_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
                ('project_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('internal', models.AutoField(primary_key=True, serialize=False)),
                ('first_interview', models.CharField(max_length=255)),
                ('second_interview', models.CharField(max_length=255)),
                ('third_interview', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('interview_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('section', models.CharField(blank=True, max_length=2, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('upload_a', models.FileField(blank=True, null=True, upload_to='profile_files/')),
                ('upload_b', models.FileField(blank=True, null=True, upload_to='profile_files/')),
                ('upload_c', models.FileField(blank=True, null=True, upload_to='profile_files/')),
                ('is_active', models.BooleanField(default=True)),
                ('laptop_status', models.BooleanField(default=False)),
                ('national_id_no', models.CharField(blank=True, max_length=100, null=True)),
                ('id_file', models.ImageField(blank=True, null=True, upload_to='id_files/')),
                ('emergency_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_address', models.CharField(blank=True, max_length=254, null=True)),
                ('emergency_citizenship', models.CharField(blank=True, max_length=254, null=True)),
                ('emergency_national_id_no', models.CharField(blank=True, max_length=254, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=254, null=True)),
                ('emergency_email', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
