# Generated by Django 5.2.12 on 2026-03-20 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('canada', 'Canada'), ('usa', 'USA'), ('uk', 'UK')], max_length=50)),
                ('purpose', models.CharField(choices=[('study', 'Study'), ('work', 'Work'), ('tourism', 'Tourism')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejected_before', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('create_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_issue', models.DateField(blank=True, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('passport_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=50)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('employer_address', models.TextField()),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='documents/passports/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='documents/photos/')),
                ('travel_doc', models.FileField(blank=True, null=True, upload_to='documents/travel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('service_type', models.CharField(choices=[('visa', 'Visa Application'), ('work', 'Work Permit'), ('residency', 'Residency'), ('legal', 'Legal Advice')], max_length=20)),
                ('consultation_mode', models.CharField(choices=[('online', 'Online'), ('physical', 'In-person')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consultations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('consultation_type', models.CharField(choices=[('immigration', 'Immigration Visa'), ('asylum', 'Asylum'), ('family', 'Family Immigration'), ('work', 'Work Permit'), ('student', 'Student Visa'), ('legal', 'General Legal Advice')], max_length=100)),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='consultation_documents/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
