# Generated by Django 5.2.12 on 2026-03-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_issue', models.DateField(blank=True, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('passport_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=50)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('employer_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
