# Generated by Django 5.2.12 on 2026-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('years_in_country', models.IntegerField()),
                ('has_criminal_record', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('min_age', models.IntegerField(default=18)),
                ('min_years_residence', models.IntegerField(default=5)),
                ('requires_clean_record', models.BooleanField(default=True)),
            ],
        ),
    ]
