# Generated by Django 5.2.12 on 2026-03-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_applicant_eligibilityrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_years', models.IntegerField(default=0)),
                ('requires_investment', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
