# Generated by Django 5.2.12 on 2026-03-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_visaapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/passports/'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/photos/'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='travel_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/travel/'),
        ),
    ]
