# Generated by Django 5.2.12 on 2026-03-31 18:30

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_attorneyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preassessment',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
