# Generated by Django 5.2.12 on 2026-04-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_preassessment_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preassessment',
            name='country',
            field=models.CharField(choices=[('canada', 'Canada'), ('usa', 'USA'), ('uk', 'UK')], max_length=50),
        ),
    ]
