# Generated by Django 3.2.6 on 2025-10-15 - Initial migration for investing app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        # This migration is intentionally empty - tables already exist
        # We're just creating the migration history
    ]

