# Generated by Django 3.2.6 on 2025-10-27 17:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0001_add_managed_trading_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorRiskProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('questionnaire_data', models.JSONField(help_text='All 10 question responses')),
                ('risk_score', models.IntegerField(help_text='Total score from questionnaire (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_category', models.CharField(choices=[('conservative', 'Conservative (0-30)'), ('moderate', 'Moderate (31-60)'), ('aggressive', 'Aggressive (61-100)')], help_text='Conservative, Moderate, or Aggressive', max_length=20)),
                ('assessed_date', models.DateTimeField(auto_now_add=True, help_text='When assessment was completed')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time profile was updated')),
                ('is_current', models.BooleanField(default=True, help_text='Is this the current valid assessment?')),
                ('expires_date', models.DateField(blank=True, help_text='Date when reassessment is required (typically 1 year)', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Risk Profile',
                'verbose_name_plural': 'Investor Risk Profiles',
                'ordering': ['-assessed_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagedTradingApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('initial_capital', models.DecimalField(decimal_places=2, help_text='Initial capital to invest (minimum $5,000)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('5000.00'))])),
                ('fee_tier', models.CharField(choices=[('consultative', 'Consultative Coaching - $420/month + 10% bonus'), ('starter', 'Starter - 0% mgmt + 25% performance'), ('professional', 'Professional - 1.5% mgmt + 20% perf'), ('premium', 'Premium - 1% mgmt + 15% perf + $500/mo min'), ('co_invest', 'Co-Investment - 50/50 split'), ('custom', 'Custom Fee Structure')], help_text='Selected fee tier', max_length=20)),
                ('funding_method', models.CharField(choices=[('wire', 'Wire Transfer'), ('ach', 'ACH Transfer'), ('check', 'Check'), ('crypto', 'Cryptocurrency')], default='wire', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Client')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Internal notes about approval decision')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to client)')),
                ('contracts_generated', models.BooleanField(default=False, help_text='Have contracts been generated?')),
                ('all_contracts_signed', models.BooleanField(default=False, help_text='Have all required contracts been signed?')),
                ('managed_account', models.OneToOneField(blank=True, help_text='Created managed trading account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='investing.managedtradingaccount')),
                ('preferred_manager', models.ForeignKey(blank=True, help_text='Preferred account manager (optional)', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('risk_profile', models.ForeignKey(help_text='Must complete risk assessment first', on_delete=django.db.models.deletion.PROTECT, to='investing.investorriskprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Managed Trading Application',
                'verbose_name_plural': 'Managed Trading Applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagedTradingContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('contract_type', models.CharField(choices=[('ima', 'Investment Management Agreement'), ('risk_disclosure', 'Options Trading Risk Disclosure'), ('fee_agreement', 'Fee Schedule Agreement'), ('terms', 'Terms of Service')], max_length=20)),
                ('title', models.CharField(help_text='Contract title', max_length=200)),
                ('contract_text', models.TextField(help_text='Full contract text (can be HTML)')),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('signature_ip', models.GenericIPAddressField(blank=True, help_text='IP address where contract was signed', null=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_url', models.URLField(blank=True, help_text='URL to signed PDF', null=True)),
                ('application', models.ForeignKey(blank=True, help_text='Application this contract belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='investing.managedtradingapplication')),
                ('managed_account', models.ForeignKey(blank=True, help_text='Account this contract belongs to (if approved)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='investing.managedtradingaccount')),
            ],
            options={
                'verbose_name': 'Managed Trading Contract',
                'verbose_name_plural': 'Managed Trading Contracts',
                'ordering': ['contract_type'],
                'unique_together': {('application', 'contract_type')},
            },
        ),
        migrations.AddIndex(
            model_name='managedtradingapplication',
            index=models.Index(fields=['status', '-applied_date'], name='investing_m_status_6aeeae_idx'),
        ),
    ]
