# Generated by Django 3.2.6 on 2026-02-09 11:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="Deal name (e.g., 'Project Phoenix Pilot')", max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier (auto-generated from name)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional deal description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this deal is currently active')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'shareholders_deal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('tx_id', models.CharField(editable=False, help_text='Unique transaction ID (auto-generated, e.g., TX-9012)', max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('CASH', 'Cash Contribution'), ('IN_KIND', 'In-Kind Asset'), ('TIME', 'Time Logged'), ('WORK', 'Work Deliverable')], help_text='Contribution tier type', max_length=10)),
                ('asset_class', models.CharField(help_text="Description of asset class (e.g., 'Capital Injection', 'Dev Work', 'Office Lease')", max_length=255)),
                ('internal_units_value', models.DecimalField(decimal_places=2, help_text='Numeric value of internal units (e.g., 15000 for cash, 120 for hours)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('internal_units_label', models.CharField(blank=True, help_text="Label for units (e.g., 'USD', 'hrs', 'pts', 'units', 'months')", max_length=50, null=True)),
                ('value_usd', models.DecimalField(decimal_places=2, help_text='Contribution value in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate used for conversion (e.g., 127 KES/USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_DISPUTE', 'In Dispute')], default='SUBMITTED', help_text='Entry status (Phase 1: UI state only; approvals in Phase 2)', max_length=15)),
                ('date', models.DateField(help_text='Date of contribution')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context', null=True)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'shareholders_ledger_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValuationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('IN_KIND', 'In-Kind Asset'), ('TIME', 'Time Logged'), ('WORK', 'Work Deliverable')], help_text='Contribution tier this rate applies to', max_length=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, help_text='USD value per internal unit (e.g., 50.00 USD/hour)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_label', models.CharField(help_text="Unit label (e.g., 'hour', 'point', 'unit')", max_length=50)),
                ('description', models.CharField(blank=True, help_text="Description of this rate (e.g., 'Senior Developer hourly rate')", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('effective_date', models.DateField(auto_now_add=True, help_text='Date this rate became effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(help_text='Associated deal', on_delete=django.db.models.deletion.CASCADE, related_name='valuation_rates', to='investing.deal')),
            ],
            options={
                'verbose_name': 'Valuation Rate',
                'verbose_name_plural': 'Valuation Rates',
                'db_table': 'shareholders_valuation_rate',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('member_type', models.CharField(choices=[('PERSON', 'Individual Person'), ('ENTITY', 'Entity / Joint Venture')], default='PERSON', help_text='Member type: individual or entity', max_length=10)),
                ('legal_name', models.CharField(help_text='Legal name as per ID/certificate', max_length=255)),
                ('role_title', models.CharField(blank=True, help_text='Role in the deal (e.g., Founder, Investor, Lead Developer)', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Primary email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=50, null=True)),
                ('verified', models.BooleanField(default=False, help_text='Identity verification status (KYC/KYB complete)')),
                ('bio', models.TextField(blank=True, help_text='Optional biography or description', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Soft deletion flag; archived members excluded from active views')),
                ('joined_date', models.DateField(auto_now_add=True, help_text='Date member was registered')),
                ('identity_document', models.FileField(blank=True, help_text='Uploaded identity document (ID, passport, or business certificate)', null=True, upload_to='shareholders/identity_documents/%Y/%m/')),
                ('deal', models.ForeignKey(help_text='Associated deal', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='investing.deal')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'shareholders_member',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded proof document (PDF, JPG, PNG)', upload_to='shareholders/evidence/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('description', models.CharField(blank=True, help_text='Optional description of the document', max_length=255, null=True)),
                ('ledger_entry', models.ForeignKey(help_text='Associated ledger entry', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='investing.ledgerentry')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ledger_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Evidence',
                'verbose_name_plural': 'Ledger Evidence',
                'db_table': 'shareholders_ledger_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='contributor',
            field=models.ForeignKey(help_text='Member making the contribution', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='investing.member'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='deal',
            field=models.ForeignKey(help_text='Associated deal', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='investing.deal'),
        ),
        migrations.CreateModel(
            name='LedgerDispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', help_text='Current dispute status', max_length=15)),
                ('reason', models.TextField(help_text='Reason for the dispute')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the dispute was resolved', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the dispute was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(help_text='The ledger entry being disputed', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='investing.ledgerentry')),
                ('raised_by', models.ForeignKey(help_text='User who raised this dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved this dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Dispute',
                'verbose_name_plural': 'Ledger Disputes',
                'db_table': 'shareholders_ledger_dispute',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Entry Created'), ('UPDATED', 'Entry Updated'), ('STATUS_CHANGED', 'Status Changed'), ('APPROVED', 'Entry Approved'), ('REJECTED', 'Entry Rejected'), ('DISPUTE_RAISED', 'Dispute Raised'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('EVIDENCE_ADDED', 'Evidence Added'), ('EVIDENCE_REMOVED', 'Evidence Removed')], help_text='Action performed', max_length=20)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (for updates)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (for updates)', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional context in JSON format', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.ForeignKey(help_text='The ledger entry this log pertains to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='investing.ledgerentry')),
                ('performed_by', models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Audit Log',
                'verbose_name_plural': 'Ledger Audit Logs',
                'db_table': 'shareholders_ledger_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='Approval action taken', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Approval notes or comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(help_text='User who approved this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_approvals', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(help_text='The ledger entry being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='investing.ledgerentry')),
            ],
            options={
                'verbose_name': 'Ledger Approval',
                'verbose_name_plural': 'Ledger Approvals',
                'db_table': 'shareholders_ledger_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_weight', models.DecimalField(decimal_places=2, default=55.0, help_text='Cash tier weight percentage (default 55%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('in_kind_weight', models.DecimalField(decimal_places=2, default=20.0, help_text='In-Kind tier weight percentage (default 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_weight', models.DecimalField(decimal_places=2, default=10.0, help_text='Time tier weight percentage (default 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('work_weight', models.DecimalField(decimal_places=2, default=15.0, help_text='Work tier weight percentage (default 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Only one active weight set per deal')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='Date these weights became effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(help_text='Associated deal', on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='investing.deal')),
            ],
            options={
                'verbose_name': 'Deal Weights',
                'verbose_name_plural': 'Deal Weights',
                'db_table': 'shareholders_deal_weights',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='DealConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', help_text='Base currency code (ISO 4217)', max_length=3)),
                ('fx_mode', models.CharField(choices=[('PEGGED', 'Pegged Rate'), ('MARKET', 'Market Rate')], default='PEGGED', help_text='FX rate mode: pegged or market', max_length=10)),
                ('fx_peg_rate', models.DecimalField(decimal_places=4, default=127.0, help_text='Pegged FX rate (e.g., 127 KES/USD); used when fx_mode=PEGGED', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dispute_window_days', models.IntegerField(default=7, help_text='Days allowed for disputes (Phase 5 placeholder)', validators=[django.core.validators.MinValueValidator(0)])),
                ('next_snapshot_date', models.DateField(blank=True, help_text='Next scheduled snapshot date (Phase 6 placeholder for dashboard display)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(help_text='Associated deal', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='investing.deal')),
            ],
            options={
                'verbose_name': 'Deal Configuration',
                'verbose_name_plural': 'Deal Configurations',
                'db_table': 'shareholders_deal_config',
            },
        ),
        migrations.AddIndex(
            model_name='valuationrate',
            index=models.Index(fields=['deal', 'tier', 'is_active'], name='shareholder_deal_id_6d1d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['deal', 'is_archived'], name='shareholder_deal_id_e80bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='shareholder_email_a320a1_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['deal', 'date'], name='shareholder_deal_id_a17957_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['deal', 'tier'], name='shareholder_deal_id_d980f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['deal', 'status'], name='shareholder_deal_id_079f52_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['contributor', 'date'], name='shareholder_contrib_bd333b_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tx_id'], name='shareholder_tx_id_0988c4_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerauditlog',
            index=models.Index(fields=['ledger_entry', 'action'], name='shareholder_ledger__11bd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerauditlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='shareholder_perform_74378e_idx'),
        ),
        migrations.AddIndex(
            model_name='dealweights',
            index=models.Index(fields=['deal', 'is_active'], name='shareholder_deal_id_e2d2bf_idx'),
        ),
    ]
