# Generated by Django 3.2.6 on 2025-10-28 04:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_auto_20251027_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsposition',
            name='approval_method',
            field=models.CharField(blank=True, choices=[('batch', 'Batch Approval'), ('session', 'Session Pre-Approved'), ('manual', 'Manual Staff Approval')], help_text='How this position was approved', max_length=20),
        ),
        migrations.AddField(
            model_name='optionsposition',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes about approval (e.g., session number)'),
        ),
        migrations.AddField(
            model_name='optionsposition',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When position was approved (batch or session)', null=True),
        ),
        migrations.AddField(
            model_name='optionsposition',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
        migrations.AddField(
            model_name='optionsposition',
            name='requires_client_approval',
            field=models.BooleanField(default=True, help_text='Does this position require client approval via batch?'),
        ),
        migrations.CreateModel(
            name='PositionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('batch_number', models.CharField(help_text='Format: BATCH-YYYY-Wxx (e.g., BATCH-2025-W47)', max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approval_deadline', models.DateTimeField(help_text='Client must approve before this time (24 hours from creation)')),
                ('status', models.CharField(choices=[('pending', 'Pending Client Approval'), ('approved', 'Approved'), ('rejected', 'Rejected by Client'), ('expired', 'Expired (24hr timeout)'), ('partial', 'Partially Approved')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approval_signature', models.TextField(blank=True, help_text='Base64 encoded signature for batch approval')),
                ('approval_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_positions', models.IntegerField(default=0, help_text='Number of positions in batch')),
                ('total_capital_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total capital required for all positions', max_digits=12)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Was 12-hour reminder sent?')),
                ('timeout_notification_sent', models.BooleanField(default=False, help_text='Was timeout notification sent?')),
                ('managed_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_batches', to='investing.managedtradingaccount')),
            ],
            options={
                'verbose_name': 'Position Batch',
                'verbose_name_plural': 'Position Batches',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='optionsposition',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this position belongs to (if requires approval)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='investing.positionbatch'),
        ),
        migrations.AddIndex(
            model_name='positionbatch',
            index=models.Index(fields=['managed_account', '-created_date'], name='investing_p_managed_2c7d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='positionbatch',
            index=models.Index(fields=['status', 'approval_deadline'], name='investing_p_status_111b74_idx'),
        ),
    ]
