# Generated by Django 3.2.6 on 2026-02-10 22:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0002_shareholders_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquitySnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('version_id', models.CharField(help_text="Version identifier (e.g., 'v1.2-q3', 'v1.0-genesis')", max_length=100, unique=True)),
                ('period_start', models.DateField(help_text='Start date of the snapshot period')),
                ('period_end', models.DateField(help_text='End date of the snapshot period')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now, help_text='Date when snapshot was taken')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked'), ('FINALIZED', 'Finalized')], default='DRAFT', help_text='Snapshot status', max_length=15)),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this snapshot is locked and immutable')),
                ('locked_at', models.DateTimeField(blank=True, help_text='When the snapshot was locked', null=True)),
                ('dispute_window_days', models.IntegerField(default=7, help_text='Days allowed for disputes before auto-lock', validators=[django.core.validators.MinValueValidator(0)])),
                ('auto_lock_date', models.DateField(blank=True, help_text='Date when snapshot will auto-lock (snapshot_date + dispute_window_days)', null=True)),
                ('total_cash_usd', models.DecimalField(decimal_places=2, default=0, help_text='Total cash contributions in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_inkind_usd', models.DecimalField(decimal_places=2, default=0, help_text='Total in-kind contributions in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_time_usd', models.DecimalField(decimal_places=2, default=0, help_text='Total time contributions in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_work_usd', models.DecimalField(decimal_places=2, default=0, help_text='Total work contributions in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_valuation_usd', models.DecimalField(decimal_places=2, default=0, help_text='Total weighted valuation in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('members_count', models.IntegerField(default=0, help_text='Number of members in this snapshot', validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum of snapshot data for integrity verification', max_length=64)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this snapshot', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_snapshots', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(help_text='Associated deal', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='investing.deal')),
                ('locked_by', models.ForeignKey(blank=True, help_text='User who locked this snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equity Snapshot',
                'verbose_name_plural': 'Equity Snapshots',
                'db_table': 'shareholders_equity_snapshot',
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Snapshot Created'), ('LOCKED', 'Snapshot Locked'), ('UNLOCKED', 'Snapshot Unlocked'), ('EXPORTED', 'Snapshot Exported'), ('VIEWED', 'Snapshot Viewed'), ('DELETED', 'Snapshot Deleted')], help_text='Action performed', max_length=20)),
                ('details', models.JSONField(blank=True, help_text='Additional context in JSON format', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(help_text='The snapshot this log pertains to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='investing.equitysnapshot')),
            ],
            options={
                'verbose_name': 'Snapshot Audit Log',
                'verbose_name_plural': 'Snapshot Audit Logs',
                'db_table': 'shareholders_snapshot_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquitySnapshotLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_usd', models.DecimalField(decimal_places=2, default=0, help_text='Cash contributions in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('inkind_usd', models.DecimalField(decimal_places=2, default=0, help_text='In-kind contributions in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('time_usd', models.DecimalField(decimal_places=2, default=0, help_text='Time contributions in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_usd', models.DecimalField(decimal_places=2, default=0, help_text='Work contributions in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('weighted_total_usd', models.DecimalField(decimal_places=2, default=0, help_text='Weighted total based on tier weights', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('equity_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Equity ownership percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('member_name', models.CharField(help_text='Member name at snapshot time (cached)', max_length=255)),
                ('member_type', models.CharField(help_text='Member type at snapshot time (cached)', max_length=10)),
                ('member_role', models.CharField(blank=True, help_text='Member role at snapshot time (cached)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(help_text='Member this line refers to', on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_lines', to='investing.member')),
                ('snapshot', models.ForeignKey(help_text='Associated snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='investing.equitysnapshot')),
            ],
            options={
                'verbose_name': 'Equity Snapshot Line',
                'verbose_name_plural': 'Equity Snapshot Lines',
                'db_table': 'shareholders_equity_snapshot_line',
                'ordering': ['-equity_percentage', 'member_name'],
            },
        ),
        migrations.AddIndex(
            model_name='snapshotauditlog',
            index=models.Index(fields=['snapshot', 'action'], name='shareholder_snapsho_c98a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotauditlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='shareholder_perform_236446_idx'),
        ),
        migrations.AddIndex(
            model_name='equitysnapshotline',
            index=models.Index(fields=['snapshot', 'member'], name='shareholder_snapsho_4b7a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='equitysnapshotline',
            index=models.Index(fields=['snapshot', 'equity_percentage'], name='shareholder_snapsho_c1dcbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equitysnapshotline',
            unique_together={('snapshot', 'member')},
        ),
        migrations.AddIndex(
            model_name='equitysnapshot',
            index=models.Index(fields=['deal', 'snapshot_date'], name='shareholder_deal_id_8833bf_idx'),
        ),
        migrations.AddIndex(
            model_name='equitysnapshot',
            index=models.Index(fields=['deal', 'is_locked'], name='shareholder_deal_id_a92407_idx'),
        ),
        migrations.AddIndex(
            model_name='equitysnapshot',
            index=models.Index(fields=['deal', 'status'], name='shareholder_deal_id_9f7661_idx'),
        ),
        migrations.AddIndex(
            model_name='equitysnapshot',
            index=models.Index(fields=['version_id'], name='shareholder_version_a1d8ba_idx'),
        ),
    ]
