# Generated by Django 3.2.6 on 2026-02-10 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0003_auto_20260211_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealconfig',
            name='auto_lock_snapshots',
            field=models.BooleanField(default=True, help_text='Automatically lock snapshots after dispute window'),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='inkind_valuation_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('RATE', 'Rate-Based')], default='MANUAL', help_text='How to value in-kind contributions', max_length=10),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='require_approval_cash',
            field=models.BooleanField(default=True, help_text='Require admin approval for cash contributions'),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='require_approval_inkind',
            field=models.BooleanField(default=True, help_text='Require admin approval for in-kind contributions'),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='require_approval_time',
            field=models.BooleanField(default=False, help_text='Require admin approval for time contributions'),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='require_approval_work',
            field=models.BooleanField(default=False, help_text='Require admin approval for work contributions'),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='snapshot_day',
            field=models.IntegerField(default=1, help_text='Day of month for scheduled snapshots (1-28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='snapshot_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('MANUAL', 'Manual Only')], default='MONTHLY', help_text='How often to auto-generate snapshots', max_length=10),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='time_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='USD value per hour of time contribution', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dealconfig',
            name='work_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='USD value per work unit/point', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dealconfig',
            name='dispute_window_days',
            field=models.IntegerField(default=7, help_text='Days allowed for disputes before auto-approval', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dealconfig',
            name='next_snapshot_date',
            field=models.DateField(blank=True, help_text='Next scheduled snapshot date', null=True),
        ),
    ]
