# Generated by Django 3.2.6 on 2025-10-28 22:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0003_auto_20251027_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTierConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tier_code', models.CharField(choices=[('starter', 'Starter - Automated Execution'), ('professional', 'Professional - Weekly Strategy'), ('premium', 'Premium - Enhanced Support'), ('consultative', 'Consultative - 1-on-1 Sessions'), ('co_invest', 'Co-Investment - Partnership')], help_text='Unique identifier for this tier', max_length=20, unique=True)),
                ('tier_name', models.CharField(help_text="Display name (e.g., 'Starter - Automated Execution')", max_length=100)),
                ('minimum_capital', models.DecimalField(decimal_places=2, help_text='Minimum capital required for this tier', max_digits=12)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed monthly fee (set to 0 if none)', max_digits=10)),
                ('profit_share_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of profits shared (e.g., 10 for 10%)', max_digits=5)),
                ('per_session_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee per session (for consultative tier)', max_digits=10)),
                ('max_sessions_per_month', models.IntegerField(default=0, help_text='Maximum sessions per month (0 if unlimited)')),
                ('short_description', models.CharField(help_text='Brief description for tier card', max_length=200)),
                ('features', models.JSONField(default=list, help_text="List of features (e.g., ['AI-driven trades', 'Real-time monitoring'])")),
                ('compatible_risk_levels', models.JSONField(default=list, help_text="Risk levels this tier is suitable for (e.g., ['low', 'medium'])")),
                ('is_active', models.BooleanField(default=True, help_text='Is this tier currently available?')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display tiers (lower = first)')),
            ],
            options={
                'verbose_name': 'Fee Tier Configuration',
                'verbose_name_plural': 'Fee Tier Configurations',
                'ordering': ['display_order', 'minimum_capital'],
            },
        ),
    ]
