# Generated by Django 3.2.6 on 2026-02-10 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0004_auto_20260211_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this action occurred')),
                ('action_type', models.CharField(choices=[('MEMBER_CREATED', 'Member Created'), ('MEMBER_UPDATED', 'Member Updated'), ('MEMBER_ARCHIVED', 'Member Archived'), ('MEMBER_RESTORED', 'Member Restored'), ('CONTRIBUTION_SUBMITTED', 'Contribution Submitted'), ('CONTRIBUTION_UPDATED', 'Contribution Updated'), ('LEDGER_CREATED', 'Ledger Entry Created'), ('LEDGER_APPROVED', 'Ledger Entry Approved'), ('LEDGER_REJECTED', 'Ledger Entry Rejected'), ('LEDGER_DISPUTED', 'Ledger Entry Disputed'), ('LEDGER_DISPUTE_RESOLVED', 'Dispute Resolved'), ('SNAPSHOT_CREATED', 'Snapshot Created'), ('SNAPSHOT_LOCKED', 'Snapshot Locked'), ('SNAPSHOT_UNLOCKED', 'Snapshot Unlocked'), ('SNAPSHOT_EXPORTED', 'Snapshot Exported'), ('SNAPSHOT_DELETED', 'Snapshot Deleted'), ('CONFIG_UPDATED', 'Deal Config Updated'), ('WEIGHTS_UPDATED', 'Contribution Weights Updated'), ('FX_RATE_UPDATED', 'FX Rate Updated'), ('VERIFICATION_SUBMITTED', 'Verification Submitted'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('EVIDENCE_REMOVED', 'Evidence Removed')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('entity_type', models.CharField(choices=[('MEMBER', 'Member'), ('CONTRIBUTION', 'Contribution'), ('LEDGER_ENTRY', 'Ledger Entry'), ('SNAPSHOT', 'Equity Snapshot'), ('DEAL_CONFIG', 'Deal Configuration'), ('DEAL_WEIGHTS', 'Deal Weights'), ('VERIFICATION', 'Verification'), ('EVIDENCE', 'Evidence'), ('DEAL', 'Deal')], db_index=True, help_text='Type of entity affected', max_length=50)),
                ('entity_id', models.CharField(db_index=True, help_text='ID or unique identifier of the affected entity', max_length=255)),
                ('entity_reference', models.CharField(help_text='Human-readable reference (e.g., TX-20260211-001, v1.3-q1)', max_length=255)),
                ('description', models.TextField(help_text='Human-readable description of what happened')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('request_source', models.CharField(blank=True, help_text='Source of request (web, api, admin, system)', max_length=50, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', help_text='Status of the action', max_length=20)),
                ('details', models.JSONField(blank=True, help_text='Additional structured data (changes, metadata, etc.)', null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Previous values before the change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values after the change', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shareholder_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(help_text='The deal this audit log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='investing.deal')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'shareholders_audit_log',
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_log', 'Can view audit logs')],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['deal', 'timestamp'], name='shareholder_deal_id_320718_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='shareholder_action__86e5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'timestamp'], name='shareholder_entity__d5050c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='shareholder_actor_i_55da15_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='shareholder_entity__1b6c96_idx'),
        ),
    ]
