# Generated by Django 3.2.6 on 2025-10-29 06:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0004_add_fee_tier_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('optionplay', 'OptionPlay API'), ('thinkorswim', 'Thinkorswim/TD Ameritrade'), ('manual', 'Manual Entry')], help_text='Where this position was sourced from', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When position was fetched from API')),
                ('symbol', models.CharField(help_text='Underlying stock ticker (e.g., AAPL, TSLA)', max_length=10)),
                ('strategy', models.CharField(choices=[('short_put', 'Cash-Secured Short Put'), ('covered_call', 'Covered Call'), ('bull_put_spread', 'Bull Put Spread'), ('bear_call_spread', 'Bear Call Spread'), ('bull_call_spread', 'Bull Call Spread'), ('bear_put_spread', 'Bear Put Spread'), ('iron_condor', 'Iron Condor'), ('long_call', 'Long Call'), ('long_put', 'Long Put'), ('other', 'Other Strategy')], help_text='Options strategy type', max_length=30)),
                ('positions', models.JSONField(help_text='Array of position legs: [{type, strike, contracts, premium, delta, theta}]')),
                ('expiration_date', models.DateField(help_text='Option expiration date')),
                ('dte', models.IntegerField(help_text='Days to expiration (calculated at fetch time)')),
                ('premium_collected', models.DecimalField(decimal_places=2, help_text='Total premium collected/paid', max_digits=10)),
                ('capital_required', models.DecimalField(decimal_places=2, help_text='Capital required for position', max_digits=12)),
                ('max_profit', models.DecimalField(decimal_places=2, help_text='Maximum possible profit', max_digits=10)),
                ('max_loss', models.DecimalField(decimal_places=2, help_text='Maximum possible loss', max_digits=12)),
                ('breakeven', models.DecimalField(blank=True, decimal_places=2, help_text='Breakeven price', max_digits=10, null=True)),
                ('probability_of_profit', models.DecimalField(decimal_places=2, help_text='Probability of profit % (e.g., 75.00 = 75%)', max_digits=5)),
                ('position_delta', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Net position delta', max_digits=8)),
                ('position_theta', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Net position theta (daily time decay)', max_digits=8)),
                ('position_gamma', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Net position gamma', max_digits=8)),
                ('position_vega', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Net position vega (volatility sensitivity)', max_digits=8)),
                ('api_response_data', models.JSONField(blank=True, default=dict, help_text='Raw API response for reference')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-100)', max_digits=5, null=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why AI recommended this position')),
                ('review_status', models.CharField(choices=[('pending', 'Pending Staff Review'), ('approved', 'Approved by Staff'), ('modified', 'Modified & Approved'), ('rejected', 'Rejected by Staff'), ('converted', 'Converted to Batch')], default='pending', help_text='Staff review status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When staff reviewed this position', null=True)),
                ('staff_notes', models.TextField(blank=True, help_text='Staff comments, modifications, or rejection reasons')),
                ('created_position', models.OneToOneField(blank=True, help_text='Actual position created from this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestion', to='investing.optionsposition')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who reviewed this', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggested_positions', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, help_text='Which account this position is intended for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_positions', to='investing.managedtradingaccount')),
            ],
            options={
                'verbose_name': 'Suggested Position',
                'verbose_name_plural': 'Suggested Positions',
                'ordering': ['-probability_of_profit', '-fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='suggestedposition',
            index=models.Index(fields=['review_status', '-fetched_at'], name='investing_s_review__9d453f_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedposition',
            index=models.Index(fields=['source', 'review_status'], name='investing_s_source_1f4584_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedposition',
            index=models.Index(fields=['-probability_of_profit'], name='investing_s_probabi_bc147d_idx'),
        ),
    ]
