# Generated by Django 3.2.6 on 2026-02-11 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0005_auto_20260211_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who registered this member (ownership for edit authorization)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['created_by'], name='shareholder_created_2db43b_idx'),
        ),
    ]
