# Generated by Django 3.2.6 on 2025-11-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0005_add_suggested_position_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingrule',
            name='rule_type',
            field=models.CharField(choices=[('position_limit', 'Position Size Limit'), ('position_size_percentage', 'Position Size % of Capital'), ('risk_limit', 'Risk Limit'), ('profit_target', 'Profit Target'), ('stop_loss', 'Stop Loss'), ('time_based', 'Time-Based Rule'), ('exposure_limit', 'Total Exposure Limit'), ('custom', 'Custom Rule')], max_length=30),
        ),
    ]
