# Generated by Django 3.2.6 on 2025-11-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0006_add_position_sizing_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingactivity',
            name='activity_type',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('account_modified', 'Account Modified'), ('account_paused', 'Account Paused'), ('account_activated', 'Account Activated'), ('position_opened', 'Position Opened'), ('position_closed', 'Position Closed'), ('position_rolled', 'Position Rolled'), ('pnl_adjusted', 'P&L Manually Adjusted'), ('alert_generated', 'Alert Generated'), ('rule_violated', 'Rule Violated'), ('rule_changed', 'Rule Changed'), ('fee_calculated', 'Fee Calculated'), ('session_completed', 'Coaching Session Completed'), ('other', 'Other Activity')], max_length=30),
        ),
    ]
