# Generated by Django 3.2.6 on 2026-02-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0006_member_add_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='tier_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Tier-specific structured data. IN_KIND: {valuation_method}. TIME: {role_multiplier}. WORK: {deliverable_title, impact_tier}.', null=True),
        ),
    ]
