# Generated by Django 3.2.6 on 2026-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0007_ledgerentry_add_tier_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Member profile photo (JPG, PNG, max 2 MB)', null=True, upload_to='shareholders/profile_photos/%Y/%m/'),
        ),
    ]
