# Generated by Django 3.2.6 on 2025-11-02 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0007_add_pnl_adjustment_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPlayRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('strategy_type', models.CharField(choices=[('credit_spread', 'Credit Spread'), ('short_put', 'Short Put'), ('covered_call', 'Covered Call')], help_text='Type of position from CSV', max_length=20)),
                ('symbol', models.CharField(help_text='Stock ticker symbol', max_length=10)),
                ('spread_strategy', models.CharField(blank=True, help_text='Bearish or Bullish (for credit spreads)', max_length=20, null=True)),
                ('option_type', models.CharField(blank=True, help_text='Call or Put (for credit spreads)', max_length=10, null=True)),
                ('stock_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current stock price', max_digits=10, null=True)),
                ('sell_strike', models.DecimalField(decimal_places=2, help_text='Short leg strike price', max_digits=10)),
                ('buy_strike', models.DecimalField(blank=True, decimal_places=2, help_text='Long leg strike price (null for naked short puts)', max_digits=10, null=True)),
                ('expiry', models.DateField(help_text='Option expiration date')),
                ('days_to_expiry', models.IntegerField(help_text='Days to expiration at upload time')),
                ('premium', models.DecimalField(decimal_places=2, help_text='Premium collected per contract', max_digits=10)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Spread width (for spreads only)', max_digits=10, null=True)),
                ('prem_width_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Premium/Width ratio (%) - indicates edge', max_digits=5, null=True)),
                ('iv_rank', models.DecimalField(blank=True, decimal_places=2, help_text='Implied Volatility Rank (%)', max_digits=5, null=True)),
                ('raw_return', models.DecimalField(blank=True, decimal_places=2, help_text='Return on capital if held to expiration (%)', max_digits=8, null=True)),
                ('annualized_return', models.DecimalField(blank=True, decimal_places=2, help_text='Annualized return (%)', max_digits=8, null=True)),
                ('distance_to_strike', models.DecimalField(blank=True, decimal_places=2, help_text='% distance from current price to strike (negative = OTM)', max_digits=8, null=True)),
                ('earnings_date', models.CharField(blank=True, help_text='Earnings date from CSV', max_length=50)),
                ('earnings_flag', models.CharField(blank=True, help_text='Y/N - position includes earnings', max_length=5)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_notes', models.TextField(blank=True, help_text='Notes about this upload batch')),
                ('is_processed', models.BooleanField(default=False, help_text='Has this been converted to SuggestedPosition?')),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if conversion failed')),
                ('csv_row_data', models.JSONField(blank=True, default=dict, help_text='Original CSV row as JSON')),
                ('created_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_raw_data', to='investing.suggestedposition')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_optionplay_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OptionPlay Raw Data',
                'verbose_name_plural': 'OptionPlay Raw Data Uploads',
                'ordering': ['-upload_date', 'symbol'],
            },
        ),
        migrations.AddIndex(
            model_name='optionplayrawdata',
            index=models.Index(fields=['strategy_type', 'is_processed'], name='investing_o_strateg_ff631c_idx'),
        ),
        migrations.AddIndex(
            model_name='optionplayrawdata',
            index=models.Index(fields=['symbol', 'expiry'], name='investing_o_symbol_7ed8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='optionplayrawdata',
            index=models.Index(fields=['is_processed', 'upload_date'], name='investing_o_is_proc_0594a8_idx'),
        ),
    ]
