# Generated by Django 3.2.6 on 2025-11-02 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0008_add_optionplay_raw_data_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsPositionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('was_profitable', models.BooleanField(help_text='True if position made money')),
                ('actual_return_amount', models.DecimalField(decimal_places=2, help_text='Actual profit/loss in dollars', max_digits=10)),
                ('actual_return_percentage', models.DecimalField(decimal_places=2, help_text='ROI as percentage of capital required', max_digits=8)),
                ('days_held', models.IntegerField(help_text='Number of days position was open')),
                ('annualized_return', models.DecimalField(decimal_places=2, help_text='Return annualized (ROI * 365 / days_held)', max_digits=8)),
                ('exit_reason', models.CharField(choices=[('profit_target', 'Hit Profit Target'), ('stop_loss', 'Hit Stop Loss'), ('expiration', 'Held to Expiration'), ('early_close', 'Early Close (Manual)'), ('rolled', 'Rolled to New Position'), ('market_conditions', 'Market Conditions Changed'), ('other', 'Other Reason')], default='expiration', max_length=50)),
                ('exit_notes', models.TextField(blank=True, help_text='Why position was closed')),
                ('entry_iv_rank', models.DecimalField(blank=True, decimal_places=2, help_text='IV Rank when position opened (0-100)', max_digits=5, null=True)),
                ('entry_market_trend', models.CharField(blank=True, choices=[('strong_bullish', 'Strong Bullish'), ('bullish', 'Bullish'), ('neutral', 'Neutral'), ('bearish', 'Bearish'), ('strong_bearish', 'Strong Bearish')], help_text='Market trend at entry', max_length=20, null=True)),
                ('entry_vix', models.DecimalField(blank=True, decimal_places=2, help_text='VIX level at entry', max_digits=5, null=True)),
                ('entry_stock_price', models.DecimalField(blank=True, decimal_places=2, help_text='Stock price when position opened', max_digits=10, null=True)),
                ('days_to_earnings', models.IntegerField(blank=True, help_text='Days until next earnings when opened', null=True)),
                ('exit_stock_price', models.DecimalField(blank=True, decimal_places=2, help_text='Stock price when closed', max_digits=10, null=True)),
                ('max_profit_captured', models.DecimalField(blank=True, decimal_places=2, help_text='% of max profit captured (50% = closed at 50% target)', max_digits=5, null=True)),
                ('ai_post_analysis', models.TextField(blank=True, help_text='AI-generated analysis of why position succeeded/failed')),
                ('ai_confidence_at_entry', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score when position was opened', max_digits=5, null=True)),
                ('performance_category', models.CharField(blank=True, choices=[('excellent', 'Excellent (>30% ROI)'), ('good', 'Good (15-30% ROI)'), ('average', 'Average (5-15% ROI)'), ('poor', 'Poor (0-5% ROI)'), ('loss', 'Loss (<0% ROI)')], help_text='Auto-categorized performance', max_length=20)),
                ('position', models.OneToOneField(help_text='Original position that was closed', on_delete=django.db.models.deletion.CASCADE, related_name='outcome_history', to='investing.optionsposition')),
            ],
            options={
                'verbose_name': 'Options Position History',
                'verbose_name_plural': 'Options Position Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='optionspositionhistory',
            index=models.Index(fields=['was_profitable', 'actual_return_percentage'], name='investing_o_was_pro_999a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='optionspositionhistory',
            index=models.Index(fields=['entry_market_trend', 'was_profitable'], name='investing_o_entry_m_478e87_idx'),
        ),
        migrations.AddIndex(
            model_name='optionspositionhistory',
            index=models.Index(fields=['performance_category'], name='investing_o_perform_ba02bf_idx'),
        ),
        migrations.AddIndex(
            model_name='optionspositionhistory',
            index=models.Index(fields=['exit_reason'], name='investing_o_exit_re_6f47a7_idx'),
        ),
    ]
