# Generated by Django 3.2.6 on 2025-11-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0009_add_position_history_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedposition',
            name='ai_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of 6 scoring factors'),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='ai_confidence_level',
            field=models.CharField(blank=True, choices=[('HIGH', 'High Confidence'), ('MEDIUM', 'Medium Confidence'), ('LOW', 'Low Confidence')], help_text='Confidence level based on data availability', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='ai_rating',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent (95-100)'), ('GOOD', 'Good (85-94)'), ('AVERAGE', 'Average (70-84)'), ('BELOW_AVERAGE', 'Below Average (50-69)'), ('POOR', 'Poor (0-49)')], help_text='AI rating based on score', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='ai_recommendation',
            field=models.TextField(blank=True, help_text='AI recommendation text (approve/review/reject)'),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI position score (0-100) from 6-factor algorithm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedposition',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-100) - DEPRECATED, use ai_score instead', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedposition',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text='Why AI recommended this position - DEPRECATED, use ai_recommendation instead'),
        ),
    ]
