# Generated by Django 3.2.6 on 2025-11-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0010_add_ai_scoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedtradingaccount',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Client Telegram chat ID', max_length=50),
        ),
        migrations.AddField(
            model_name='managedtradingaccount',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Enable Telegram notifications for position updates'),
        ),
        migrations.AddField(
            model_name='managedtradingaccount',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Enable WhatsApp notifications for position updates'),
        ),
        migrations.AddField(
            model_name='managedtradingaccount',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Client phone number in international format (+1234567890)', max_length=20),
        ),
    ]
