# Generated by Django 3.2.6 on 2025-11-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0011_add_whatsapp_telegram_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionbatch',
            name='approval_method',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp Reply'), ('sms', 'SMS Reply'), ('portal', 'Client Portal'), ('email', 'Email Link'), ('phone', 'Phone Call')], help_text='How client approved this batch', max_length=20),
        ),
        migrations.AddField(
            model_name='positionbatch',
            name='approval_token',
            field=models.CharField(blank=True, help_text='Token for quick approval via WhatsApp/SMS', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='positionbatch',
            name='sms_notification_date',
            field=models.DateTimeField(blank=True, help_text='When SMS notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='positionbatch',
            name='sms_notification_sent',
            field=models.BooleanField(default=False, help_text='Was SMS notification sent?'),
        ),
        migrations.AddField(
            model_name='positionbatch',
            name='whatsapp_notification_date',
            field=models.DateTimeField(blank=True, help_text='When WhatsApp notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='positionbatch',
            name='whatsapp_notification_sent',
            field=models.BooleanField(default=False, help_text='Was WhatsApp notification sent?'),
        ),
    ]
