# Generated by Django 3.2.6 on 2025-11-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0012_add_whatsapp_approval_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedposition',
            name='notes',
            field=models.TextField(blank=True, help_text='System-generated notes (technical analysis, cross-validation, flow signals, etc.)'),
        ),
    ]
