# Generated by Django 3.2.6 on 2025-11-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0013_suggestedposition_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionplayrawdata',
            name='strategy_type',
            field=models.CharField(choices=[('credit_spread', 'Credit Spread'), ('bull_put_spread', 'Bull Put Spread'), ('bear_call_spread', 'Bear Call Spread'), ('iron_condor', 'Iron Condor'), ('short_put', 'Short Put'), ('covered_call', 'Covered Call'), ('short_call', 'Short Call')], help_text='Type of position from CSV', max_length=30),
        ),
    ]
