# Generated by Django 3.2.6 on 2025-11-05 19:43

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove legacy models: ShortPut, covered_calls, Portfolio
    
    Background:
    - These models used incorrect data types (CharField for numeric values)
    - ShortPut: 2 records (backed up to CSV)
    - covered_calls: 33 records (backed up to CSV) 
    - Portfolio: Never migrated (table doesn't exist in database)
    - All superseded by OptionsPosition model with proper Decimal fields
    
    Data Backup: legacy_shortput_backup_20251105_112852.csv
                 legacy_covered_calls_backup_20251105_112852.csv
    """

    dependencies = [
        ('investing', '0014_add_spread_strategy_types'),
    ]

    operations = [
        # Drop ShortPut table
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS investing_shortput CASCADE;',
            reverse_sql='-- Cannot reverse: Data backed up to CSV before deletion',
        ),
        
        # Drop covered_calls table
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS investing_covered_calls CASCADE;',
            reverse_sql='-- Cannot reverse: Data backed up to CSV before deletion',
        ),
        
        # Portfolio table never existed in database (migration never ran)
        # No DROP needed
    ]
