# Generated by Django 5.2.6 on 2025-11-12 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0023_add_suggested_position_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Cost_Basis',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS investing_cost_basis CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='covered_calls',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS investing_covered_calls CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='credit_spread',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS investing_credit_spread CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Options_Returns',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS investing_options_returns CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='OverBoughtSold',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS investing_overboughtsold CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='portfolio',
                    name='user',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.tables
                                WHERE table_name = 'investing_portfolio'
                            ) THEN
                                IF EXISTS (
                                    SELECT 1 FROM information_schema.columns
                                    WHERE table_name = 'investing_portfolio'
                                      AND column_name = 'user_id'
                                ) THEN
                                    ALTER TABLE investing_portfolio DROP COLUMN user_id;
                                END IF;
                            END IF;
                        END;
                        $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='SavedResponses',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS investing_savedresponses CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ShortPut',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS investing_shortput CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'optionspos_managed_entry_idx'
                    ) THEN
                        ALTER INDEX optionspos_managed_entry_idx
                        RENAME TO investing_o_managed_6ac7ce_idx;
                    END IF;
                END;
                $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'investing_o_managed_6ac7ce_idx'
                    ) THEN
                        ALTER INDEX investing_o_managed_6ac7ce_idx
                        RENAME TO optionspos_managed_entry_idx;
                    END IF;
                END;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'suggested_rev_ai_idx'
                    ) THEN
                        ALTER INDEX suggested_rev_ai_idx
                        RENAME TO investing_s_review__6c0d21_idx;
                    END IF;
                END;
                $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'investing_s_review__6c0d21_idx'
                    ) THEN
                        ALTER INDEX investing_s_review__6c0d21_idx
                        RENAME TO suggested_rev_ai_idx;
                    END IF;
                END;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'suggested_symbol_review_idx'
                    ) THEN
                        ALTER INDEX suggested_symbol_review_idx
                        RENAME TO investing_s_symbol_da6ab7_idx;
                    END IF;
                END;
                $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'investing_s_symbol_da6ab7_idx'
                    ) THEN
                        ALTER INDEX investing_s_symbol_da6ab7_idx
                        RENAME TO suggested_symbol_review_idx;
                    END IF;
                END;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'sp_outcome_source_status_idx'
                    ) THEN
                        ALTER INDEX sp_outcome_source_status_idx
                        RENAME TO investing_s_source_bf2455_idx;
                    END IF;
                END;
                $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'investing_s_source_bf2455_idx'
                    ) THEN
                        ALTER INDEX investing_s_source_bf2455_idx
                        RENAME TO sp_outcome_source_status_idx;
                    END IF;
                END;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'sp_outcome_symbol_expiry_idx'
                    ) THEN
                        ALTER INDEX sp_outcome_symbol_expiry_idx
                        RENAME TO investing_s_symbol_318295_idx;
                    END IF;
                END;
                $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'investing_s_symbol_318295_idx'
                    ) THEN
                        ALTER INDEX investing_s_symbol_318295_idx
                        RENAME TO sp_outcome_symbol_expiry_idx;
                    END IF;
                END;
                $$;
            """,
        ),
        migrations.AlterField(
            model_name='brokerconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='brokerconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor_information',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managedtradingaccount',
            name='fee_tier',
            field=models.CharField(choices=[('balanced', 'Balanced Automation - $249/mo + 12% over 6% hurdle'), ('consultative', 'Consultative Coaching - Legacy $420 Plan'), ('elite', 'Elite Desk (Coming Soon) - $399/mo + 18% over 5% hurdle'), ('custom', 'Custom Fee Structure'), ('starter', 'Starter - Legacy (inactive)'), ('professional', 'Professional - Legacy (inactive)'), ('premium', 'Premium - Legacy (inactive)'), ('co_invest', 'Co-Investment - Legacy (inactive)')], default='balanced', help_text='Fee tier selected by client', max_length=20),
        ),
        migrations.AlterField(
            model_name='managedtradingapplication',
            name='fee_tier',
            field=models.CharField(choices=[('balanced', 'Balanced Automation - $249/mo + 12% over 6% hurdle'), ('consultative', 'Consultative Coaching - Legacy $420 Plan'), ('elite', 'Elite Desk (Coming Soon) - $399/mo + 18% over 5% hurdle'), ('custom', 'Custom Fee Structure'), ('starter', 'Starter - Legacy (inactive)'), ('professional', 'Professional - Legacy (inactive)'), ('premium', 'Premium - Legacy (inactive)'), ('co_invest', 'Co-Investment - Legacy (inactive)')], help_text='Selected fee tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='optionplayrawdata',
            name='strategy_type',
            field=models.CharField(choices=[('short_put', 'Cash-Secured Short Put'), ('covered_call', 'Covered Call'), ('short_call', 'Naked Short Call'), ('bull_put_spread', 'Bull Put Spread'), ('bear_call_spread', 'Bear Call Spread'), ('bull_call_spread', 'Bull Call Spread'), ('bear_put_spread', 'Bear Put Spread'), ('iron_condor', 'Iron Condor'), ('long_call', 'Long Call'), ('long_put', 'Long Put'), ('straddle', 'Straddle'), ('strangle', 'Strangle'), ('other', 'Other Strategy')], help_text='Type of position from CSV', max_length=30),
        ),
        migrations.AlterField(
            model_name='optionsposition',
            name='strategy',
            field=models.CharField(choices=[('short_put', 'Cash-Secured Short Put'), ('covered_call', 'Covered Call'), ('short_call', 'Naked Short Call'), ('bull_put_spread', 'Bull Put Spread'), ('bear_call_spread', 'Bear Call Spread'), ('bull_call_spread', 'Bull Call Spread'), ('bear_put_spread', 'Bear Put Spread'), ('iron_condor', 'Iron Condor'), ('long_call', 'Long Call'), ('long_put', 'Long Put'), ('straddle', 'Straddle'), ('strangle', 'Strangle'), ('other', 'Other Strategy')], help_text='Options strategy type', max_length=30),
        ),
        migrations.AlterField(
            model_name='positionbatch',
            name='approval_method',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp Reply'), ('sms', 'SMS Reply'), ('portal', 'Client Portal'), ('email', 'Email Link'), ('phone', 'Phone Call'), ('auto', 'Auto Approval (Client Timeout)')], help_text='How client approved this batch', max_length=20),
        ),
        migrations.AlterField(
            model_name='positionbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Client Approval'), ('auto_approved', 'Auto Approved - Awaiting Trader Entry'), ('approved', 'Approved'), ('rejected', 'Rejected by Client'), ('expired', 'Expired (24hr timeout)'), ('partial', 'Partially Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestedposition',
            name='source',
            field=models.CharField(choices=[('optionplay', 'OptionPlay API'), ('thinkorswim', 'Thinkorswim/TD Ameritrade'), ('unusual_whales', 'Unusual Whales'), ('manual', 'Manual Entry')], help_text='Where this position was sourced from', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestedposition',
            name='strategy',
            field=models.CharField(choices=[('short_put', 'Cash-Secured Short Put'), ('covered_call', 'Covered Call'), ('short_call', 'Naked Short Call'), ('bull_put_spread', 'Bull Put Spread'), ('bear_call_spread', 'Bear Call Spread'), ('bull_call_spread', 'Bull Call Spread'), ('bear_put_spread', 'Bear Put Spread'), ('iron_condor', 'Iron Condor'), ('long_call', 'Long Call'), ('long_put', 'Long Put'), ('straddle', 'Straddle'), ('strangle', 'Strangle'), ('other', 'Other Strategy')], help_text='Options strategy type', max_length=30),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Portfolio',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS investing_portfolio CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
