# Generated by Django 3.2.6 on 2025-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0024_delete_cost_basis_delete_covered_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedposition',
            name='fade_probability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Probability (%) that fading the move is safer', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='follow_probability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Probability (%) that following the flow is preferred', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='minimum_fee_tier',
            field=models.CharField(choices=[('balanced', 'Balanced Automation - $249/mo + 12% over 6% hurdle'), ('consultative', 'Consultative Coaching - Legacy $420 Plan'), ('elite', 'Elite Desk (Coming Soon) - $399/mo + 18% over 5% hurdle'), ('custom', 'Custom Fee Structure'), ('starter', 'Starter - Legacy (inactive)'), ('professional', 'Professional - Legacy (inactive)'), ('premium', 'Premium - Legacy (inactive)'), ('co_invest', 'Co-Investment - Legacy (inactive)')], default='balanced', help_text='Minimum client plan required to auto-deliver this signal', max_length=20),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='momentum_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Captured technical indicators (RSI, VWAP distance, volume z-score, etc.)'),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='signal_intent',
            field=models.CharField(choices=[('follow', 'Follow Flow'), ('fade', 'Fade Exhaustion'), ('neutral', 'Neutral / Manual Review')], default='neutral', help_text='Classifier output describing whether to follow or fade the flow', max_length=20),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='signal_last_evaluated',
            field=models.DateTimeField(blank=True, help_text='When the follow/fade classifier last refreshed this record', null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='signal_tier',
            field=models.CharField(choices=[('apex', 'Excellent (Apex)'), ('strong', 'High (Strong)'), ('watchlist', 'Good (Watchlist)')], default='watchlist', help_text='Commercial tier this signal belongs to (maps to client plan access)', max_length=20),
        ),
    ]
