# Generated by Django 3.2.6 on 2025-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0025_auto_20251114_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedposition',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this suggestion was captured', null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='captured_underlying_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Underlying price recorded at fetch time', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='consistency_streak',
            field=models.IntegerField(default=1, help_text='Number of consecutive fetches this symbol/strategy has appeared'),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='fetch_batch_id',
            field=models.CharField(blank=True, help_text='Identifier for the upstream fetch batch', max_length=64),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='persisted_from_last_fetch',
            field=models.BooleanField(default=False, help_text='True when this symbol/strategy persisted across consecutive fetches'),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='price_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Allowed deviation ($) from captured underlying price', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='time_tolerance_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes this suggestion remains valid', null=True),
        ),
        migrations.AddField(
            model_name='suggestedposition',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='When this suggestion should expire if not actioned', null=True),
        ),
    ]
