# Generated by Django 3.2.6 on 2025-11-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0026_auto_20251114_2041'),
    ]

    operations = [
        # Remove old indexes (if they exist) - idempotent
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS investing_optionspos_managed_entry_idx;",
            reverse_sql="-- Cannot reverse index drop",
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS investing_suggested_rev_ai_idx;",
            reverse_sql="-- Cannot reverse index drop",
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS investing_suggested_symbol_review_idx;",
            reverse_sql="-- Cannot reverse index drop",
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS investing_sp_outcome_source_status_idx;",
            reverse_sql="-- Cannot reverse index drop",
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS investing_sp_outcome_symbol_expiry_idx;",
            reverse_sql="-- Cannot reverse index drop",
        ),
        migrations.AddField(
            model_name='optionspositionhistory',
            name='feedback_added_at',
            field=models.DateTimeField(blank=True, help_text='When feedback was added', null=True),
        ),
        migrations.AddField(
            model_name='optionspositionhistory',
            name='feedback_added_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who added feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optionspositionhistory',
            name='staff_feedback',
            field=models.TextField(blank=True, help_text='Staff notes/annotations on trade outcome for learning and improvement'),
        ),
        migrations.AlterField(
            model_name='tradingactivity',
            name='activity_type',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('account_modified', 'Account Modified'), ('account_paused', 'Account Paused'), ('account_activated', 'Account Activated'), ('position_opened', 'Position Opened'), ('position_closed', 'Position Closed'), ('position_rolled', 'Position Rolled'), ('pnl_adjusted', 'P&L Manually Adjusted'), ('alert_generated', 'Alert Generated'), ('rule_violated', 'Rule Violated'), ('rule_changed', 'Rule Changed'), ('fee_calculated', 'Fee Calculated'), ('session_completed', 'Coaching Session Completed'), ('client_review_requested', 'Client Review Requested'), ('other', 'Other Activity')], max_length=30),
        ),
        # Add new indexes (if they don't exist) - idempotent
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS investing_o_managed_6ac7ce_idx 
            ON investing_optionsposition (managed_account_id, entry_date DESC);
            """,
            reverse_sql="DROP INDEX IF EXISTS investing_o_managed_6ac7ce_idx;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS investing_s_review__6c0d21_idx 
            ON investing_suggestedposition (review_status, ai_score DESC);
            """,
            reverse_sql="DROP INDEX IF EXISTS investing_s_review__6c0d21_idx;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS investing_s_symbol_da6ab7_idx 
            ON investing_suggestedposition (symbol, review_status);
            """,
            reverse_sql="DROP INDEX IF EXISTS investing_s_symbol_da6ab7_idx;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS investing_s_source_bf2455_idx 
            ON investing_suggestedpositionoutcome (source, status);
            """,
            reverse_sql="DROP INDEX IF EXISTS investing_s_source_bf2455_idx;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS investing_s_symbol_318295_idx 
            ON investing_suggestedpositionoutcome (symbol, expiration_date);
            """,
            reverse_sql="DROP INDEX IF EXISTS investing_s_symbol_318295_idx;",
        ),
    ]
