# Generated by Django 3.2.6 on 2025-11-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0027_auto_20251117_2012'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='optionsposition',
            name='optionspos_managed_entry_idx',
        ),
        migrations.RemoveIndex(
            model_name='suggestedposition',
            name='suggested_rev_ai_idx',
        ),
        migrations.RemoveIndex(
            model_name='suggestedposition',
            name='suggested_symbol_review_idx',
        ),
        migrations.RemoveIndex(
            model_name='suggestedpositionoutcome',
            name='sp_outcome_source_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='suggestedpositionoutcome',
            name='sp_outcome_symbol_expiry_idx',
        ),
        migrations.AlterField(
            model_name='managedtradingaccount',
            name='fee_tier',
            field=models.CharField(choices=[('starter', 'Starter - $99/mo + 15% over 5% hurdle'), ('balanced', 'Balanced Automation - $249/mo + 12% over 6% hurdle'), ('elite', 'Elite - $399/mo + 14% over 5% hurdle'), ('consultative', 'Consultative - $420/mo + 10% over 8% hurdle (Premium Full Management)'), ('custom', 'Custom Fee Structure'), ('professional', 'Professional - Legacy (inactive)'), ('premium', 'Premium - Legacy (inactive)'), ('co_invest', 'Co-Investment - Legacy (inactive)')], default='balanced', help_text='Fee tier selected by client', max_length=20),
        ),
        migrations.AlterField(
            model_name='managedtradingapplication',
            name='fee_tier',
            field=models.CharField(choices=[('starter', 'Starter - $99/mo + 15% over 5% hurdle'), ('balanced', 'Balanced Automation - $249/mo + 12% over 6% hurdle'), ('elite', 'Elite - $399/mo + 14% over 5% hurdle'), ('consultative', 'Consultative - $420/mo + 10% over 8% hurdle (Premium Full Management)'), ('custom', 'Custom Fee Structure'), ('professional', 'Professional - Legacy (inactive)'), ('premium', 'Premium - Legacy (inactive)'), ('co_invest', 'Co-Investment - Legacy (inactive)')], help_text='Selected fee tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestedposition',
            name='minimum_fee_tier',
            field=models.CharField(choices=[('starter', 'Starter - $99/mo + 15% over 5% hurdle'), ('balanced', 'Balanced Automation - $249/mo + 12% over 6% hurdle'), ('elite', 'Elite - $399/mo + 14% over 5% hurdle'), ('consultative', 'Consultative - $420/mo + 10% over 8% hurdle (Premium Full Management)'), ('custom', 'Custom Fee Structure'), ('professional', 'Professional - Legacy (inactive)'), ('premium', 'Premium - Legacy (inactive)'), ('co_invest', 'Co-Investment - Legacy (inactive)')], default='balanced', help_text='Minimum client plan required to auto-deliver this signal', max_length=20),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_o_managed_6ac7ce_idx ON investing_optionsposition (managed_account_id, entry_date DESC);",
            reverse_sql="DROP INDEX IF EXISTS investing_o_managed_6ac7ce_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_s_review__6c0d21_idx ON investing_suggestedposition (review_status, ai_score DESC);",
            reverse_sql="DROP INDEX IF EXISTS investing_s_review__6c0d21_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_s_symbol_da6ab7_idx ON investing_suggestedposition (symbol, review_status);",
            reverse_sql="DROP INDEX IF EXISTS investing_s_symbol_da6ab7_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_s_source_bf2455_idx ON investing_suggestedpositionoutcome (source, status);",
            reverse_sql="DROP INDEX IF EXISTS investing_s_source_bf2455_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_s_symbol_318295_idx ON investing_suggestedpositionoutcome (symbol, expiration_date);",
            reverse_sql="DROP INDEX IF EXISTS investing_s_symbol_318295_idx;",
        ),
    ]
