# Generated by Django 3.2.6 on 2025-11-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0028_auto_20251118_0801'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_o_managed_6ac7ce_idx ON investing_optionsposition (managed_account_id, entry_date DESC);",
            reverse_sql="DROP INDEX IF EXISTS investing_o_managed_6ac7ce_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_s_review__6c0d21_idx ON investing_suggestedposition (review_status, ai_score DESC);",
            reverse_sql="DROP INDEX IF EXISTS investing_s_review__6c0d21_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_s_symbol_da6ab7_idx ON investing_suggestedposition (symbol, review_status);",
            reverse_sql="DROP INDEX IF EXISTS investing_s_symbol_da6ab7_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_s_source_bf2455_idx ON investing_suggestedpositionoutcome (source, status);",
            reverse_sql="DROP INDEX IF EXISTS investing_s_source_bf2455_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS investing_s_symbol_318295_idx ON investing_suggestedpositionoutcome (symbol, expiration_date);",
            reverse_sql="DROP INDEX IF EXISTS investing_s_symbol_318295_idx;",
        ),
    ]
