# Generated by Django 3.2.6 on 2025-11-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergencyHelpActivation',
            new_name='EmergencyHelpActivations',
        ),
    ]
