# Generated by Django 3.2.6 on 2025-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('salary_range', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=20)),
                ('employer', models.CharField(max_length=100)),
                ('posted_at', models.DateField()),
                ('expires_at', models.DateField()),
            ],
        ),
    ]
