# Generated by Django 3.2.6 on 2026-02-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0008_merge_20260218_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_bracket', models.CharField(choices=[('young', '18 - 30 Years'), ('mid', '31 - 55 Years'), ('senior', '56+ Years')], max_length=20)),
                ('residence', models.CharField(choices=[('usa', 'USA / Canada'), ('europe', 'Europe / UK'), ('other', 'Rest of World')], max_length=20)),
                ('priority', models.CharField(choices=[('budget', 'Cost Savings'), ('comprehensive', 'Full Coverage'), ('emergency', 'Emergency Only')], max_length=20)),
                ('recommendation_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyHotline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display label, e.g., Global Hotline', max_length=100)),
                ('number', models.CharField(help_text='E.164 like +15551234567 or local format', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpertInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=100)),
                ('max_benefit', models.CharField(max_length=50)),
                ('evacuation', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-score'],
            },
        ),
        migrations.DeleteModel(
            name='ConsularAssistancePage',
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='interested_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.insuranceplan'),
        ),
        migrations.AddField(
            model_name='airecommendationrule',
            name='recommended_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.insuranceplan'),
        ),
        migrations.AlterUniqueTogether(
            name='airecommendationrule',
            unique_together={('age_bracket', 'residence', 'priority')},
        ),
    ]
