# Generated by Django 5.2.11 on 2026-02-28 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsularAssistancePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consular Assistance Page',
                'verbose_name_plural': 'Consular Assistance Pages',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('categories', models.JSONField(default=list)),
                ('location_city', models.CharField(max_length=200)),
                ('location_country', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('languages', models.JSONField(default=list)),
                ('telehealth', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField()),
                ('education', models.JSONField(default=list)),
                ('avatar_color', models.CharField(default='#4A90D9', max_length=7)),
                ('avatar_initials', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', '-review_count'],
            },
        ),
        migrations.AlterModelOptions(
            name='governance',
            options={},
        ),
        migrations.AlterField(
            model_name='governance',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='governance',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='governance',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (8am–12pm)'), ('afternoon', 'Afternoon (12pm–5pm)'), ('evening', 'Evening (5pm–8pm)')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='new', max_length=20)),
                ('honeypot', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='main.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
