# Generated by Django 5.2.3 on 2025-08-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="governance",
            name="ui_order",
            field=models.IntegerField(default=0),
        ),
    ]
