# Generated by Django 3.2.6 on 2026-04-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSubPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_pricing', models.IntegerField()),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
