# Generated by Django 3.2.6 on 2025-10-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
