# Generated by Django 3.2.6 on 2026-03-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientAvailability',
        ),
    ]
