# Generated by Django 5.2.11 on 2026-03-18 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['deadline']},
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='amount',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='amount_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='amount_description',
            field=models.CharField(blank=True, help_text="E.g, 'Full tuition', 'Partial funding', etc.", max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='amount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='field',
            field=models.CharField(choices=[(' STEM', 'STEM'), ('Humanities', 'Humanities'), ('Business', 'Business'), ('Arts', 'Arts')], default=' STEM', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='level',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Vocational', 'Vocational')], default='Undergraduate', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='location',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Global', 'Global'), ('UK', 'UK'), ('USA', 'USA')], default='Global', max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closing Soon', 'Closing Soon'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
    ]
