# Generated by Django 5.2.11 on 2026-04-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal_servicess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter service title', max_length=200)),
                ('category', models.CharField(choices=[('visa', 'Visa and Residency Services'), ('citizenship', 'Citizenship and Naturalization'), ('legal_referral', 'Legal Representation & Referrals')], help_text='Select the type of legal service', max_length=50)),
                ('description', models.TextField(help_text='Detailed explanation of this service')),
                ('image_url', models.URLField(blank=True, help_text='Image URL: /static/community/img/visa-residency.png', null=True)),
                ('features', models.JSONField(default=list, help_text='Format: ["Feature 1", "Feature 2", "Feature 3", "Feature 4"]')),
                ('cta_button_text', models.CharField(default='Learn More', help_text='Text on the action button', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='1=first, 2=second, 3=third. Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this service from the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Service',
                'verbose_name_plural': 'Legal Services',
                'ordering': ['order'],
            },
        ),
    ]
