# Generated by Django 5.2.11 on 2026-03-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_scholarship_options_remove_scholarship_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingCourse',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount_currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('KES', 'Kenyan Shilling (Ksh)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount_description',
            field=models.CharField(blank=True, help_text="E.g., 'Full tuition', 'Partial funding', etc.", max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='field',
            field=models.CharField(choices=[('STEM', 'STEM'), ('Humanities', 'Humanities'), ('Business', 'Business'), ('Arts', 'Arts')], default='STEM', max_length=100),
        ),
    ]
