# Generated by Django 3.2.6 on 2025-11-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_emergencyhelpactivation_emergencyhelpactivations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergencyHotline',
            new_name='EmergencyHotlines',
        ),
    ]
