# Generated by Django 3.2.6 on 2026-01-17 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_governance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
