# Generated by Django 3.2.6 on 2025-09-22 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_galleryimage_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the donor.', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the donor.', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount donated.', max_digits=10)),
                ('donation_type', models.CharField(choices=[('One-Time', 'One-Time'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One-Time', help_text='Type of donation.', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from the donor.', null=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the donation was made.')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Flag to indicate if the donor wants to remain anonymous.')),
                ('user', models.ForeignKey(blank=True, help_text='The user who made the donation (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
