# Generated by Django 5.2.11 on 2026-03-01 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_consularassistancepage_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Governance', 'verbose_name_plural': 'Governance Records'},
        ),
        migrations.AlterField(
            model_name='governance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='governance',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='governance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
