# Generated by Django 3.2.6 on 2026-02-21 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20260221_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airecommendationrule',
            options={'verbose_name': 'AI Recommendation Rule', 'verbose_name_plural': 'AI Recommendation Rules'},
        ),
        migrations.AlterModelOptions(
            name='expertinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expert Inquiry', 'verbose_name_plural': 'Expert Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='insuranceplan',
            options={'ordering': ['display_order', '-score'], 'verbose_name': 'Insurance Plan', 'verbose_name_plural': 'Insurance Plans'},
        ),
        migrations.AddField(
            model_name='airecommendationrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airecommendationrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
