# Generated by Django 3.2.6 on 2026-01-06 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_emergencyhotline_emergencyhotlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('application_assistance', 'Application Assistance and Review'), ('translation', 'Translation Services'), ('document_review', 'Document Review and Authentication'), ('registration_support', 'Birth/Death Certificate Registration Support')], max_length=50)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='document_services/')),
                ('message', models.TextField(help_text='Describe your specific needs or issues.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
