# Generated by Django 3.2.6 on 2025-10-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_donation_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hero', 'Hero'), ('services', 'Services'), ('insurance', 'Insurance')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='healthcare/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
