# Generated by Django 3.2.6 on 2025-09-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_donation_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation_organisation',
            old_name='donated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='donation_organisation',
            old_name='name',
            new_name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donation_organisation',
            name='donation_type',
        ),
        migrations.RemoveField(
            model_name='donation_organisation',
            name='is_anonymous',
        ),
    ]
