# Generated by Django 3.2.6 on 2026-01-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_emergencyhotline_emergencyhotlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('document_type', models.CharField(choices=[('birth', 'Birth Certificate'), ('marriage', 'Marriage Certificate'), ('police_clearance', 'Police Clearanc (Good Conduct)'), ('legalization', 'Legalization/Apostille (MFA)'), ('notarization', 'Notarization/Oath Commissioner'), ('other', 'Other/Custom')], max_length=50)),
                ('package_type', models.CharField(choices=[('standard', 'Standard ($99)'), ('premium', 'Premium ($249)'), ('diplomatic', 'Diplomatic ($399)')], max_length=50)),
                ('destination_country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('processing', 'Processing'), ('completed', 'Completed')], default='Pending', max_length=50)),
            ],
        ),
    ]
