# Generated by Django 3.2.6 on 2025-11-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_emergencyhotline_emergencyhotlines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergencyHotlines',
            new_name='EmergencyHot',
        ),
    ]
