# Generated by Django 5.2.11 on 2026-03-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_governance_options_alter_governance_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertinquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Agent assigned to this inquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='escalated',
            field=models.BooleanField(default=False, help_text='Whether this inquiry has been escalated'),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='first_response_time',
            field=models.DateTimeField(blank=True, help_text='When this inquiry was first responded to', null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='resolution_time',
            field=models.DateTimeField(blank=True, help_text='When this inquiry was resolved', null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='SLA deadline based on priority', null=True),
        ),
    ]
