# Generated by Django 5.2.7 on 2025-10-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coda'),
    ]

    operations = [
        migrations.CreateModel(
            name='WCAGStandardWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('app_name', models.CharField(blank=True, max_length=500, null=True)),
                ('page_name', models.TextField(blank=True, null=True)),
                ('website_url', models.FileField(blank=True, null=True, upload_to='websites/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='coda',
        ),
    ]
