# Generated by Django 5.2.11 on 2026-03-21 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_trainingcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcourse',
            options={'ordering': ['start_date'], 'verbose_name': 'Training Course', 'verbose_name_plural': 'Training Courses'},
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='certificate_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='course_code',
            field=models.CharField(blank=True, help_text='e.g., CS101', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='description',
            field=models.TextField(blank=True, help_text='Brief course description'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional: Course end date', null=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='enrolled_students',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='instructor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum capacity', null=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Required knowledge or courses'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Upcoming', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Course outline/syllabus'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Business', 'Business'), ('Art', 'Art'), ('Health', 'Health')], default='Tech', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='duration',
            field=models.CharField(default='Self-paced', help_text="e.g., '6 weeks', '3 months', 'Self-paced'", max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='enrollment',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Closing Soon', 'Closing Soon')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='format',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['status'], name='main_traini_status_270f78_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['category'], name='main_traini_categor_55bb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['start_date'], name='main_traini_start_d_b2d316_idx'),
        ),
    ]
