# Generated by Django 5.2.12 on 2026-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_donation_alter_opportunity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
