# Generated by Django 5.2.7 on 2026-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_documentationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentationrequest",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("birth", "Birth Certificate"),
                    ("marriage", "Marriage Certificate"),
                    ("police_clearance", "Police Clearance (Good Conduct)"),
                    ("legalization", "Legalization/Apostille (MFA)"),
                    ("notarization", "Notarization/Oath Commissioner"),
                    ("other", "Other/Custom"),
                ],
                max_length=50,
            ),
        ),
    ]
