# Generated by Django 3.2.6 on 2025-04-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_galleryimage2_volunteer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage2',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
