# Generated by Django 3.2.6 on 2025-11-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_safetyalertsubscription'),
        ('main', '0004_emergencyhelpactivation_emergencyhotline_staffcontact'),
    ]

    operations = [
    ]
