# Generated by Django 3.2.6 on 2025-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_emergencyhotlines_emergencyhot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('testimonial', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Testimonial/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
