# Generated by Django 5.2.11 on 2026-03-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_trainingcourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertinquiry',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='consultation_type',
            field=models.CharField(blank=True, choices=[('Legal & Immigration', 'Legal & Immigration'), ('Documentation', 'Documentation'), ('Property & Estate', 'Property & Estate'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='location',
            field=models.CharField(blank=True, help_text="Client's location/country", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Swahili', 'Swahili'), ('French', 'French'), ('Spanish', 'Spanish'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expertinquiry',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Not Urgent', 'Not Urgent'), ('Moderately Urgent', 'Moderately Urgent (within 3-5 days)'), ('Very Urgent', 'Very Urgent (within 24-48 hours)'), ('Emergency', 'Emergency (immediate assistance needed)')], max_length=50, null=True),
        ),
    ]
