# Generated by Django 3.2.6 on 2025-11-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20251112_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='created_at',
        ),
    ]
