# Generated by Django 3.2.6 on 2025-09-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactmessage',
        ),
    ]
