# Generated by Django 5.2.7 on 2026-01-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_documentationrequest_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentationrequest",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard ($99)"),
                    ("premium", "Premium ($249)"),
                    ("diplomatic", "Diplomatic ($399)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
