# Generated by Django 5.2.12 on 2026-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_donation_stripe_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='volunteers/photos/')),
                ('availability', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Occasional', 'Occasional')], max_length=20)),
                ('available_days', models.CharField(max_length=200)),
                ('hours_per_week', models.IntegerField()),
                ('skills', models.TextField()),
                ('interests', models.TextField()),
                ('territory', models.CharField(max_length=150)),
                ('is_remote', models.BooleanField(default=False)),
                ('motivation', models.TextField()),
                ('experience', models.TextField(blank=True)),
                ('impact_goal', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='volunteers/cv/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='volunteers/id/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='volunteers/certificates/')),
                ('role', models.CharField(choices=[('Field volunteer', 'Field volunteer'), ('Online volunteer', 'Online volunteer'), ('Event volunteer', 'Event volunteer'), ('Team leader', 'Team leader'), ('Trainer / Mentor', 'Trainer / Mentor'), ('Fundraising ambassador', 'Fundraising ambassador')], max_length=100)),
                ('emergency_name', models.CharField(max_length=200)),
                ('emergency_relationship', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('receive_updates', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
