# Generated by Django 3.2.6 on 2025-10-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20251017_1430'),
        ('main', '0005_contactmessage'),
    ]

    operations = [
    ]
