# Generated by Django 5.2.11 on 2026-03-25 13:06
# This migration is now a no-op - all models were already created in 0001_initial.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        # All models (Category, Subscriber, NewsArticle) already exist in 0001_initial.py
        # This migration file is kept for migration history consistency
    ]
