# Generated by Django 3.2.6 on 2025-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_0005_auto_20251017_1430_0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Vocational', 'Vocational')], max_length=200)),
                ('field', models.CharField(choices=[('STEM', 'STEM'), ('Humanities', 'Humanities'), ('Business', 'Business'), ('Arts', 'Arts')], max_length=200)),
                ('location', models.CharField(choices=[('Kenya', 'Kenya'), ('Global', 'Global'), ('UK', 'UK'), ('USA', 'USA')], max_length=200)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closing Soon', 'Closing Soon'), ('Closed', 'Closed')], max_length=20)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
