# Generated by Django 5.2.12 on 2026-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Beneficiary', 'Beneficiary'), ('Partner', 'Partner'), ('Visitor', 'Visitor')], max_length=20)),
                ('category', models.CharField(choices=[('Technical problem', 'Technical problem'), ('Volunteer support', 'Volunteer support'), ('Donation issue', 'Donation issue'), ('Report a problem', 'Report a problem'), ('Partnership inquiry', 'Partnership inquiry'), ('Mental/Community support', 'Mental/Community support'), ('Emergency assistance', 'Emergency assistance'), ('Other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
