# Generated by Django 5.2.11 on 2026-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expertinquiry_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name': 'News Item', 'verbose_name_plural': 'News Items'},
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='DC48K News Team', max_length=150),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('press', 'Press Release'), ('embassy', 'Embassy & Government News'), ('community', 'Community Update'), ('other', 'Other News')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for news lists', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show at top of news list'),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
