# Generated by Django 3.2.6 on 2026-01-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expertservicerequest_globalsetting_testimonial'),
        ('main', '0006_populate_initial_data'),
    ]

    operations = [
    ]
