# Generated by Django 3.2.6 on 2025-09-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationorganisation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
    ]
