# Generated by Django 3.2.6 on 2026-01-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20260107_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='service',
            name='cta_link',
            field=models.CharField(default='#', help_text='URL name or path for the button', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_text',
            field=models.CharField(default='Learn More', help_text='Text for the call-to-action button', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text="Unique ID for anchors (e.g. 'consular', 'financial')", null=True),
        ),
    ]
