# Generated by Django 3.2.6 on 2026-02-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_governance_created_at'),
        ('main', '0007_consularassistancepage'),
    ]

    operations = [
    ]
