# Generated by Django 5.2.11 on 2026-03-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_communitymember_eventcalendar_forumcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('individual', 'Individual'), ('leader', 'Leader'), ('organization', 'Organization')], max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Membership Registrations',
                'ordering': ['-registration_date'],
            },
        ),
    ]
