# Generated by Django 3.2.6 on 2026-01-07 12:13

from django.db import migrations
from django.conf import settings
import os
import shutil

def populate_services(apps, schema_editor):
    Service = apps.get_model('main', 'Service')
    SubService = apps.get_model('main', 'SubService')
    
    # Define source for static images
    # BASE_DIR is two levels up from 'main' app
    BASE_DIR = settings.BASE_DIR
    STATIC_IMG_DIR = os.path.join(BASE_DIR, 'main', 'static', 'main', 'img')
    MEDIA_SERVICES_DIR = os.path.join(settings.MEDIA_ROOT, 'services')
    
    if not os.path.exists(MEDIA_SERVICES_DIR):
        os.makedirs(MEDIA_SERVICES_DIR)

    services_data = [
        {
            "title": "Consular Assistance",
            "description": "After losing her passport in a foreign country, Jane Matiko struggled to find a way home. Jane received DC48K consular support, helping navigate the bureaucratic maze and expediting her return.",
            "image_filename": "consularAssistance.png",
            "slug": "consular",
            "cta_text": "Contact Our Experts",
            "cta_link": "#", # Opens Modal
            "bullets": [
                "Emergency Travel Documents",
                "Legal Aid and Referrals",
                "Notarization Services",
                "Assistance in Case of Arrest or Detention"
            ]
        },
        {
            "title": "Document Services/preparation",
            "description": "Otieno was facing hurdles in finalizing his immigration document. Document Services/Preparation provided invaluable assistance in compiling, reviewing, and completing his application to ensure accuracy and compliance.",
            "image_filename": "documentServicespreparation.png",
            "slug": "documents",
            "cta_text": "Get Assistance",
            "cta_link": "main:document_services",
            "bullets": [
                "Application Assistance and Review",
                "Translation Services",
                "Document Review and Authentication",
                "Birth/Death Certificate Registration Support"
            ]
        },
        {
            "title": "Healthcare Information",
            "description": "Recovering from an illness abroad, Brian Omondi utilized Healthcare Information services to understand his options and find a suitable, vetted doctor for his specific treatment needs in a foreign system.",
            "image_filename": "healthcareproviders.png",
            "slug": "healthcare",
            "cta_text": "Find Healthcare Providers",
            "cta_link": "#",
            "bullets": [
                "Medical Referrals and Vetting",
                "Insurance Guidance and Enrollment Support",
                "Health Seminars and Wellness Programs",
                "Mental Health Resource Access"
            ]
        },
        {
            "title": "Financial Services",
            "description": "Peter was advised on safer investment strategies through Financial Services after an initial venture failed. We help members secure their hard-earned assets and plan for long-term financial stability.",
            "image_filename": "financialserices.png",
            "slug": "financial",
            "cta_text": "Start Financial Planning",
            "cta_link": "finance:planning_list",
            "bullets": [
                "Investment Advice and Planning",
                "Currency Exchange Information",
                "Reliable Remittance Assistance",
                "Tax and Compliance Guidance"
            ]
        },
        {
            "title": "Community Support",
            "description": "Moving to a new city can be isolating. Our Community Support programs ensure you have immediate connections and access to cultural events that make you feel at home, fostering a strong sense of belonging.",
            "image_filename": "communitysupport.png",
            "slug": "community",
            "cta_text": "Join the Community",
            "cta_link": "home", # /communities/
            "bullets": [
                "Cultural Events and Festivals",
                "Wellness and Counseling Programs",
                "Social Networking Meetups (Local Chapters)",
                "Newcomer Orientation Assistance"
            ]
        },
        {
            "title": "Crisis Management",
            "description": "During natural disasters or civil unrest, rapid, reliable information is key. Our 24/7 Crisis Management team provides real-time alerts, necessary evacuation guidance, and emergency communication channels.",
            "image_filename": "crisismanagement.png",
            "slug": "crisis",
            "cta_text": "Contact Our Crisis Team",
            "cta_link": "main:crisis_page",
            "bullets": [
                "24/7 Emergency Hotline Access",
                "Real-time Security and Safety Alerts",
                "Emergency Planning and Evacuation Guidance",
                "Disaster Relief Coordination"
            ]
        },
        {
            "title": "Education and Training",
            "description": "Mercy used our Education and Training services to find accredited online courses and career mentorship tailored for the diaspora market, helping her upskill for a major career promotion.",
            "image_filename": "educationandtraining.png",
            "slug": "education",
            "cta_text": "Explore Educational Opportunities",
            "cta_link": "main:education_landing",
            "bullets": [
                "Scholarship Guidance and Application Support",
                "Professional Development Workshops",
                "Skills Training and Certification Resources",
                "Career Mentorship Programs"
            ]
        }
    ]

    for idx, data in enumerate(services_data, start=1):
        # Handle Image Copy
        src_path = os.path.join(STATIC_IMG_DIR, data['image_filename'])
        dst_filename = f"service_{data['slug']}_{data['image_filename']}"
        dst_path = os.path.join(MEDIA_SERVICES_DIR, dst_filename)
        
        image_rel_path = f"services/{dst_filename}"
        
        if os.path.exists(src_path):
            shutil.copy2(src_path, dst_path)
        else:
            print(f"Warning: Image not found at {src_path}")
            image_rel_path = None # Or keep null

        service, created = Service.objects.get_or_create(
            title=data['title'],
            defaults={
                'description': data['description'],
                'image': image_rel_path,
                'slug': data['slug'],
                'ordering': idx,
                'cta_text': data['cta_text'],
                'cta_link': data['cta_link']
            }
        )
        
        # Populate Bullet Points
        if created or service:
            # clear old subservices if re-running
            # SubService.objects.filter(service=service).delete()
            for bullet in data['bullets']:
                SubService.objects.get_or_create(
                    service=service,
                    title=bullet,
                    defaults={'description': ''} 
                )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20260107_1413'),
    ]

    operations = [
        migrations.RunPython(populate_services),
    ]
