# Generated manually to merge conflicting migrations
# Generated by Django 3.2.6 on 2025-11-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_scholarship_trainingcourse'),
        ('main', '0008_scholarship_amount'),
    ]

    operations = [
        # Empty merge migration - merges two parallel branches:
        # Branch 1: Creates TrainingCourse model
        # Branch 2: Creates Scholarship model and adds amount field
        # Both branches are compatible and can be merged
    ]

