# Generated by Django 5.2.11 on 2026-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_subscriber_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('visa', 'Visa and Residency Services'), ('citizenship', 'Citizenship and Naturalization'), ('legal_referral', 'Legal Representation & Referrals')], max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('features', models.JSONField(default=list)),
                ('cta_button_text', models.CharField(default='Learn More', max_length=100)),
                ('cta_button_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Service',
                'verbose_name_plural': 'Legal Services',
                'ordering': ['order'],
            },
        ),
    ]
