# Generated by Django 3.2.6 on 2026-01-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20260107_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cta_link',
            field=models.CharField(blank=True, default='#', help_text='URL name or path for the button', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cta_text',
            field=models.CharField(blank=True, default='Learn More', help_text='Text for the call-to-action button', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
