# Generated by Django 3.2.6 on 2026-01-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_governance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
