# Generated by Django 5.2.11 on 2026-05-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_department_legalservice_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalservice',
            options={'ordering': ['order'], 'verbose_name': 'Legal Service', 'verbose_name_plural': 'Legal Services'},
        ),
    ]
