# Generated by Django 3.2.6 on 2026-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20260107_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
