# Generated by Django 5.2.11 on 2026-03-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_legalservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name_plural': 'Subscribers'},
        ),
    ]
