# Generated by Django 5.2.11 on 2026-03-27 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20260326_1652'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentp',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentp',
            name='post',
        ),
        migrations.RemoveField(
            model_name='directoryprofile',
            name='community_member',
        ),
        migrations.DeleteModel(
            name='EventCalendar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='MembershipRegistration',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RemoveField(
            model_name='expertinquiry',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='expertinquiry',
            name='consultation_type',
        ),
        migrations.RemoveField(
            model_name='expertinquiry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='expertinquiry',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='expertinquiry',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='CommentP',
        ),
        migrations.DeleteModel(
            name='CommunityMember',
        ),
        migrations.DeleteModel(
            name='DirectoryProfile',
        ),
        migrations.DeleteModel(
            name='ForumCategory',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
