# Generated by Django 3.2.6 on 2026-01-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_documentationrequest_package_type'),
        ('main', '0011_alter_subservice_description'),
    ]

    operations = [
    ]
