# Generated by Django 3.2.6 on 2026-01-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_emergencyhotlines_emergencyhot'),
        ('main', '0012_merge_20260113_1920'),
    ]

    operations = [
    ]
