"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')  # Required - no default for security

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Add Heroku domain if deployed
if 'HEROKU_APP_NAME' in os.environ:
    ALLOWED_HOSTS.append(f"{os.environ['HEROKU_APP_NAME']}.herokuapp.com")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth

    # Third-party apps
    'social_django',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Local apps
    'accounts',
    'payments',
    'marketplace',
]

# Site ID for django.contrib.sites
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Heroku PostgreSQL configuration
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Local development database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='biashara_bridges'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication backends
# Use custom backend for case-insensitive username/email authentication
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',       # Google OAuth2
    'social_core.backends.facebook.FacebookOAuth2',   # Facebook OAuth2
    'accounts.backends.CaseInsensitiveAuthBackend',   # Custom case-insensitive backend
    'django.contrib.auth.backends.ModelBackend',      # Fallback to default backend
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# ============================================================================
# EMAIL SETTINGS
# ============================================================================

# Email Backend Configuration
# For development, use console backend (prints emails to console)
# For production, use SMTP backend
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')

# SMTP Configuration (for production)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@biasharabridges.com')
SERVER_EMAIL = config('SERVER_EMAIL', default='server@biasharabridges.com')

# Email verification settings
EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Link expires after 3 days
EMAIL_SUBJECT_PREFIX = '[Biashara Bridges] '

# ============================================================================
# DJANGO-ALLAUTH CONFIGURATION
# ============================================================================

# Authentication settings
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Allow login with username or email
ACCOUNT_EMAIL_REQUIRED = True  # Email is required for registration
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Email verification is mandatory
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # Confirm email on GET request
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False  # Don't auto-login after email confirmation
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Confirmation link expires after 3 days
ACCOUNT_UNIQUE_EMAIL = True  # Email must be unique

# Login/Logout settings
ACCOUNT_LOGIN_ON_PASSWORD_RESET = False  # Don't auto-login after password reset
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False  # Don't auto-logout after password change
ACCOUNT_LOGOUT_REDIRECT_URL = 'login'

# Registration settings
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True  # User must enter password twice

# Email settings for allauth
ACCOUNT_EMAIL_SUBJECT_PREFIX = EMAIL_SUBJECT_PREFIX
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if not DEBUG else 'http'

# Session settings
ACCOUNT_SESSION_REMEMBER = True  # Remember me by default

# Custom adapter
ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'

# Allauth forms
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
}

# ============================================================================
# PAYMENT GATEWAY SETTINGS
# ============================================================================

# Stripe Configuration
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# PayPal Configuration
PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')
PAYPAL_MODE = config('PAYPAL_MODE', default='sandbox')  # 'sandbox' or 'live'
PAYPAL_IPN_URL = 'https://ipnpb.sandbox.paypal.com/cgi-bin/webscr' if config('PAYPAL_MODE', default='sandbox') == 'sandbox' else 'https://ipnpb.paypal.com/cgi-bin/webscr'

# M-Pesa Configuration (Safaricom - Kenya)
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')
MPESA_BUSINESS_SHORTCODE = config('MPESA_BUSINESS_SHORTCODE', default='')
MPESA_PASSKEY = config('MPESA_PASSKEY', default='')
MPESA_CALLBACK_URL = config('MPESA_CALLBACK_URL', default='')
MPESA_INITIATOR_NAME = config('MPESA_INITIATOR_NAME', default='')
MPESA_SECURITY_CREDENTIAL = config('MPESA_SECURITY_CREDENTIAL', default='')

# CashApp Configuration (Square)
CASHAPP_APP_ID = config('CASHAPP_APP_ID', default='')
CASHAPP_CLIENT_ID = config('CASHAPP_CLIENT_ID', default='')
CASHAPP_CLIENT_SECRET = config('CASHAPP_CLIENT_SECRET', default='')
CASHAPP_ACCESS_TOKEN = config('CASHAPP_ACCESS_TOKEN', default='')
CASHAPP_LOCATION_ID = config('CASHAPP_LOCATION_ID', default='')

# Venmo Configuration (Braintree)
VENMO_MERCHANT_ID = config('VENMO_MERCHANT_ID', default='')
VENMO_PUBLIC_KEY = config('VENMO_PUBLIC_KEY', default='')
VENMO_PRIVATE_KEY = config('VENMO_PRIVATE_KEY', default='')

# Payment Settings
PAYMENT_CURRENCY = 'USD'
# Payment Currency
DEFAULT_CURRENCY = "USD"

MINIMUM_DEPOSIT_AMOUNT = 1.00  # Minimum amount users can deposit
MAXIMUM_DEPOSIT_AMOUNT = 10000.00  # Maximum amount per transaction
MINIMUM_WALLET_BALANCE = 0.00  # Minimum wallet balance allowed

# Webhook URLs (for production, use full domain)
STRIPE_WEBHOOK_URL = config('STRIPE_WEBHOOK_URL', default='/webhooks/stripe/')
PAYPAL_WEBHOOK_URL = config('PAYPAL_WEBHOOK_URL', default='/webhooks/paypal/')
MPESA_WEBHOOK_URL = config('MPESA_WEBHOOK_URL', default='/webhooks/mpesa/')
CASHAPP_WEBHOOK_URL = config('CASHAPP_WEBHOOK_URL', default='/webhooks/cashapp/')
VENMO_WEBHOOK_URL = config('VENMO_WEBHOOK_URL', default='/webhooks/venmo/')

# Payment Gateway Feature Flags
ENABLE_STRIPE = config('ENABLE_STRIPE', default=True, cast=bool)
ENABLE_PAYPAL = config('ENABLE_PAYPAL', default=True, cast=bool)
ENABLE_MPESA = config('ENABLE_MPESA', default=True, cast=bool)
ENABLE_CASHAPP = config('ENABLE_CASHAPP', default=True, cast=bool)
ENABLE_VENMO = config('ENABLE_VENMO', default=True, cast=bool)
ENABLE_WALLET_PAYMENTS = config('ENABLE_WALLET_PAYMENTS', default=True, cast=bool)

# Transaction Settings
TRANSACTION_TIMEOUT_SECONDS = 300  # 5 minutes timeout for pending transactions
AUTO_CANCEL_PENDING_INVOICES_DAYS = 7  # Auto-cancel unpaid invoices after 7 days

# Security Settings for API Keys Encryption
PAYMENT_ENCRYPTION_KEY = config('PAYMENT_ENCRYPTION_KEY', default='')  # Fernet encryption key

# Static files configuration for Heroku with WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Celery Configuration
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# ============================================================================
# SOCIAL AUTHENTICATION SETTINGS
# ============================================================================

# Google OAuth2 Configuration
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_OAUTH2_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_OAUTH2_CLIENT_SECRET', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['first_name', 'last_name', 'picture']

# Facebook OAuth2 Configuration
SOCIAL_AUTH_FACEBOOK_KEY = config('FACEBOOK_APP_ID', default='')
SOCIAL_AUTH_FACEBOOK_SECRET = config('FACEBOOK_APP_SECRET', default='')
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'public_profile']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email,picture.type(large),first_name,last_name'
}
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [
    ('first_name', 'first_name'),
    ('last_name', 'last_name'),
    ('email', 'email'),
    ('picture', 'picture'),
]

# Social Auth General Settings
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/edit-profile/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Pipeline for social authentication
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'accounts.pipeline.create_user_profile',  # Custom pipeline to create UserProfile
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

# Production Security Settings
# Only enforce in production (when DEBUG is False)
if not DEBUG:
    # HTTPS/SSL Settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS (HTTP Strict Transport Security) Settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Additional Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
