"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-v!+8q*b!_lu)ef@!2-y8amu5m8t+9x0cp_p@%se9ry09y6u8xr')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'accounts',
    'payments',
    'marketplace',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='biashara_bridges'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Allow using SQLite for local development (default for easier setup).
# Set USE_POSTGRESQL=True in environment to use PostgreSQL instead.
DB_ENGINE = config('DB_ENGINE', default='sqlite')
USE_SQLITE_DEV = config('USE_SQLITE_DEV', default=True, cast=bool)
USE_POSTGRESQL = config('USE_POSTGRESQL', default=False, cast=bool)
if not USE_POSTGRESQL and (isinstance(DB_ENGINE, str) and DB_ENGINE.lower() in ('sqlite', 'sqlite3') or USE_SQLITE_DEV):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication backends
# Use custom backend for case-insensitive username/email authentication
AUTHENTICATION_BACKENDS = [
    'accounts.backends.CaseInsensitiveAuthBackend',  # Custom case-insensitive backend
    'django.contrib.auth.backends.ModelBackend',     # Fallback to default backend
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Email settings (for password reset)
# For development, use console backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production, use SMTP (uncomment and configure)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
# EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@biasharabridges.com')

# ============================================================================
# PAYMENT GATEWAY SETTINGS
# ============================================================================

# Stripe Configuration
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# PayPal Configuration
PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')
PAYPAL_MODE = config('PAYPAL_MODE', default='sandbox')  # 'sandbox' or 'live'

# M-Pesa Configuration (Safaricom - Kenya)
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')
MPESA_BUSINESS_SHORTCODE = config('MPESA_BUSINESS_SHORTCODE', default='')
MPESA_PASSKEY = config('MPESA_PASSKEY', default='')
MPESA_CALLBACK_URL = config('MPESA_CALLBACK_URL', default='')
MPESA_INITIATOR_NAME = config('MPESA_INITIATOR_NAME', default='')
MPESA_SECURITY_CREDENTIAL = config('MPESA_SECURITY_CREDENTIAL', default='')

# Payment Settings
PAYMENT_CURRENCY = 'USD'
# Payment Currency
DEFAULT_CURRENCY = "USD"

MINIMUM_DEPOSIT_AMOUNT = 1.00  # Minimum amount users can deposit
MAXIMUM_DEPOSIT_AMOUNT = 10000.00  # Maximum amount per transaction
MINIMUM_WALLET_BALANCE = 0.00  # Minimum wallet balance allowed

# Webhook URLs (for production, use full domain)
STRIPE_WEBHOOK_URL = config('STRIPE_WEBHOOK_URL', default='/webhooks/stripe/')
PAYPAL_WEBHOOK_URL = config('PAYPAL_WEBHOOK_URL', default='/webhooks/paypal/')
MPESA_WEBHOOK_URL = config('MPESA_WEBHOOK_URL', default='/webhooks/mpesa/')

# Payment Gateway Feature Flags
ENABLE_STRIPE = config('ENABLE_STRIPE', default=True, cast=bool)
ENABLE_PAYPAL = config('ENABLE_PAYPAL', default=True, cast=bool)
ENABLE_MPESA = config('ENABLE_MPESA', default=True, cast=bool)
ENABLE_WALLET_PAYMENTS = config('ENABLE_WALLET_PAYMENTS', default=True, cast=bool)

# Transaction Settings
TRANSACTION_TIMEOUT_SECONDS = 300  # 5 minutes timeout for pending transactions
AUTO_CANCEL_PENDING_INVOICES_DAYS = 7  # Auto-cancel unpaid invoices after 7 days

# Security Settings for API Keys Encryption
PAYMENT_ENCRYPTION_KEY = config('PAYMENT_ENCRYPTION_KEY', default='')  # Fernet encryption key

# ============================================================================
# SECURITY SETTINGS (Production)
# ============================================================================
# These settings are enforced in production (when DEBUG=False)

if not DEBUG:
    # HTTPS/SSL Security
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HTTP Strict Transport Security (HSTS)
    # Start with a low value and increase once confirmed working
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Additional Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True  # Deprecated but still useful for older browsers
    X_FRAME_OPTIONS = 'DENY'
    
    # Content Security Policy (optional - uncomment if needed)
    # CSP_DEFAULT_SRC = ("'self'",)
    # CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
    # CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'")
    # CSP_IMG_SRC = ("'self'", "data:", "https:")
    # CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")
    
    # Session Security
    SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False
    SESSION_SAVE_EVERY_REQUEST = True

# Development-specific relaxed settings
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ============================================================================
# FILE UPLOAD SECURITY
# ============================================================================
# Allowed file extensions and max file sizes

# Document uploads (resumes, business profiles)
ALLOWED_DOCUMENT_EXTENSIONS = ['.pdf', '.doc', '.docx']
MAX_DOCUMENT_SIZE_MB = 10  # 10 MB max

# Image uploads (profile pictures)
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']
MAX_IMAGE_SIZE_MB = 5  # 5 MB max

# General file upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# ============================================================================
# LOGGING (Security-aware)
# ============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'verbose',
        } if not DEBUG else {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['console'] if DEBUG else ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'payments': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
