# Generated by Django 4.2.27 on 2026-01-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_credentials", "Invalid Credentials"),
                            ("account_disabled", "Account Disabled"),
                            ("account_locked", "Account Locked"),
                            ("mfa_required", "MFA Required"),
                            ("mfa_failed", "MFA Failed"),
                            ("rate_limited", "Rate Limited"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique device identifier hash",
                        max_length=64,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, help_text="desktop, mobile, tablet, etc.", max_length=50
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=100)),
                (
                    "os",
                    models.CharField(blank=True, max_length=100, verbose_name="Operating System"),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                (
                    "risk_score",
                    models.IntegerField(default=0, help_text="Risk score 0-100, higher is riskier"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("attempted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login History",
                "verbose_name_plural": "Login Histories",
                "db_table": "login_history",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(fields=["-attempted_at"], name="login_histo_attempt_f43419_idx"),
                    models.Index(
                        fields=["user", "-attempted_at"], name="login_histo_user_id_e7ce08_idx"
                    ),
                    models.Index(
                        fields=["username", "-attempted_at"], name="login_histo_usernam_9806fb_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "-attempted_at"],
                        name="login_histo_ip_addr_c22786_idx",
                    ),
                    models.Index(
                        fields=["status", "-attempted_at"], name="login_histo_status_b98e4d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Successful"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("password_changed", "Password Changed"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("password_reset_completed", "Password Reset Completed"),
                            ("mfa_enabled", "MFA Enabled"),
                            ("mfa_disabled", "MFA Disabled"),
                            ("mfa_verified", "MFA Verified"),
                            ("mfa_failed", "MFA Verification Failed"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("user_activated", "User Activated"),
                            ("user_deactivated", "User Deactivated"),
                            ("profile_updated", "Profile Updated"),
                            ("profile_viewed", "Profile Viewed"),
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_refunded", "Payment Refunded"),
                            ("subscription_created", "Subscription Created"),
                            ("subscription_renewed", "Subscription Renewed"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            ("subscription_expired", "Subscription Expired"),
                            ("data_exported", "Data Exported"),
                            ("data_deleted", "Data Deleted"),
                            ("consent_given", "Consent Given"),
                            ("consent_withdrawn", "Consent Withdrawn"),
                            ("suspicious_activity", "Suspicious Activity Detected"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("permission_changed", "Permission Changed"),
                            ("admin_action", "Admin Action"),
                            ("system_error", "System Error"),
                            ("api_access", "API Access"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Human-readable description of the event"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username at time of event (preserved even if user deleted)",
                        max_length=150,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ("user_agent", models.TextField(blank=True, help_text="Browser/client user agent")),
                (
                    "request_method",
                    models.CharField(blank=True, help_text="HTTP method", max_length=10),
                ),
                (
                    "request_path",
                    models.CharField(blank=True, help_text="Request URL path", max_length=500),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data (old/new values, error details, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_audit_log", "Can view audit logs"),
                    ("export_audit_log", "Can export audit logs"),
                ],
                "indexes": [
                    models.Index(fields=["-created_at"], name="audit_log_created_e49a79_idx"),
                    models.Index(
                        fields=["user", "-created_at"], name="audit_log_user_id_b57afc_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"], name="audit_log_event_t_ae55c9_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"], name="audit_log_ip_addr_05a107_idx"
                    ),
                ],
            },
        ),
    ]
