"""
Canonical Activity Catalog.

This module defines the single source of truth for canonical ActivityTypes.
Each entry represents a standardized activity that should exist in the system.
"""

from decimal import Decimal
from typing import List, Dict, Any

# Canonical activities list - single source of truth
# Each entry should have: slug, name, department_code, category_code, subcategory_code,
# unit_type, unit_rate, monthly_target_units, points_per_unit, is_billable
CANONICAL_ACTIVITIES: List[Dict[str, Any]] = [
    {
        "slug": "DAILY_UPDATE_SESSION",
        "name": "Daily Update Session",
        "department_code": "MANAGEMENT",
        "category_code": "MEETINGS_SESSIONS",
        "subcategory_code": "DAILY_UPDATES",
        "unit_type": "month",
        "unit_rate": Decimal("1000.00"),
        "monthly_target_units": 1,
        "points_per_unit": Decimal("11.00"),
        "is_billable": False,
        "description": "Daily team update session (was generic 'General Meeting')",
    },
    {
        "slug": "CLIENT_TRAINING_PREP_SESSION",
        "name": "Client Training Preparation Session",
        "department_code": "MANAGEMENT",
        "category_code": "TRAINING_COACHING",
        "subcategory_code": "CLIENT_TRAINING",
        "unit_type": "session",
        "unit_rate": Decimal("250.00"),
        "monthly_target_units": 8,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "BI training prep session",
    },
    {
        "slug": "CLIENT_TRAINING_SESSION",
        "name": "Client Training Session",
        "department_code": "IT",
        "category_code": "TRAINING_COACHING",
        "subcategory_code": "CLIENT_TRAINING",
        "unit_type": "hour",
        "unit_rate": Decimal("1000.00"),
        "monthly_target_units": 16,
        "points_per_unit": Decimal("2.50"),
        "is_billable": True,
        "description": "Client-facing training session",
    },
    {
        "slug": "SELF_TRAINING_SESSION",
        "name": "Self-Training Session",
        "department_code": "MANAGEMENT",
        "category_code": "TRAINING_COACHING",
        "subcategory_code": "INTERNAL_TRAINING",
        "unit_type": "session",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 5,
        "points_per_unit": Decimal("15.00"),
        "is_billable": False,
        "description": "Employee solo training session (was 'One on One')",
    },
    {
        "slug": "INTERNAL_TRAINING_SESSION",
        "name": "Internal Training Session",
        "department_code": "MANAGEMENT",
        "category_code": "TRAINING_COACHING",
        "subcategory_code": "INTERNAL_TRAINING",
        "unit_type": "session",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Internal team training session",
    },
    {
        "slug": "SIMULATION_TRAINING_SESSION",
        "name": "Simulation Training Session",
        "department_code": "IT",
        "category_code": "TRAINING_COACHING",
        "subcategory_code": "INTERNAL_TRAINING",
        "unit_type": "session",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Training simulation session",
    },
    {
        "slug": "CLIENT_JOB_SUPPORT",
        "name": "Client Job Support",
        "department_code": "IT",
        "category_code": "SUPPORT_TROUBLESHOOTING",
        "subcategory_code": "CLIENT_SUPPORT",
        "unit_type": "hour",
        "unit_rate": Decimal("1000.00"),
        "monthly_target_units": 45,
        "points_per_unit": Decimal("2.00"),
        "is_billable": True,
        "description": "Client-facing support (was 'Job Support Session')",
    },
    {
        "slug": "INTERNAL_TECHNICAL_SUPPORT",
        "name": "Internal Technical Support",
        "department_code": "IT",
        "category_code": "SUPPORT_TROUBLESHOOTING",
        "subcategory_code": "INTERNAL_SUPPORT",
        "unit_type": "hour",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 20,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Internal technical support",
    },
    {
        "slug": "DEVELOPER_PROJECT_WORK",
        "name": "Developer Project Work",
        "department_code": "IT",
        "category_code": "DEVELOPMENT_DELIVERY",
        "subcategory_code": "PROJECT_WORK",
        "unit_type": "work_block",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 20,
        "points_per_unit": Decimal("1.00"),
        "is_billable": True,
        "description": "Developer project work (internal or client)",
    },
    {
        "slug": "GENERAL_PROJECT_WORK",
        "name": "General Project Work",
        "department_code": "IT",
        "category_code": "DEVELOPMENT_DELIVERY",
        "subcategory_code": "PROJECT_WORK",
        "unit_type": "work_block",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 15,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Non-dev project work",
    },
    {
        "slug": "EMPLOYEE_DAF_REVIEW",
        "name": "Employee DAF Review",
        "department_code": "MANAGEMENT",
        "category_code": "OVERSIGHT_QUALITY",
        "subcategory_code": "WORK_REVIEW",
        "unit_type": "session",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Employee DAF review session",
    },
    {
        "slug": "CLIENT_ASSIGNMENT_REVIEW",
        "name": "Client Assignment Review",
        "department_code": "MANAGEMENT",
        "category_code": "OVERSIGHT_QUALITY",
        "subcategory_code": "WORK_REVIEW",
        "unit_type": "session",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 2,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Client assignment review",
    },
    {
        "slug": "STRATEGIC_FORESIGHT_WORKSHOP",
        "name": "Strategic Foresight Workshop",
        "department_code": "MANAGEMENT",
        "category_code": "STRATEGIC_PLANNING",
        "subcategory_code": "WORKSHOPS",
        "unit_type": "session",
        "unit_rate": Decimal("1000.00"),
        "monthly_target_units": 1,
        "points_per_unit": Decimal("5.00"),
        "is_billable": False,
        "description": "Board of Governors long-term strategy workshop",
    },
    {
        "slug": "ANNUAL_DEPARTMENT_REPORT_PREP",
        "name": "Annual Department Report Preparation",
        "department_code": "MANAGEMENT",
        "category_code": "REPORTING_DOCUMENTATION",
        "subcategory_code": "REPORTS",
        "unit_type": "month",
        "unit_rate": Decimal("1000.00"),
        "monthly_target_units": 1,
        "points_per_unit": Decimal("10.00"),
        "is_billable": False,
        "description": "Annual department report preparation",
    },
    {
        "slug": "RESEARCH_DEVELOPMENT",
        "name": "Research & Development / Innovation Work",
        "department_code": "IT",
        "category_code": "DEVELOPMENT_DELIVERY",
        "subcategory_code": "RND",
        "unit_type": "work_block",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 10,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Research & Development / Innovation Work",
    },
    {
        "slug": "TEAM_BUILDING_EVENT",
        "name": "Team-Building / General Assembly Event",
        "department_code": "MANAGEMENT",
        "category_code": "TEAM_CULTURE",
        "subcategory_code": "EVENTS",
        "unit_type": "meeting",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 1,
        "points_per_unit": Decimal("2.00"),
        "is_billable": False,
        "description": "Team-building / General Assembly Event",
    },
    {
        "slug": "DEVELOPER_RECRUITMENT",
        "name": "Developer Recruitment",
        "department_code": "HR",
        "category_code": "HR_RECRUITMENT",
        "subcategory_code": "RECRUITMENT",
        "unit_type": "candidate_cycle",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Developer recruitment (was 'Dev Recruitment')",
    },
    {
        "slug": "GENERAL_STAFF_RECRUITMENT",
        "name": "General Staff Recruitment",
        "department_code": "HR",
        "category_code": "HR_RECRUITMENT",
        "subcategory_code": "RECRUITMENT",
        "unit_type": "candidate_cycle",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 2,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "General staff recruitment",
    },
    {
        "slug": "EMPLOYEE_DEVELOPMENT_MEETING",
        "name": "Employee Development Meeting",
        "department_code": "MANAGEMENT",
        "category_code": "TRAINING_COACHING",
        "subcategory_code": "INTERNAL_TRAINING",
        "unit_type": "meeting",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Manager-employee 1:1 development meeting",
    },
    {
        "slug": "FACILITIES_OFFICE_MAINTENANCE",
        "name": "Facilities & Office Maintenance Round",
        "department_code": "MANAGEMENT",
        "category_code": "FACILITIES_ENVIRONMENT",
        "subcategory_code": "MAINTENANCE",
        "unit_type": "item",
        "unit_rate": Decimal("200.00"),
        "monthly_target_units": 10,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Facilities & Office Maintenance Round (was 'Cleaning Round')",
    },
    {
        "slug": "CASHFLOW_UPDATE_RECONCILIATION",
        "name": "Cashflow Update & Reconciliation",
        "department_code": "FINANCE",
        "category_code": "FINANCE_REPORTING",
        "subcategory_code": "RECONCILIATION",
        "unit_type": "session",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Cashflow Update & Reconciliation",
    },
    {
        "slug": "BUDGETING_FORECASTING_SESSION",
        "name": "Budgeting & Forecasting Session",
        "department_code": "FINANCE",
        "category_code": "FINANCE_REPORTING",
        "subcategory_code": "FORECASTING",
        "unit_type": "session",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 2,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Budgeting & Forecasting Session",
    },
    {
        "slug": "VIDEO_EDITING",
        "name": "Video Editing",
        "department_code": "MARKETING",
        "category_code": "MARKETING_CONTENT",
        "subcategory_code": "VIDEO_CONTENT",
        "unit_type": "approved_video",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Video Editing",
    },
    {
        "slug": "MARKETING_CONTENT_CREATION",
        "name": "Marketing Content Creation",
        "department_code": "MARKETING",
        "category_code": "MARKETING_CONTENT",
        "subcategory_code": "CONTENT_CREATION",
        "unit_type": "item",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Marketing Content Creation",
    },
    {
        "slug": "SOCIAL_MEDIA_CONTENT_PUBLISHING",
        "name": "Social Media Content Publishing",
        "department_code": "MARKETING",
        "category_code": "MARKETING_CONTENT",
        "subcategory_code": "PUBLISHING",
        "unit_type": "item",
        "unit_rate": Decimal("200.00"),
        "monthly_target_units": 10,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Social Media Content Publishing (was 'Social Media Content Work')",
    },
    {
        "slug": "SOCIAL_MEDIA_MONITORING_ENGAGEMENT",
        "name": "Social Media Monitoring & Engagement",
        "department_code": "MARKETING",
        "category_code": "MARKETING_CONTENT",
        "subcategory_code": "PUBLISHING",
        "unit_type": "item",
        "unit_rate": Decimal("200.00"),
        "monthly_target_units": 10,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Social Media Monitoring & Engagement",
    },
    {
        "slug": "AGILE_DAILY_STANDUP",
        "name": "Agile Daily Standup",
        "department_code": "IT",
        "category_code": "AGILE_TEAM_RHYTHMS",
        "subcategory_code": "CEREMONIES",
        "unit_type": "meeting",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 20,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Agile Daily Standup",
    },
    {
        "slug": "AGILE_SPRINT_PLANNING",
        "name": "Agile Sprint Planning",
        "department_code": "IT",
        "category_code": "AGILE_TEAM_RHYTHMS",
        "subcategory_code": "CEREMONIES",
        "unit_type": "meeting",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 2,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Agile Sprint Planning",
    },
    {
        "slug": "AGILE_SPRINT_REVIEW",
        "name": "Agile Sprint Review",
        "department_code": "IT",
        "category_code": "AGILE_TEAM_RHYTHMS",
        "subcategory_code": "CEREMONIES",
        "unit_type": "meeting",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 2,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Agile Sprint Review",
    },
    {
        "slug": "AGILE_RETROSPECTIVE",
        "name": "Agile Retrospective",
        "department_code": "IT",
        "category_code": "AGILE_TEAM_RHYTHMS",
        "subcategory_code": "CEREMONIES",
        "unit_type": "meeting",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 2,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Agile Retrospective",
    },
    {
        "slug": "AGILE_PBR_SESSION",
        "name": "Agile PBR Session",
        "department_code": "IT",
        "category_code": "AGILE_TEAM_RHYTHMS",
        "subcategory_code": "CEREMONIES",
        "unit_type": "meeting",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 2,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Product Backlog Refinement Session (was 'PBR Session')",
    },
    {
        "slug": "REQUIREMENTS_WALKTHROUGH_VIDEO",
        "name": "Requirements Walkthrough Video",
        "department_code": "IT",
        "category_code": "REQUIREMENTS_DOCUMENTATION",
        "subcategory_code": "REQUIREMENTS",
        "unit_type": "requirement",
        "unit_rate": Decimal("500.00"),
        "monthly_target_units": 4,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Requirements Walkthrough Video",
    },
    {
        "slug": "APP_DATA_ENTRY_TESTING_SUPPORT",
        "name": "App / Data Entry & Testing Support",
        "department_code": "IT",
        "category_code": "SUPPORT_TROUBLESHOOTING",
        "subcategory_code": "CLIENT_SUPPORT",
        "unit_type": "item",
        "unit_rate": Decimal("200.00"),
        "monthly_target_units": 10,
        "points_per_unit": Decimal("1.00"),
        "is_billable": False,
        "description": "Non-technical user entering data for testing",
    },
]

