# Generated by Django 3.2.6 on 2025-12-01 08:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professional_services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='background', max_length=200, null=True)),
                ('image_string', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='background', null=True)),
                ('service_image', models.ImageField(blank=True, default='background', null=True, upload_to='images/')),
                ('image_url', models.CharField(blank=True, default='background', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('mission', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('relation', models.IntegerField(choices=[(1, 'Client'), (2, 'Investor'), (3, 'Background'), (4, 'Other')], default=4)),
                ('logo', models.ImageField(blank=True, help_text='Company logo for receipts and emails (kept for future use)', null=True, upload_to='company_logos/')),
                ('receipt_email', models.EmailField(blank=True, help_text='Email address for sending receipts (e.g., info@domain.com)', max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, help_text="Display name for receipts (e.g., 'CODA ANALYTICS' or 'DC48K')", max_length=100, null=True)),
                ('address', models.CharField(blank=True, help_text='Company address for receipts', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999999.99)])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999999.99)])),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('contract_length', models.IntegerField(choices=[(1, 'One Month'), (2, 'Two Months'), (3, 'Three Months'), (12, 'Open')], default=3)),
                ('is_direct', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('redirect_url_path', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pricing',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(default='training', max_length=254)),
                ('slug', models.SlugField(default='slug', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_titles', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='WCAGStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('criteria', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('what_to_test', models.CharField(max_length=255)),
                ('how_to_test', models.TextField()),
                ('user_affected', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WCAGStandardWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('app_name', models.CharField(choices=[('accounts', 'accounts'), ('application', 'application'), ('finance', 'finance'), ('management', 'management'), ('data', 'data'), ('getdata', 'getdata'), ('investing', 'investing'), ('main', 'main'), ('projectmanagement', 'projectmanagement')], default='main', max_length=25)),
                ('page_name', models.CharField(blank=True, max_length=500, null=True)),
                ('website_url', models.CharField(blank=True, max_length=500, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('writer', models.ForeignKey(limit_choices_to=models.Q(('is_staff', True), ('category__in', [1, 3, 4, 5, 6, 7]), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='writer name')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('service', models.ForeignKey(default=main.models.ServiceCategory.get_default_service, on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accounts', 'Registration'), ('application', 'Application'), ('finance', 'Financial Information'), ('management', 'Employees Activities'), ('data', 'Data Analysis'), ('getdata', 'Automation'), ('investing', 'Investments'), ('main', 'General Information'), ('projectmanagement', 'Field Projects')], default='Other', max_length=25)),
                ('topic', models.CharField(default='Task', max_length=255)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('searched_by', models.ForeignKey(limit_choices_to=models.Q(('is_staff', True), ('category__in', [1, 3, 4, 5, 6, 7]), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search',
            },
        ),
        migrations.CreateModel(
            name='PricingSubPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999999.99)])),
                ('my_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pricing')),
            ],
            options={
                'verbose_name_plural': 'PricingSubPlan',
            },
        ),
        migrations.AddField(
            model_name='pricing',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.servicecategory'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Financial', 'Financial'), ('Health', 'Health'), ('Family', 'Family'), ('Work', 'Work'), ('Meetings', 'Meetings'), ('Other', 'Other')], default='Other', max_length=25)),
                ('goal', models.CharField(choices=[('Business', 'Business'), ('Employment', 'Employment'), ('Savings', 'Savings'), ('Insurance', 'Insurance'), ('Relationship', 'Relationship'), ('Trips', 'Trips'), ('Other', 'Other')], default='Other', max_length=25)),
                ('status', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=25)),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=25)),
                ('task', models.CharField(default='CODA', max_length=255)),
                ('duration', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.TextField()),
                ('why', models.TextField()),
                ('how', models.TextField()),
                ('comments', models.TextField(blank=True, default='No Comment', null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='Uploads/Support_Docs/')),
                ('pptlink', models.CharField(blank=True, default='link', max_length=300, null=True)),
                ('videolink', models.CharField(blank=True, default='Video', max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_answered', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('planner', models.ForeignKey(blank=True, default=1, limit_choices_to=models.Q(('is_admin', True), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner', to=settings.AUTH_USER_MODEL)),
                ('responsible_party', models.ForeignKey(default=1, limit_choices_to=models.Q(('is_staff', True), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Plan',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(blank=True, null=True)),
                ('time_zone', models.CharField(choices=[('PST', 'PST'), ('CST', 'CST'), ('EST', 'EST'), ('EAT', 'EAT')], default='CST', max_length=4, null=True)),
                ('activity_links', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_links', to='professional_services.activitylinks')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Categories', to='professional_services.featuredcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='professional_services.featuredsubcategory')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='professional_services.featuredactivity')),
            ],
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='main_servic_is_acti_450399_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured'], name='main_servic_is_feat_79e781_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['company'], name='main_servic_company_829555_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='main_servic_slug_57a981_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['created_at'], name='main_plan_created_3dded7_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['updated_at'], name='main_plan_updated_c76201_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active'], name='main_plan_is_acti_adb061_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_featured'], name='main_plan_is_feat_be0d35_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['category'], name='main_plan_categor_0348e9_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['goal'], name='main_plan_goal_7d6a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status'], name='main_plan_status_766519_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['planner'], name='main_plan_planner_af8b35_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['responsible_party'], name='main_plan_respons_c49595_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active', 'is_featured'], name='main_plan_is_acti_12d341_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['category', 'is_active'], name='main_plan_categor_ec8fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['planner', 'is_active'], name='main_plan_planner_2fc4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['created_at', 'is_active'], name='main_plan_created_a9e77e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='main_compan_created_b61037_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='main_compan_is_acti_c6fa0f_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_featured'], name='main_compan_is_feat_93bd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['relation'], name='main_compan_relatio_31f334_idx'),
        ),
    ]
