# Generated by Django 3.2.6 on 2025-09-18 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('gpt4_primary', 'GPT-4 Primary Model'), ('gpt35_fallback', 'GPT-3.5 Fallback Model'), ('claude3_backup', 'Claude-3 Backup Model'), ('local_offline', 'Local Offline Model')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_order', models.IntegerField(default=1)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('temperature', models.FloatField(default=0.3)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_model_configuration',
                'ordering': ['priority_order'],
            },
        ),
        migrations.AlterField(
            model_name='usecase',
            name='app',
            field=models.CharField(choices=[('main', 'main'), ('accounts', 'accounts'), ('application', 'application'), ('professional_services', 'professional_services'), ('ai_services', 'ai_services'), ('investing', 'investing'), ('management', 'management'), ('finance', 'finance'), ('marketing', 'marketing'), ('unified_dashboard', 'unified_dashboard')], default='Other', max_length=100),
        ),
        migrations.CreateModel(
            name='UserBehaviorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('form_start', 'Form Started'), ('form_submit', 'Form Submitted'), ('analysis_complete', 'Analysis Completed'), ('result_view', 'Results Viewed'), ('download', 'File Downloaded'), ('share', 'Content Shared'), ('error', 'Error Encountered'), ('session_start', 'Session Started'), ('session_end', 'Session Ended')], max_length=50)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('analysis_type', models.CharField(blank=True, choices=[('remittance_analysis', 'Remittance Analysis'), ('trade_facilitation', 'Trade Facilitation'), ('investment_opportunities', 'Investment Opportunities'), ('education_pathways', 'Education Pathways'), ('healthcare_access', 'Healthcare Access')], max_length=50, null=True)),
                ('event_data', models.JSONField(default=dict, help_text='Additional event-specific data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_behavior_analytics',
            },
        ),
        migrations.CreateModel(
            name='DiasporaAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('analysis_type', models.CharField(choices=[('remittance_analysis', 'Remittance Analysis'), ('trade_facilitation', 'Trade Facilitation'), ('investment_opportunities', 'Investment Opportunities'), ('education_pathways', 'Education Pathways'), ('healthcare_access', 'Healthcare Access')], max_length=50)),
                ('user_input', models.JSONField()),
                ('ai_prediction', models.JSONField()),
                ('model_used', models.CharField(choices=[('gpt4_primary', 'GPT-4 Primary Model'), ('gpt35_fallback', 'GPT-3.5 Fallback Model'), ('claude3_backup', 'Claude-3 Backup Model'), ('local_offline', 'Local Offline Model')], max_length=100)),
                ('confidence_score', models.FloatField()),
                ('processing_time', models.FloatField()),
                ('fallback_used', models.BooleanField(default=False)),
                ('is_real_ai', models.BooleanField(default=False, help_text='Whether this used real AI or fallback data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaspora_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diaspora_analysis_data',
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_analyses', models.IntegerField(default=0)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('presentation_mode', models.BooleanField(default=False)),
                ('stakeholder_type', models.CharField(blank=True, choices=[('investor', 'Investor'), ('government', 'Government Representative'), ('diaspora', 'Diaspora Member'), ('general', 'General Public')], max_length=50, null=True)),
                ('is_authenticated_session', models.BooleanField(default=False, help_text='Whether this is an authenticated user session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_session',
            },
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['session_id', 'event_type'], name='user_behavi_session_f07319_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['timestamp'], name='user_behavi_timesta_a6bd97_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['analysis_type'], name='user_behavi_analysi_b7d0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['user', 'timestamp'], name='user_behavi_user_id_5bcefc_idx'),
        ),
        migrations.AddIndex(
            model_name='diasporaanalysisdata',
            index=models.Index(fields=['session_id', 'analysis_type'], name='diaspora_an_session_bf5d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='diasporaanalysisdata',
            index=models.Index(fields=['created_at'], name='diaspora_an_created_f7ccd8_idx'),
        ),
        migrations.AddIndex(
            model_name='diasporaanalysisdata',
            index=models.Index(fields=['model_used'], name='diaspora_an_model_u_3a9804_idx'),
        ),
    ]
