# Generated by Django 4.2.27 on 2026-01-09 09:42

from django.db import migrations, models
import onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=onboarding.models.default_token_expiry,
                help_text="When this token expires (24 hours from creation)",
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.CharField(
                default=onboarding.models.default_token_value,
                help_text="Unique verification token",
                max_length=100,
                unique=True,
            ),
        ),
    ]
