# Generated by Django 4.2.27 on 2026-01-06 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCVerificationLevel",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="kyc_level",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic - Email Verified"),
                            ("standard", "Standard - ID Document Verified"),
                            ("enhanced", "Enhanced - ID + Address Verified"),
                            ("premium", "Premium - Full KYC Completed"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("identity_verified", models.BooleanField(default=False)),
                ("address_verified", models.BooleanField(default=False)),
                ("business_verified", models.BooleanField(default=False)),
                (
                    "transaction_limit_daily",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily transaction limit in USD",
                        max_digits=10,
                    ),
                ),
                ("can_invest", models.BooleanField(default=False)),
                ("can_receive_investment", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KYC Verification Level",
                "verbose_name_plural": "KYC Verification Levels",
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("passport", "Passport"),
                            ("drivers_license", "Driver's License"),
                            ("business_registration", "Business Registration Certificate"),
                            ("tax_certificate", "Tax Registration Certificate"),
                            ("proof_of_address", "Proof of Address (Utility Bill)"),
                            ("bank_statement", "Bank Statement"),
                            ("other", "Other Document"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        help_text="Allowed formats: PDF, JPG, PNG, DOC, DOCX. Max size: 10MB",
                        upload_to="kyc_documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document ID or reference number (if applicable)",
                        max_length=100,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("issuing_authority", models.CharField(blank=True, max_length=200)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Staff notes about verification decision"
                    ),
                ),
                (
                    "is_scanned",
                    models.BooleanField(
                        default=False, help_text="Whether document was scanned for viruses/malware"
                    ),
                ),
                ("scan_result", models.CharField(blank=True, max_length=200)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Document",
                "verbose_name_plural": "KYC Documents",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="kyc_kycdocu_user_id_ecb0b2_idx"),
                    models.Index(
                        fields=["status", "uploaded_at"], name="kyc_kycdocu_status_49c402_idx"
                    ),
                ],
            },
        ),
    ]
