# Generated by Django 3.2.6 on 2025-12-21 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_completed", "Interview Completed"),
                            ("skills_assessment", "Skills Assessment"),
                            ("assessment_completed", "Assessment Completed"),
                            ("final_review", "Final Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("employee", "Employee"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="applied",
                        help_text="Current status in the workflow",
                        max_length=20,
                    ),
                ),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic (Criteria Met)"),
                            ("manual", "Manual (Admin Override)"),
                            ("hybrid", "Hybrid (Criteria + Admin Approval)"),
                        ],
                        default="hybrid",
                        help_text="Type of promotion process",
                        max_length=10,
                    ),
                ),
                (
                    "documents_completed",
                    models.BooleanField(
                        default=False, help_text="All required documents submitted"
                    ),
                ),
                (
                    "skills_assessment_score",
                    models.IntegerField(
                        default=0, help_text="Total skills assessment score"
                    ),
                ),
                (
                    "interview_completed",
                    models.BooleanField(
                        default=False, help_text="Interview process completed"
                    ),
                ),
                (
                    "admin_approval",
                    models.BooleanField(
                        default=False, help_text="Admin approval given"
                    ),
                ),
                (
                    "min_skills_score",
                    models.IntegerField(
                        default=12, help_text="Minimum skills score required"
                    ),
                ),
                (
                    "min_interview_score",
                    models.IntegerField(
                        default=8, help_text="Minimum interview score required"
                    ),
                ),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("last_status_change", models.DateTimeField(auto_now=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about the application"
                    ),
                ),
                (
                    "applicant",
                    models.OneToOneField(
                        help_text="The applicant going through the workflow",
                        limit_choices_to={"category": 1, "is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this application",
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Workflow",
                "verbose_name_plural": "Application Workflows",
                "db_table": "application_workflow",
                "ordering": ["-applied_date"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "upload_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("Leave", "Leave"),
                            ("Working Hours", "Working Hours"),
                            ("Working Days", "Working Days"),
                            ("Unpaid Training", "Unpaid_Training"),
                            ("Location", "Location"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=25,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "policy_doc",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="policy/doc/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(
                        choices=[
                            ("projectDescription", "projectDescription"),
                            ("requirementsAnalysis ", "requirementsAnalysis "),
                            ("development", "development"),
                            ("testing", "testing"),
                            ("deployment", "deployment"),
                        ],
                        default="Other",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowCriteria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Criteria name", max_length=100, unique=True
                    ),
                ),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("documents", "Document Completion"),
                            ("skills_score", "Skills Assessment Score"),
                            ("interview_score", "Interview Score"),
                            ("admin_approval", "Admin Approval Required"),
                            ("time_based", "Time-based Criteria"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_value",
                    models.IntegerField(
                        blank=True, help_text="Minimum value required", null=True
                    ),
                ),
                (
                    "max_value",
                    models.IntegerField(
                        blank=True, help_text="Maximum value allowed", null=True
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True, help_text="Is this criteria required?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this criteria active?"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the criteria"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workflow Criteria",
                "verbose_name_plural": "Workflow Criteria",
                "db_table": "application_workflow_criteria",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStatusLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="application.applicationworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Status Log",
                "verbose_name_plural": "Workflow Status Logs",
                "db_table": "application_workflow_status_log",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Trainee_Assessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "data_tools",
                    models.CharField(
                        choices=[
                            ("ETL", "ETL"),
                            ("Reporting", "Reporting"),
                            ("Database", "Database"),
                            ("Website", "Website"),
                            ("SAS", "SAS"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=255,
                    ),
                ),
                (
                    "audibility",
                    models.IntegerField(
                        choices=[
                            (1, "Excellent"),
                            (2, "Very Good"),
                            (3, "Good"),
                            (4, "Below Average"),
                        ],
                        default=999,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        choices=[
                            (1, "Excellent"),
                            (2, "Very Good"),
                            (3, "Good"),
                            (4, "Below Average"),
                        ],
                        default=999,
                    ),
                ),
                ("duration", models.IntegerField(default=0)),
                (
                    "uploadlinkurl",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        limit_choices_to=models.Q(("is_staff", True)),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessor_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("topic", models.ManyToManyField(blank=True, to="application.Topic")),
                (
                    "trainee_username",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        limit_choices_to=models.Q(
                            ("is_staff", True), ("category", 1), _connector="OR"
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reporting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("rate", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("Internal Interview", "Internal Interview"),
                            ("First Interview", "First Interview"),
                            ("Second Interview", "Second Interview"),
                            ("Third Interview", "Third Interview"),
                            ("Other", "Other"),
                        ],
                        default="other",
                        max_length=25,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[("Direct", "Direct"), ("Indirect", "Indirect")],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "reporting_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reporting Date(mm/dd/yyyy)"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("comment", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reporting_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rated",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Exam", "Exam"),
                            ("Symbosium", "Symbosium"),
                            ("Exam_ChatGPT", "Exam_ChatGPT"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=255,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Kiswahili", "Kiswahili"),
                            ("Math", "Math"),
                            ("Business", "Business"),
                            ("Physics", "Physics"),
                            ("Chemistry", "Chemistry"),
                            ("Biology", "Biology"),
                            ("GHC", "GHC"),
                            ("History", "History"),
                            ("CRE", "CRE"),
                            ("Agriculture", "Agriculture"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=255,
                    ),
                ),
                (
                    "data_tools",
                    models.CharField(
                        choices=[
                            ("Alteryx", "Alteryx"),
                            ("Tableau", "Tableau"),
                            ("Database", "Database"),
                            ("Python", "Python"),
                            ("SAS", "SAS"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=255,
                    ),
                ),
                (
                    "uploadlinkurl",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "rating_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("projectDescription", models.BooleanField(default=False)),
                ("requirementsAnalysis", models.BooleanField(default=False)),
                ("development", models.BooleanField(default=False)),
                ("testing", models.BooleanField(default=False)),
                ("deployment", models.BooleanField(default=False)),
                ("totalpoints", models.IntegerField(default=0)),
                (
                    "employeename",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        limit_choices_to=models.Q(
                            ("is_staff", True), ("category", 1), _connector="OR"
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_empname",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="applicationworkflow",
            index=models.Index(fields=["status"], name="application_status_b0b799_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationworkflow",
            index=models.Index(
                fields=["applicant"], name="application_applica_84b527_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationworkflow",
            index=models.Index(
                fields=["applied_date"], name="application_applied_1ae02c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationworkflow",
            index=models.Index(
                fields=["promotion_type"], name="application_promoti_f805a3_idx"
            ),
        ),
    ]
