# Generated by Django 3.2.6 on 2025-09-20 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='duration',
            field=models.PositiveIntegerField(default=12, help_text='Loan duration in months'),
        ),
        migrations.AlterField(
            model_name='payslipconfig',
            name='installment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 1, 22, 40, 5, 927344), null=True),
        ),
    ]
