# Generated by Django 3.2.6 on 2026-01-20 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='Budget categories this policy applies to', to='finance.BudgetCategory'),
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this policy applies to', to='accounts.Department'),
        ),
        migrations.AddField(
            model_name='automationauditlog',
            name='budget_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.budgetrequest'),
        ),
        migrations.AddField(
            model_name='automationauditlog',
            name='disbursement_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.disbursementrequest'),
        ),
        migrations.AddField(
            model_name='automationauditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancesheetcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.balancesheetcategory'),
        ),
        migrations.AddField(
            model_name='budget',
            name='approval_policy',
            field=models.ForeignKey(blank=True, help_text='The approval policy applicable to this budget', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.approvalpolicy'),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the budget', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_lead',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('category', 2), ('is_active', True), ('is_staff', True)), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_type', to='main.company'),
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_type', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='budget',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_type', to='finance.budgetsubcategory'),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_budget_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgetestimateprojection',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='budgetitemlibrary',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Budget category this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgetitemlibrary',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Budget subcategory this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.budgetsubcategory'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='approval_policy',
            field=models.ForeignKey(blank=True, help_text='Approval policy applied to this request', null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.approvalpolicy'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='budget_category',
            field=models.ForeignKey(blank=True, help_text='Budget category for this request', null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_budget_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='current_approver',
            field=models.ForeignKey(blank=True, help_text='Current approver in the chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department requesting the budget', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified the request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_budget_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_budget_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='requester',
            field=models.ForeignKey(blank=True, help_text='User who submitted the request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetsubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='codabudget',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company this budget belongs to', on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
        migrations.AddField(
            model_name='codabudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codabudget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dc48_inflow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentannouncement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='budget_request',
            field=models.ForeignKey(blank=True, help_text='Associated budget request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_requests', to='finance.budgetrequest'),
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the disbursement request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_disbursement_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='field_expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financenotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loannotification',
            name='loan_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='finance.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loannotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.loanapplication'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='web_budget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_web_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='websubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.webcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitemlibrary',
            unique_together={('category', 'subcategory', 'item_name')},
        ),
        migrations.AlterUniqueTogether(
            name='foodinventory',
            unique_together={('food_item', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='loanrollover',
            unique_together={('original_loan', 'rollover_number')},
        ),
        migrations.AlterUniqueTogether(
            name='websubcategory',
            unique_together={('name', 'category')},
        ),
        migrations.AddIndex(
            model_name='approvalpolicy',
            index=models.Index(fields=['is_active'], name='finance_app_is_acti_af6748_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalpolicy',
            index=models.Index(fields=['min_amount'], name='finance_app_min_amo_36e6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='automationauditlog',
            index=models.Index(fields=['action'], name='finance_aut_action_b40bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='automationauditlog',
            index=models.Index(fields=['user'], name='finance_aut_user_id_95e03e_idx'),
        ),
        migrations.AddIndex(
            model_name='automationauditlog',
            index=models.Index(fields=['created_at'], name='finance_aut_created_e939f6_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['status'], name='finance_bud_status_e26806_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['requester'], name='finance_bud_request_38890f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['department'], name='finance_bud_departm_070e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['request_date'], name='finance_bud_request_4ca576_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['priority'], name='finance_bud_priorit_a9ef87_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursementrequest',
            index=models.Index(fields=['status'], name='finance_dis_status_91d4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursementrequest',
            index=models.Index(fields=['budget_request'], name='finance_dis_budget__5b2f48_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursementrequest',
            index=models.Index(fields=['disbursement_date'], name='finance_dis_disburs_424bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='finance_foo_name_c72b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category'], name='finance_foo_categor_5300d9_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['is_active'], name='finance_foo_is_acti_a2e7af_idx'),
        ),
        migrations.AddIndex(
            model_name='foodconsumptionlog',
            index=models.Index(fields=['inventory', '-consumption_date'], name='finance_foo_invento_bcb8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='foodconsumptionlog',
            index=models.Index(fields=['-consumption_date'], name='finance_foo_consump_eb77d2_idx'),
        ),
        migrations.AddIndex(
            model_name='foodinventory',
            index=models.Index(fields=['food_item', 'location'], name='finance_foo_food_it_27e892_idx'),
        ),
        migrations.AddIndex(
            model_name='foodinventory',
            index=models.Index(fields=['status'], name='finance_foo_status_572139_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpricehistory',
            index=models.Index(fields=['food', '-change_date'], name='finance_foo_food_id_73716b_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpricehistory',
            index=models.Index(fields=['-change_date'], name='finance_foo_change__0b0c44_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpurchasetransaction',
            index=models.Index(fields=['food_item', '-purchase_date'], name='finance_foo_food_it_cd6073_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpurchasetransaction',
            index=models.Index(fields=['-purchase_date'], name='finance_foo_purchas_4fa2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpurchasetransaction',
            index=models.Index(fields=['supplier'], name='finance_foo_supplie_e96798_idx'),
        ),
        migrations.AddIndex(
            model_name='foodrestockrequest',
            index=models.Index(fields=['inventory', 'status'], name='finance_foo_invento_f69119_idx'),
        ),
        migrations.AddIndex(
            model_name='foodrestockrequest',
            index=models.Index(fields=['-created_at'], name='finance_foo_created_9f2092_idx'),
        ),
        migrations.AddIndex(
            model_name='foodrestockrequest',
            index=models.Index(fields=['status'], name='finance_foo_status_cf7ec8_idx'),
        ),
    ]
