# Generated by Django 4.2.7 on 2024-12-19 12:00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
        ('main', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the approval policy', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of the policy')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is active')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount for this policy to apply', max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount for this policy to apply', max_digits=10, null=True)),
                ('approver_roles', models.JSONField(default=list, help_text='List of roles that can approve under this policy')),
                ('approval_chain', models.JSONField(default=list, help_text='Sequential approval chain configuration')),
                ('auto_approve', models.BooleanField(default=False, help_text='Whether to auto-approve requests under this policy')),
                ('requires_otp', models.BooleanField(default=True, help_text='Whether OTP verification is required')),
                ('applicable_user_types', models.JSONField(default=list, help_text='User types this policy applies to (Staff, KCC, External)')),
                ('max_approval_days', models.PositiveIntegerField(default=7, help_text='Maximum days for approval')),
                ('escalation_days', models.PositiveIntegerField(default=3, help_text='Days before escalation')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Budget categories this policy applies to', related_name='approval_policies', to='finance.budgetcategory')),
                ('applicable_departments', models.ManyToManyField(blank=True, help_text='Departments this policy applies to', related_name='approval_policies', to='accounts.department')),
            ],
            options={
                'verbose_name': 'Approval Policy',
                'verbose_name_plural': 'Approval Policies',
                'ordering': ['min_amount'],
                'indexes': [
                    models.Index(fields=['is_active'], name='finance_approvalpolicy_is_active_idx'),
                    models.Index(fields=['min_amount'], name='finance_approvalpolicy_min_amount_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AutomationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(help_text='Action performed', max_length=100)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('disburse', 'Disburse'), ('otp_send', 'OTP Send'), ('otp_verify', 'OTP Verify'), ('escalate', 'Escalate'), ('cancel', 'Cancel')], help_text='Type of action', max_length=50)),
                ('description', models.TextField(help_text='Description of the action')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the user')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the affected object', max_length=255)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('old_values', models.JSONField(default=dict, help_text='Old values before the action')),
                ('new_values', models.JSONField(default=dict, help_text='New values after the action')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the affected object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automation Audit Log',
                'verbose_name_plural': 'Automation Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['action'], name='finance_automationauditlog_action_idx'),
                    models.Index(fields=['user'], name='finance_automationauditlog_user_idx'),
                    models.Index(fields=['created_at'], name='finance_automationauditlog_created_at_idx'),
                    models.Index(fields=['content_type', 'object_id'], name='finance_automationauditlog_content_type_object_id_idx'),
                    models.Index(fields=['action_type'], name='finance_automationauditlog_action_type_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('purpose', models.TextField(help_text='Purpose of the budget request')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when request was submitted')),
                ('required_date', models.DateField(help_text='Date when budget is required')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the request', max_length=20)),
                ('approval_chain', models.JSONField(default=list, help_text='List of approvers in the approval chain')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('disbursed', 'Disbursed')], default='draft', help_text='Current status of the request', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('cost_center', models.CharField(blank=True, help_text='Cost center for the request', max_length=50)),
                ('attachments', models.JSONField(default=list, help_text='List of attached documents')),
                ('approval_policy', models.ForeignKey(blank=True, help_text='Approval policy applied to this request', null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.approvalpolicy')),
                ('budget_category', models.ForeignKey(help_text='Budget category for this request', on_delete=django.db.models.deletion.CASCADE, to='finance.budgetcategory')),
                ('created_by', models.ForeignKey(help_text='User who created the request', on_delete=django.db.models.deletion.CASCADE, related_name='created_budget_requests', to=settings.AUTH_USER_MODEL)),
                ('current_approver', models.ForeignKey(blank=True, help_text='Current approver in the chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department requesting the budget', on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('last_modified_by', models.ForeignKey(help_text='User who last modified the request', on_delete=django.db.models.deletion.CASCADE, related_name='modified_budget_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='User who submitted the request', on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Request',
                'verbose_name_plural': 'Budget Requests',
                'ordering': ['-request_date'],
                'indexes': [
                    models.Index(fields=['status'], name='finance_budgetrequest_status_idx'),
                    models.Index(fields=['requester'], name='finance_budgetrequest_requester_idx'),
                    models.Index(fields=['department'], name='finance_budgetrequest_department_idx'),
                    models.Index(fields=['request_date'], name='finance_budgetrequest_request_date_idx'),
                    models.Index(fields=['priority'], name='finance_budgetrequest_priority_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DisbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursement_method', models.CharField(choices=[('mpesa', 'MPESA'), ('bank_transfer', 'Bank Transfer'), ('stanbic', 'Stanbic Bank'), ('cash', 'Cash'), ('check', 'Check')], help_text='Method of disbursement', max_length=50)),
                ('recipient_name', models.CharField(help_text='Name of the recipient', max_length=255)),
                ('recipient_phone', models.CharField(blank=True, help_text='Phone number of the recipient', max_length=20)),
                ('recipient_email', models.EmailField(blank=True, help_text='Email of the recipient')),
                ('bank_account', models.CharField(blank=True, help_text='Bank account number if applicable', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be disbursed', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency of the disbursement', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate applied', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the disbursement', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment provider', max_length=100)),
                ('otp_code', models.CharField(blank=True, help_text='OTP code for verification', max_length=10)),
                ('otp_expires_at', models.DateTimeField(blank=True, help_text='OTP expiration time', null=True)),
                ('otp_verified', models.BooleanField(default=False, help_text='Whether OTP has been verified')),
                ('disbursement_date', models.DateTimeField(blank=True, help_text='Date when disbursement was processed', null=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date when disbursement was completed', null=True)),
                ('budget_request', models.OneToOneField(help_text='Associated budget request', on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_request', to='finance.budgetrequest')),
            ],
            options={
                'verbose_name': 'Disbursement Request',
                'verbose_name_plural': 'Disbursement Requests',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status'], name='finance_disbursementrequest_status_idx'),
                    models.Index(fields=['disbursement_method'], name='finance_disbursementrequest_disbursement_method_idx'),
                    models.Index(fields=['disbursement_date'], name='finance_disbursementrequest_disbursement_date_idx'),
                ],
            },
        ),
    ]
