# Generated by Django 3.2.6 on 2025-09-25 23:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
        ('finance', '0002_add_automation_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='approvalpolicy',
            name='finance_approvalpolicy_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalpolicy',
            name='finance_approvalpolicy_min_amount_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationauditlog',
            name='finance_automationauditlog_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationauditlog',
            name='finance_automationauditlog_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationauditlog',
            name='finance_automationauditlog_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationauditlog',
            name='finance_automationauditlog_content_type_object_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='automationauditlog',
            name='finance_automationauditlog_action_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetrequest',
            name='finance_budgetrequest_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetrequest',
            name='finance_budgetrequest_requester_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetrequest',
            name='finance_budgetrequest_department_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetrequest',
            name='finance_budgetrequest_request_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetrequest',
            name='finance_budgetrequest_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursementrequest',
            name='finance_disbursementrequest_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursementrequest',
            name='finance_disbursementrequest_disbursement_method_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursementrequest',
            name='finance_disbursementrequest_disbursement_date_idx',
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationauditlog',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationauditlog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='modification_reason',
            field=models.TextField(blank=True, help_text='Reason for the last modification', null=True),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_finance_disbursementrequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='modification_reason',
            field=models.TextField(blank=True, help_text='Reason for the last modification', null=True),
        ),
        migrations.AlterField(
            model_name='approvalpolicy',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='Budget categories this policy applies to', to='finance.BudgetCategory'),
        ),
        migrations.AlterField(
            model_name='approvalpolicy',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this policy applies to', to='accounts.Department'),
        ),
        migrations.AlterField(
            model_name='approvalpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvalpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='automationauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='automationauditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslipconfig',
            name='installment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 1, 23, 43, 43, 655441), null=True),
        ),
        migrations.AddIndex(
            model_name='approvalpolicy',
            index=models.Index(fields=['is_active'], name='finance_app_is_acti_af6748_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalpolicy',
            index=models.Index(fields=['min_amount'], name='finance_app_min_amo_36e6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='automationauditlog',
            index=models.Index(fields=['action'], name='finance_aut_action_b40bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='automationauditlog',
            index=models.Index(fields=['user'], name='finance_aut_user_id_95e03e_idx'),
        ),
        migrations.AddIndex(
            model_name='automationauditlog',
            index=models.Index(fields=['created_at'], name='finance_aut_created_e939f6_idx'),
        ),
        migrations.AddIndex(
            model_name='automationauditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='finance_aut_content_bb5fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='automationauditlog',
            index=models.Index(fields=['action_type'], name='finance_aut_action__0a3d53_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['status'], name='finance_bud_status_e26806_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['requester'], name='finance_bud_request_38890f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['department'], name='finance_bud_departm_070e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['request_date'], name='finance_bud_request_4ca576_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['priority'], name='finance_bud_priorit_a9ef87_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursementrequest',
            index=models.Index(fields=['status'], name='finance_dis_status_91d4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursementrequest',
            index=models.Index(fields=['disbursement_method'], name='finance_dis_disburs_049851_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursementrequest',
            index=models.Index(fields=['disbursement_date'], name='finance_dis_disburs_424bc7_idx'),
        ),
    ]
