# Generated by Django 3.2.6 on 2025-10-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_enhanced_food_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipconfig',
            name='eom_bonus',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Employee of the Month bonus', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslipconfig',
            name='eoq_bonus',
            field=models.DecimalField(decimal_places=2, default=3000.0, help_text='Employee of the Quarter bonus', max_digits=10),
        ),
        migrations.AddField(
            model_name='payslipconfig',
            name='eoy_bonus',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Employee of the Year bonus', max_digits=10),
        ),
    ]
