# Generated by Django 3.2.6 on 2025-09-21 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_interest_rate_to_loan_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this loan application is active'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this loan application is featured'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_plan_id',
            field=models.IntegerField(default=1, help_text='Legacy loan plan ID'),
        ),
        migrations.AlterField(
            model_name='payslipconfig',
            name='installment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 1, 16, 21, 24, 522645), null=True),
        ),
    ]
