# Generated by Django 3.2.6 on 2025-09-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_enhance_budget_model'),
    ]

    operations = [
    ]
