# Generated by Django 5.2.6 on 2025-11-12 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_min_max_term_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE finance_loanproduct DROP COLUMN IF EXISTS max_term_months;",
            reverse_sql="""
                ALTER TABLE finance_loanproduct
                ADD COLUMN IF NOT EXISTS max_term_months integer DEFAULT 0 NOT NULL;
            """,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE finance_loanproduct DROP COLUMN IF EXISTS min_term_months;",
            reverse_sql="""
                ALTER TABLE finance_loanproduct
                ADD COLUMN IF NOT EXISTS min_term_months integer DEFAULT 0 NOT NULL;
            """,
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
