# Generated by Django 3.2.6 on 2025-09-29 18:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_add_supporting_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancollateral',
            name='equipment_condition_report',
            field=models.FileField(blank=True, help_text='Equipment condition assessment report', null=True, upload_to='collateral/equipment/'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='equipment_photos',
            field=models.JSONField(blank=True, default=list, help_text='Array of equipment photo URLs'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='equipment_serial_number',
            field=models.CharField(blank=True, help_text='Equipment serial number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='gps_device_id',
            field=models.CharField(blank=True, help_text='GPS device identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='gps_install_date',
            field=models.DateTimeField(blank=True, help_text='When GPS was installed', null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='gps_last_location',
            field=models.CharField(blank=True, help_text='Last known GPS location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='gps_last_update',
            field=models.DateTimeField(blank=True, help_text='Last GPS update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='gps_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline'), ('tampered', 'Tampered')], default='inactive', help_text='Current GPS tracking status', max_length=20),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='gps_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Enable GPS tracking for vehicle collateral'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='land_photos',
            field=models.JSONField(blank=True, default=list, help_text='Array of land photo URLs'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='land_survey_done',
            field=models.BooleanField(default=False, help_text='Professional land survey completed'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='land_survey_report',
            field=models.FileField(blank=True, help_text='Land survey report file', null=True, upload_to='collateral/surveys/'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='last_monitoring_check',
            field=models.DateTimeField(blank=True, help_text='Last monitoring check performed', null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='mitigation_measures',
            field=models.TextField(blank=True, help_text='Risk mitigation measures implemented', null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='monitoring_alerts',
            field=models.JSONField(blank=True, default=list, help_text='Array of monitoring alerts and notifications'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='monitoring_enabled',
            field=models.BooleanField(default=False, help_text='Enable real-time monitoring of collateral'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='monitoring_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('real_time', 'Real-time')], default='weekly', help_text='How often to monitor collateral', max_length=20),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='Identified risk factors'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Collateral risk score (0-100)'),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='title_deed_number',
            field=models.CharField(blank=True, help_text='Official title deed number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='title_deed_verification_date',
            field=models.DateTimeField(blank=True, help_text='When title was verified', null=True),
        ),
        migrations.AddField(
            model_name='loancollateral',
            name='title_deed_verified',
            field=models.BooleanField(default=False, help_text='Land title deed verified with government registry'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='actual_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual amount spent against this budget', max_digits=15),
        ),
        migrations.AlterField(
            model_name='budget',
            name='approval_policy',
            field=models.ForeignKey(blank=True, help_text='The approval policy applicable to this budget', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.approvalpolicy'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of approval', null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the budget', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('general', 'General Budget'), ('website_development', 'Website Development'), ('operations', 'Operations'), ('marketing', 'Marketing'), ('infrastructure', 'Infrastructure'), ('investment', 'Investment')], default='general', help_text='Type of budget (e.g., General, Website Development)', max_length=30),
        ),
        migrations.AlterField(
            model_name='budget',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically estimated amount', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='estimation_confidence',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Confidence score for automated estimation (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='budget',
            name='estimation_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('average_3_months', 'Average of Last 3 Months'), ('average_6_months', 'Average of Last 6 Months'), ('last_year_actual', 'Last Year Actual'), ('trend_analysis', 'Trend Analysis'), ('coda_development', 'CODA Development Estimation')], default='manual', help_text='Method used for budget estimation', max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='estimation_source',
            field=models.CharField(blank=True, help_text='Source of the estimation data (e.g., Transaction history)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='expected_roi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected Return on Investment (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='investment_type',
            field=models.CharField(blank=True, choices=[('equity', 'Equity Investment'), ('debt', 'Debt Investment'), ('capital_expenditure', 'Capital Expenditure'), ('r&d', 'Research & Development'), ('other', 'Other Investment')], help_text='Type of investment if applicable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='is_investment',
            field=models.BooleanField(default=False, help_text='Is this budget related to an investment?'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes for the budget', null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='payback_period',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected payback period in months', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project_description',
            field=models.TextField(blank=True, help_text='Description of the project', null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project if applicable', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Does this budget require approval?'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the budget', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='timeframe',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('multi_year', 'Multi-Year')], default='monthly', help_text='Timeframe for the budget', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Variance (Actual - Budgeted)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='budget',
            name='variance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Variance as a percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payslipconfig',
            name='installment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 1, 18, 24, 19, 662736), null=True),
        ),
    ]
