# Generated by Django 3.2.6 on 2025-09-23 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_payslipconfig_installment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipconfig',
            name='installment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 1, 3, 21, 47, 341287), null=True),
        ),
    ]
