# Generated by Django 3.2.6 on 2025-11-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_loanproduct_max_term_months_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_history',
            options={'managed': False, 'ordering': ['-contract_submitted_date']},
        ),
        migrations.AlterModelOptions(
            name='payment_information',
            options={'managed': False, 'ordering': ['-contract_submitted_date']},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE finance_loanproduct DROP COLUMN IF EXISTS max_term_months;",
            reverse_sql="-- Cannot reverse: Field may not have existed",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE finance_loanproduct DROP COLUMN IF EXISTS min_term_months;",
            reverse_sql="-- Cannot reverse: Field may not have existed",
        ),
    ]
