# Generated by Django 3.2.6 on 2025-09-29 19:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userprofile_country'),
        ('finance', '0001_initial'),  # Changed from 0007_fix_budget_subcategory_field (doesn't exist)
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipconfig',
            name='installment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 1, 19, 28, 8, 433429), null=True),
        ),
        migrations.CreateModel(
            name='BudgetEstimateProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(choices=[('monthly', 'Monthly'), ('two_year', '2 Years'), ('five_year', '5 Years')], default='monthly', max_length=20)),
                ('method', models.CharField(default='average', max_length=30)),
                ('estimates', models.JSONField(default=dict)),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_projections', to='main.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_projections', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_projections', to='accounts.department')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budgetestimationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
