# Generated by Django 3.2.6 on 2025-11-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20251118_0801'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE finance_loanproduct DROP COLUMN IF EXISTS max_term_months;",
            reverse_sql="-- Cannot reverse: Field may not have existed",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE finance_loanproduct DROP COLUMN IF EXISTS min_term_months;",
            reverse_sql="-- Cannot reverse: Field may not have existed",
        ),
        migrations.AlterModelTable(
            name='payment_history',
            table='finance_payment_history',
        ),
        migrations.AlterModelTable(
            name='payment_information',
            table='finance_payment_information',
        ),
    ]
