# Generated by Django 3.2.6 on 2025-09-29 23:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_add_supporting_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (USD, KES, EUR, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate used for conversion', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payslipconfig',
            name='installment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 1, 23, 59, 54, 195743), null=True),
        ),
        migrations.CreateModel(
            name='BudgetItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text="Specific item name (e.g., 'Office Rent', 'Software Licenses')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Quantity needed', max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time')], default='monthly', help_text='How often this item is needed', max_length=50)),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether this is a recurring expense')),
                ('is_essential', models.BooleanField(default=True, help_text='Whether this is an essential expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='finance.budgetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_items', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='finance.budgetsubcategory')),
            ],
            options={
                'verbose_name': 'Budget Item Detail',
                'verbose_name_plural': 'Budget Item Details',
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_quantity', models.DecimalField(decimal_places=2, help_text="User's estimated quantity", max_digits=10)),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, help_text="User's estimated unit cost", max_digits=10)),
                ('notes', models.TextField(blank=True, help_text="User's notes about this estimate")),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this item is approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_items', to=settings.AUTH_USER_MODEL)),
                ('item_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='finance.budgetitemdetail')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='finance.budgetestimateprojection')),
            ],
            options={
                'verbose_name': 'Budget Estimate Item',
                'verbose_name_plural': 'Budget Estimate Items',
                'unique_together': {('projection', 'item_detail')},
            },
        ),
    ]
