# Generated by Django - October 16, 2025

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20250929_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='approval_tier',
            field=models.CharField(
                choices=[
                    ('A', 'Tier A - Known/Recurring (Auto-Approve)'),
                    ('B', 'Tier B - Variable/Operational (Priority-Based)'),
                    ('C', 'Tier C - Strategic/Discretionary (Assessment Required)'),
                ],
                default='C',
                help_text='Approval tier determined by spending pattern analysis',
                max_length=1
            ),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='auto_approve_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Finance Manager can enable/disable auto-approval for this category'
            ),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='typical_monthly_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Typical monthly spending for this category (calculated from transaction data)',
                max_digits=12,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='variance_threshold',
            field=models.DecimalField(
                decimal_places=2,
                default=20.00,
                help_text='Percentage variance from typical that triggers manual review (default: 20%)',
                max_digits=5
            ),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='is_recurring',
            field=models.BooleanField(
                default=False,
                help_text='Whether this category has recurring spending patterns (detected from data)'
            ),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='last_pattern_analysis',
            field=models.DateTimeField(
                blank=True,
                help_text='Last time spending pattern analysis was run for this category',
                null=True
            ),
        ),
    ]

