# Generated by Django - October 16, 2025
# Safe idempotent migration using raw SQL

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_add_tier_fields_to_budget_category'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Add tier fields to finance_budgetcategory if they don't exist
            DO $$
            BEGIN
                -- Add approval_tier
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='finance_budgetcategory' AND column_name='approval_tier') THEN
                    ALTER TABLE finance_budgetcategory ADD COLUMN approval_tier VARCHAR(1) DEFAULT 'C' NOT NULL;
                END IF;
                
                -- Add auto_approve_enabled
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='finance_budgetcategory' AND column_name='auto_approve_enabled') THEN
                    ALTER TABLE finance_budgetcategory ADD COLUMN auto_approve_enabled BOOLEAN DEFAULT FALSE NOT NULL;
                END IF;
                
                -- Add typical_monthly_amount
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='finance_budgetcategory' AND column_name='typical_monthly_amount') THEN
                    ALTER TABLE finance_budgetcategory ADD COLUMN typical_monthly_amount NUMERIC(12, 2) NULL;
                END IF;
                
                -- Add variance_threshold
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='finance_budgetcategory' AND column_name='variance_threshold') THEN
                    ALTER TABLE finance_budgetcategory ADD COLUMN variance_threshold NUMERIC(5, 2) DEFAULT 20.00 NOT NULL;
                END IF;
                
                -- Add is_recurring
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='finance_budgetcategory' AND column_name='is_recurring') THEN
                    ALTER TABLE finance_budgetcategory ADD COLUMN is_recurring BOOLEAN DEFAULT FALSE NOT NULL;
                END IF;
                
                -- Add last_pattern_analysis
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='finance_budgetcategory' AND column_name='last_pattern_analysis') THEN
                    ALTER TABLE finance_budgetcategory ADD COLUMN last_pattern_analysis TIMESTAMP NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE finance_budgetcategory DROP COLUMN IF EXISTS approval_tier;
            ALTER TABLE finance_budgetcategory DROP COLUMN IF EXISTS auto_approve_enabled;
            ALTER TABLE finance_budgetcategory DROP COLUMN IF EXISTS typical_monthly_amount;
            ALTER TABLE finance_budgetcategory DROP COLUMN IF EXISTS variance_threshold;
            ALTER TABLE finance_budgetcategory DROP COLUMN IF EXISTS is_recurring;
            ALTER TABLE finance_budgetcategory DROP COLUMN IF EXISTS last_pattern_analysis;
            """
        ),
    ]

