# Generated by Django 3.2.6 on 2025-09-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20250923_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='payment_date',
            field=models.DateField(help_text='Date payment was made'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='payment_type',
            field=models.CharField(choices=[('regular', 'Regular Payment'), ('extra', 'Extra Payment'), ('late_fee', 'Late Fee')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='reference_number',
            field=models.CharField(help_text='Payment reference number', max_length=50, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='notes',
            field=models.TextField(blank=True, help_text='Payment notes', null=True),
        ),
    ]
