# Generated by Django 5.2.6 on 2025-10-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20250929_1928'),
        ('finance', '0010_add_vendor_and_location'),
        ('finance', '0011_add_budget_item_library'),
    ]

    operations = [
    ]
